const $=s=>document.querySelector(s);
const RAW_STATE='https://raw.githubusercontent.com/kyle8824/chatgptfarm/main/world/state.json';
let world=null,selectedMemoryAgent='agent-mara',lastDiscoveryCount=0,cameraMode='auto';
const FALLBACK_POS={camp:{x:64,y:34},creek:{x:48,y:19},berries:{x:29,y:31},log:{x:59,y:29},meadow:{x:43,y:31},edge:{x:78,y:42},forest:{x:14,y:38},stones:{x:73,y:24},clay:{x:86,y:21},reeds:{x:10,y:22}};
const PLACE_INFO={camp:['CAMP','⌂'],creek:['CREEK','≈'],berries:['BERRY PATCH','●'],log:['FALLEN LOG','▰'],stones:['STONE FIELD','∴'],clay:['CLAY BANK','◒'],reeds:['REED MARSH','≋'],edge:['FRONTIER','?']};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const relKey=(a,b)=>[a,b].sort().join('|');
const hourLabel=(h,m=0)=>`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;
const skillName=s=>String(s).replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase());
const locationName=p=>PLACE_INFO[p]?.[0]?.toLowerCase()||String(p||'unknown').replaceAll('_',' ');

function normalize(w){
  w.relationships||={'agent-ivo|agent-mara':{trust:34,familiarity:12,affinity:50,lastInteraction:null,sharedMemories:0,techniquesShared:0}};
  w.discoveries||=[];w.discovered||={};w.structures||={};w.liveThreads||=[];w.spatial||={locations:{}};w.dna||=[];w.history||=[];
  for(const a of w.agents||[]){a.skills||={};a.experiments||={};a.affordanceAttempts||={};a.inventory||={};a.memories||=[];a.mind||={};a.coordinates||=w.spatial.locations?.[a.position]||FALLBACK_POS[a.position]||FALLBACK_POS.meadow}
  return w;
}
async function loadCanonical(){
  for(const url of [`${RAW_STATE}?t=${Date.now()}`,`./world/state.json?t=${Date.now()}`]){
    try{const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const next=normalize(await response.json());const changed=!world||next.meta?.tickNumber!==world.meta?.tickNumber||next.day!==world.day||next.hour!==world.hour;const newDiscovery=world&&next.discoveries.length>lastDiscoveryCount;world=next;lastDiscoveryCount=world.discoveries.length;render(changed,newDiscovery);$('#saveState').textContent=`● ${world.meta?.mindMode==='ai'?'AI MINDS':'WORLD'} LIVE · ${world.version||'?'}`;return}catch(error){console.warn('World source unavailable',url,error)}
  }
  $('#saveState').textContent='● WORLD SYNC ERROR';
}
function heartbeatProgress(){if(!world)return 1;const advanced=world.meta?.lastAdvancedAt?new Date(world.meta.lastAdvancedAt).getTime():Date.now(),period=(world.meta?.heartbeatMinutes||5)*60000;return Math.max(0,Math.min(1,(Date.now()-advanced)/period))}
function phaseState(a){const plan=a.activeAction,p=heartbeatProgress();if(!plan?.phases?.length)return{phase:'idle',label:'Between actions',progress:1,x:a.coordinates?.x??50,y:a.coordinates?.y??50};const phase=plan.phases.find(x=>p>=x.start&&p<x.end)||plan.phases.at(-1),from=plan.from||a.coordinates,to=plan.to||a.coordinates;let x=to.x,y=to.y;if(plan.moving){const travel=plan.phases.find(x=>x.id==='travel');if(travel&&p<travel.start){x=from.x;y=from.y}else if(travel&&p<travel.end){const q=Math.max(0,Math.min(1,(p-travel.start)/(travel.end-travel.start)));x=from.x+(to.x-from.x)*q;y=from.y+(to.y-from.y)*q}}return{phase:phase.id,label:phase.label,progress:p,x,y}}
function currentFocusAgent(){if(!world?.agents?.length)return null;if(cameraMode!=='auto')return world.agents.find(a=>a.id===cameraMode)||world.agents[0];const top=world.liveThreads?.[0],threadAgent=top?.agentIds?.length?world.agents.find(a=>a.id===top.agentIds[0]):null;if(threadAgent)return threadAgent;return world.agents.find(a=>a.activeAction?.physicalProposal)||world.agents.find(a=>a.activeAction?.moving)||world.agents[0]}
function updateCameraButtons(){document.querySelectorAll('.camera-btn').forEach(b=>b.classList.toggle('active',b.dataset.camera===cameraMode))}
function applyCamera(){if(!world)return;const focus=currentFocusAgent(),scene=$('#worldScene'),halo=$('#focusHalo');if(!focus||!scene||!halo)return;const s=phaseState(focus),scale=cameraMode==='auto'?1.06:1.12,tx=(50-s.x)*.16,ty=(s.y-50)*.16;scene.style.transform=`translate(${tx}%,${ty}%) scale(${scale})`;halo.style.left=`${s.x}%`;halo.style.bottom=`${s.y}%`;$('#focusStatus').innerHTML=`${cameraMode==='auto'?'AUTO':'FOLLOW'} · <b>${esc(focus.name)}</b> · ${esc(s.label).toUpperCase()}`;$('#worldMode').textContent=`${world.meta?.mindMode==='ai'?'AI MINDS':'FALLBACK'} · ${world.meta?.pacing||'LIVE'}`}
function animateWorld(){if(!world)return;world.agents.forEach((a,i)=>{const el=$(i===0?'#maraSprite':'#ivoSprite');if(!el)return;const s=phaseState(a);el.style.left=`${s.x}%`;el.style.bottom=`${s.y}%`;el.classList.toggle('moving',s.phase==='travel');el.classList.toggle('acting',s.phase==='interact');const tag=el.querySelector('.agent-phase');if(tag)tag.textContent=s.label});applyCamera();const focus=currentFocusAgent();if(focus){const s=phaseState(focus),intent=focus.mind?.intent||focus.currentAction;$('#worldCaption').innerHTML=`<b>${esc(focus.name)} · ${esc(s.label)}</b><br>${esc(intent)}`}}
function needRow(name,value){const cls=value<32?'danger':value<52?'warning':'';return `<div class="need ${cls}"><label><span>${esc(name.toUpperCase())}</span><b>${Math.round(value||0)}%</b></label><div class="need-track"><i style="width:${Math.max(0,Math.min(100,value||0))}%"></i></div></div>`}
function invHTML(a){const items=Object.entries(a.inventory||{}).filter(([,v])=>v>0);return items.length?items.slice(0,8).map(([k,v])=>`<span class="inv">${esc(k.replace(/([A-Z])/g,' $1'))} ×${v}</span>`).join(''):'<span class="empty">nothing carried</span>'}
function latestBelief(a){const e=Object.entries(a.beliefs||{}).at(-1);return e?e[1]:'No explicit reflection yet.'}
function relationshipLabel(r){if((r?.familiarity||0)<20)return'Strangers';if((r?.trust||0)>70&&(r?.familiarity||0)>65)return'Trusted partners';if((r?.familiarity||0)>55)return'Companions';if((r?.familiarity||0)>30)return'Getting acquainted';return'Familiar faces'}
function renderAgentCards(){
  $('#agentCards').innerHTML=world.agents.map((a,i)=>{const s=phaseState(a),refs=a.mind?.lastReferencedMemoryIds||[],dna=world.dna.find(d=>d.agent_id===a.id),override=dna?.deviated_from_policy;return `<div class="panel agent-panel agent-panel-${i}"><div class="agent-head"><div class="portrait">${esc(a.name[0])}</div><div><small>${esc(locationName(a.position).toUpperCase())}</small><h2>${esc(a.name)}</h2><p>${esc(s.label)} · ${esc(a.currentAction)}</p></div></div><div class="agent-live"><label>CURRENT GOAL</label><p>${esc(a.mind?.currentGoal||'Respond to the world')}</p><label>INTENT</label><p>${esc(a.mind?.intent||a.currentAction)}</p><div class="agent-meta"><span>${a.mind?.brainMode==='ai'?'AI MIND':'FALLBACK'}</span><span>${Math.round((a.mind?.confidence||0)*100)}% confidence</span><span>${refs.length} memories used</span>${override?'<span>DEVIATED FROM UTILITY</span>':''}</div></div><div class="needs">${needRow('hydration',a.needs.hydration)}${needRow('satiety',a.needs.hunger)}${needRow('energy',a.needs.energy)}${needRow('warmth',a.needs.warmth)}</div><div class="inventory"><small>CARRIED</small><div>${invHTML(a)}</div></div><div class="agent-live"><label>LATEST REFLECTION</label><p>${esc(latestBelief(a))}</p></div></div>`}).join('')
}
function placeKnown(id){if(id==='clay')return!!world.discovered.clayBank;if(id==='reeds')return!!world.discovered.reedBed;return true}
function renderPlaces(){const root=$('#worldPlaces');if(!root)return;const locs=world.spatial?.locations||FALLBACK_POS;root.innerHTML=Object.entries(PLACE_INFO).map(([id,[label,icon]])=>{const p=locs[id]||FALLBACK_POS[id];if(!p)return'';const known=placeKnown(id);return `<div class="world-place ${known?'':'unknown'}" style="left:${p.x}%;bottom:${p.y}%"><span class="place-icon">${icon}</span><b>${known?label:'UNKNOWN'}</b></div>`}).join('');const camp=locs.camp||FALLBACK_POS.camp;for(const [id,dx,dy] of [['shelter',1,3],['fire',-3,-1],['cache',4,-2],['dryingRack',7,1]]){const el=$('#'+id);if(el){el.style.left=`${camp.x+dx}%`;el.style.bottom=`${camp.y+dy}%`}}$('#shelter').classList.toggle('hidden',!world.structures.shelter);$('#fire').classList.toggle('hidden',!world.structures.fire);$('#cache').classList.toggle('hidden',!world.structures.cache);$('#dryingRack').classList.toggle('hidden',!world.structures.dryingRack)}
function renderEnvironment(){const weather=$('#weatherLayer'),night=$('#nightLayer');weather.className=`weather-layer ${world.weather==='rain'?'rain':world.weather==='cloudy'?'cloudy':''}`;const h=currentProjectedClock().hour;night.classList.toggle('on',h<6||h>=20);$('#weatherLabel').textContent=`${world.temperature}°F · ${world.weather[0].toUpperCase()+world.weather.slice(1)}`}
function renderThreads(){const threads=world.liveThreads||[];$('#threadCount').textContent=`${threads.length} open`;$('#liveThreads').innerHTML=threads.length?threads.map(t=>`<article class="thread ${t.urgency>=85?'urgent':t.urgency>=60?'high':''}" data-agent="${esc(t.agentIds?.[0]||'')}"><div class="thread-head"><div><span class="thread-kind">${esc(t.kind)}</span><br><b>${esc(t.title)}</b></div><span class="urgency">${t.urgency}</span></div><p>${esc(t.summary)}</p></article>`).join(''):'<div class="dna-empty">No strong unresolved thread right now. The world is in a quieter stretch.</div>';const top=threads[0];$('#nowStrip').innerHTML=top?`<b>NOW:</b> ${esc(top.title)} · ${esc(top.summary)}`:'<b>NOW:</b> No urgent tension detected.';document.querySelectorAll('.thread[data-agent]').forEach(el=>el.addEventListener('click',()=>{const id=el.dataset.agent;if(id){cameraMode=id;updateCameraButtons();animateWorld()}}))}
function renderRelationship(){const[a,b]=world.agents,r=world.relationships[relKey(a.id,b.id)]||{trust:0,familiarity:0,affinity:50,sharedMemories:0,techniquesShared:0},label=relationshipLabel(r);$('#relationshipSummary').textContent=label;$('#relationshipChip').textContent=label.toUpperCase();$('#relationshipBody').innerHTML=[['Trust',r.trust],['Familiarity',r.familiarity],['Affinity',r.affinity]].map(([n,v])=>`<div class="rel-row"><label><span>${n}</span><b>${Math.round(v||0)}%</b></label><div class="rel-track"><i style="width:${Math.max(0,Math.min(100,v||0))}%"></i></div></div>`).join('')+`<div class="shared-knowledge"><b>${r.sharedMemories||0}</b><span>memories shared</span></div><div class="shared-knowledge"><b>${r.techniquesShared||0}</b><span>techniques taught</span></div>`}
function renderDiscoveries(){const d=world.discoveries||[];$('#discoveryCount').textContent=`${d.length} discover${d.length===1?'y':'ies'}`;$('#discoveries').innerHTML=d.length?d.slice(0,8).map(x=>`<article class="discovery"><header><h3>${esc(x.title)}</h3><code>${esc(x.id)}</code></header><p>${esc(x.detail)}</p><footer><span>Day ${x.day} · ${hourLabel(x.hour)} · ${esc(x.firstAgentName)}</span><span class="discovery-effect">${esc(x.effect)}</span></footer></article>`).join(''):'<div class="discovery-empty">Nothing has become a world-first yet.</div>'}
function renderFrontier(){const rows=[['●','Willow Basin','Camp, creek, berries, fallen wood and stones',true],['◒','Eastern clay bank','Sticky creek-bank clay',!!world.discovered.clayBank],['≋','Western reed marsh','Reeds and animal sign',!!world.discovered.reedBed],['?','Beyond the basin','Unknown territory',false]];$('#frontier').innerHTML=rows.map(([icon,title,copy,known])=>`<div class="frontier-row ${known?'':'unknown'}"><div class="frontier-icon">${icon}</div><div class="frontier-copy"><b>${esc(known?title:'Unknown')}</b><small>${esc(known?copy:'Not yet understood')}</small></div></div>`).join('')}
function renderMemories(){const a=world.agents.find(x=>x.id===selectedMemoryAgent)||world.agents[0];$('#memoryTitle').textContent=`What ${a.name} remembers`;$('#memoryMara').classList.toggle('active',a.id==='agent-mara');$('#memoryIvo').classList.toggle('active',a.id==='agent-ivo');$('#memories').innerHTML=a.memories?.length?a.memories.slice(0,16).map(m=>`<article class="memory"><b>${esc(m.id)}</b><p>${esc(m.text)}</p><footer><span>${esc(m.source)}</span><span class="confidence">${Math.round((m.confidence||0)*100)}%</span></footer></article>`).join(''):`<div class="dna-empty">No persistent memories yet.</div>`}
function renderHistory(){const h=world.history||[];$('#eventCount').textContent=`${h.length} events`;$('#timeline').innerHTML=h.length?h.slice(0,70).map(e=>{const cls=e.type==='discovery'?'discovery-event':e.type==='physical'?'physical-event':e.type==='attempt'?'attempt-event':e.type==='social'||e.type==='culture'?'social-event':'';return `<article class="event ${cls}"><time>D${e.day} · ${hourLabel(e.hour)}</time><div><b>${esc(e.title)}</b><p>${esc(e.detail)}</p></div></article>`}).join(''):'<div class="dna-empty">The world has no history yet.</div>'}
function renderDNA(){const dna=world.dna?.[0],el=$('#dnaInspector');if(!dna){el.innerHTML='<div class="dna-empty">Waiting for a canonical decision trace.</div>';return}const cf=(dna.memory_counterfactuals||[]).slice(0,3),proposal=dna.mind?.physical_proposal,outcome=dna.physics?.outcome;el.innerHTML=`<div class="dna-action"><small>${esc(dna.agent_name)} · ${esc(dna.mind?.brain_mode||'unknown')} MIND</small><strong>${esc(dna.action_label)}</strong><code>${esc(dna.decision_id)}</code></div><div class="agent-live"><label>GOAL</label><p>${esc(dna.mind?.goal||'')}</p><label>DECISION SUMMARY</label><p>${esc(dna.mind?.decision_summary||'')}</p><div class="agent-meta"><span>baseline: ${esc(dna.baseline_policy_action||'none')}</span>${dna.deviated_from_policy?'<span>AI CHOSE DIFFERENTLY</span>':''}</div></div>${proposal?`<div class="physical-box"><label>PHYSICAL PROPOSAL</label><p>${esc(proposal.verb)} ${esc(proposal.primaryObjectId)}${proposal.secondaryObjectId&&proposal.secondaryObjectId!=='none'?` + ${esc(proposal.secondaryObjectId)}`:''}</p><p>${esc(proposal.purpose||'')}</p></div>`:''}${outcome?`<div class="physical-box"><label>PHYSICS OUTCOME</label><p class="${outcome.success===false?'failed':'success'}">${esc(outcome.detail||'Resolved')}</p></div>`:''}<div class="cf-box"><small>MEMORY COUNTERFACTUAL</small>${cf.length?cf.map(c=>`<div class="cf"><code>− ${esc(c.removed_memory)}</code><span>${esc(c.original_action)} → <b class="${c.action_changed?'flip':''}">${esc(c.counterfactual_action)}</b></span></div>`).join(''):'<div class="cf"><span>Not tested: no memory intervention was run.</span></div>'}</div>`}
function renderGuardian(){const top=world.liveThreads?.[0],latest=world.dna?.[0],pivot=latest?.memory_counterfactuals?.find(x=>x.action_changed);let text=top?`Highest live tension: ${top.title}. ${top.summary}`:'No major live tension is currently detected.';if(pivot)text+=` One provisional replay changed the choice after removing ${pivot.removed_memory} from the context for ${latest.agent_name}'s latest choice.`;$('#guardianStatus').textContent=text}
function render(changed=false,newDiscovery=false){if(!world)return;$('#tickCount').textContent=world.meta?.tickNumber||0;$('#worldAge').textContent=`Day ${world.day}`;renderPlaces();renderEnvironment();renderThreads();renderAgentCards();renderRelationship();renderDiscoveries();renderFrontier();renderMemories();renderHistory();renderDNA();renderGuardian();updateProjectedClock();animateWorld();const advanced=world.meta?.lastAdvancedAt?new Date(world.meta.lastAdvancedAt):null;$('#lastAdvanced').textContent=advanced?`Last canonical heartbeat ${advanced.toLocaleTimeString([], {hour:'numeric',minute:'2-digit',second:'2-digit'})}`:'Awaiting first canonical heartbeat';if(changed){document.body.classList.add('world-updated');setTimeout(()=>document.body.classList.remove('world-updated'),1200)}if(newDiscovery){$('#discoveryPanel')?.classList.add('milestone-flash');setTimeout(()=>$('#discoveryPanel')?.classList.remove('milestone-flash'),1800)}}
function currentProjectedClock(){if(!world)return{day:1,hour:6,minute:0};const advanced=world.meta?.lastAdvancedAt?new Date(world.meta.lastAdvancedAt).getTime():Date.now(),elapsed=Math.max(0,Date.now()-advanced),period=(world.meta?.heartbeatMinutes||5)*60000,hoursPerBeat=world.meta?.worldHoursPerHeartbeat||1,worldMinutes=Math.min(hoursPerBeat*60-1,Math.floor((elapsed/period)*hoursPerBeat*60)),total=world.hour*60+worldMinutes,dayOffset=Math.floor(total/(24*60)),clock=total%(24*60);return{day:world.day+dayOffset,hour:Math.floor(clock/60),minute:clock%60}}
function updateProjectedClock(){if(!world)return;const c=currentProjectedClock();$('#dayLabel').textContent=`Day ${c.day} · ${hourLabel(c.hour,c.minute)}`;const advanced=world.meta?.lastAdvancedAt?new Date(world.meta.lastAdvancedAt).getTime():Date.now(),period=(world.meta?.heartbeatMinutes||5)*60000,remaining=Math.max(0,period-(Date.now()-advanced)),mins=Math.floor(remaining/60000),secs=Math.floor((remaining%60000)/1000);$('#heartbeatLabel').textContent=remaining<=0?`Canonical heartbeat due · ${world.meta?.pacing||'live'}`:`Next heartbeat ~${mins}:${String(secs).padStart(2,'0')} · ${world.meta?.pacing||'live'}`;renderEnvironment()}

document.querySelectorAll('.camera-btn').forEach(btn=>btn.addEventListener('click',()=>{cameraMode=btn.dataset.camera;updateCameraButtons();animateWorld()}));
$('#memoryMara').addEventListener('click',()=>{selectedMemoryAgent='agent-mara';renderMemories()});$('#memoryIvo').addEventListener('click',()=>{selectedMemoryAgent='agent-ivo';renderMemories()});
updateCameraButtons();loadCanonical();setInterval(loadCanonical,15000);setInterval(updateProjectedClock,1000);setInterval(animateWorld,180);