import {createWorld,tick} from "./engine.js";
const STORAGE="chatgptfarm.world.v01",$=s=>document.querySelector(s);let world=load();
function load(){try{const saved=localStorage.getItem(STORAGE);return saved?JSON.parse(saved):createWorld()}catch{return createWorld()}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(world));$("#saveState").textContent="● SAVED LOCALLY"}
const hour=h=>String(h).padStart(2,"0")+":00";
function needRow(name,value){const cls=value<32?"danger":value<52?"warning":"";return `<div class="need ${cls}"><label><span>${name.toUpperCase()}</span><b>${Math.round(value)}%</b></label><div class="need-track"><i style="width:${value}%"></i></div></div>`}
function render(){
$("#dayLabel").textContent=`Day ${world.day} · ${hour(world.hour)}`;$("#weatherLabel").textContent=`${world.temperature}°F · ${world.weather[0].toUpperCase()+world.weather.slice(1)}`;$("#currentAction").textContent=world.agent.currentAction;
$("#needs").innerHTML=["hydration","hunger","energy","warmth"].map(k=>needRow(k,world.agent.needs[k])).join("");
const inv=Object.entries(world.agent.inventory).filter(([,v])=>v>0);$("#inventory").innerHTML=inv.length?inv.map(([k,v])=>`<span class="inv">${k.replace(/([A-Z])/g," $1")} ×${v}</span>`).join(""):`<span class="empty">nothing carried</span>`;
$("#memoryCount").textContent=world.agent.memories.length;$("#memories").innerHTML=world.agent.memories.length?world.agent.memories.slice(0,12).map(m=>`<article class="memory"><b>${m.id}</b><p>${m.text}</p><footer><span>${m.source}</span><span class="confidence">${Math.round(m.confidence*100)}% confidence</span></footer></article>`).join(""):`<div class="dna-empty">Mara has not formed a persistent memory yet.</div>`;
$("#eventCount").textContent=`${world.history.length} event${world.history.length===1?"":"s"}`;$("#timeline").innerHTML=world.history.length?world.history.slice(0,28).map(e=>`<article class="event"><time>D${e.day} · ${hour(e.hour)}</time><div><b class="${e.type==="learn"?"learn":""}">${e.title}</b><p>${e.detail}</p></div></article>`).join(""):`<div class="dna-empty">The world has no history yet.</div>`;
$("#shelter").classList.toggle("hidden",!world.structures.shelter);$("#fire").classList.toggle("hidden",!world.structures.fire);
const pos={creek:["48%","19%"],berries:["29%","31%"],log:["59%","29%"],camp:["64%","34%"],meadow:["43%","31%"],edge:["78%","42%"]}[world.agent.position]||["43%","31%"];
$("#agentSprite").style.left=pos[0];$("#agentSprite").style.bottom=pos[1];document.querySelector(".world").style.filter=world.hour<6||world.hour>20?"brightness(.58) saturate(.75)":world.weather==="rain"?"brightness(.82) saturate(.75)":"";
$("#worldCaption").textContent=world.history[0]?.detail||"Mara wakes beside the creek with no shelter and no stored food.";
const dna=world.dna[0];if(dna){$("#dnaEmpty").classList.add("hidden");$("#dnaInspector").classList.remove("hidden");$("#dnaAction").textContent=dna.action_label;$("#dnaId").textContent=dna.decision_id;const fs=[...dna.factors].sort((a,b)=>Math.abs(b[1])-Math.abs(a[1])),max=Math.max(1,...fs.map(x=>Math.abs(x[1])));$("#dnaFactors").innerHTML=fs.map(([name,v])=>`<div class="factor"><div class="factor-head"><span>${name}</span><b>${v>=0?"+":""}${(+v).toFixed(1)}</b></div><div class="factor-track"><i style="width:${Math.abs(v)/max*100}%"></i></div></div>`).join("")||`<small>No strong factors recorded.</small>`;const cfs=dna.memory_counterfactuals.filter(x=>x.action_changed||Math.abs(x.score_delta)>.01).slice(0,5);$("#counterfactuals").innerHTML=cfs.length?cfs.map(c=>`<div class="cf"><code>− ${c.removed_memory}</code><span>${c.original_action} → <b class="${c.action_changed?"flip":""}">${c.counterfactual_action}</b></span></div>`).join(""):`<div class="cf"><span>No stored memory was pivotal to this decision.</span></div>`}
save()}
async function run(hours,delay=180){$("#runDay").disabled=true;$("#stepHour").disabled=true;for(let i=0;i<hours;i++){tick(world);render();await new Promise(r=>setTimeout(r,delay))}$("#runDay").disabled=false;$("#stepHour").disabled=false}
$("#stepHour").addEventListener("click",()=>run(1,120));$("#runDay").addEventListener("click",()=>run(24,95));$("#resetWorld").addEventListener("click",()=>{if(confirm("Erase this world's entire history and start again?")){world=createWorld();localStorage.removeItem(STORAGE);render();$("#dnaInspector").classList.add("hidden");$("#dnaEmpty").classList.remove("hidden")}});render();