(()=>{
'use strict';
const RAW='https://raw.githubusercontent.com/kyle8824/chatgptfarm/main/world/state.json';
const WORLD_UNITS=100,PX=22,WORLD_PX=WORLD_UNITS*PX,MIN_ZOOM=.38,MAX_ZOOM=2.8;
const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const wp=p=>({x:(p?.x??50)*PX,y:(100-(p?.y??50))*PX});
const colors={ground:0x56694c,meadow:0x6f8358,meadowWet:0x586f50,forest:0x304a38,forest2:0x3c5a40,wetland:0x496a59,water:0x69aabd,waterDark:0x447f94,bank:0x72765a,mud:0x625a43,wood:0x785438,woodWet:0x493b31,woodDark:0x493327,leaf:0x315e37,leafDry:0x4c6540,berry:0xc84f5b,rock:0x818a82,rockDark:0x555f58,clay:0xaa714f,reed:0x758d58,fire:0xf39b45,fire2:0xffd46c,mara:0x6f9a78,ivo:0x787ba6,skinA:0xc89c7c,skinB:0xb88a70,shadow:0x08100b};
let app,root,terrainLayer,objectLayer,artifactLayer,agentLayer,fxWorld,screenFx,current=null,lastTick=null;
let camera={x:WORLD_PX*.55,y:WORLD_PX*.64,scale:1.05,mode:'auto',manualUntil:0,vx:0,vy:0};
const agents=new Map(),selectables=new Map(),hoverLabels=[],waterGlints=[];
const pointers=new Map();let gesture=null,lastTap={time:0,x:0,y:0};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function hash(s){let h=2166136261;for(let i=0;i<String(s).length;i++){h^=String(s).charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=hash(seed)||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function mix(a,b,t){const ar=(a>>16)&255,ag=(a>>8)&255,ab=a&255,br=(b>>16)&255,bg=(b>>8)&255,bb=b&255;return((Math.round(ar+(br-ar)*t)<<16)|(Math.round(ag+(bg-ag)*t)<<8)|Math.round(ab+(bb-ab)*t))>>>0}
function shade(c,f){return mix(c,f>=0?0xffffff:0x000000,Math.min(1,Math.abs(f)))}
function screenPoint(e){const r=app.view.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function screenToWorld(s,scale=camera.scale){return{x:(s.x-app.screen.width/2)/scale+camera.x,y:(s.y-app.screen.height/2)/scale+camera.y}}
function dist2(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}

async function init(){
 const host=$('#worldViewport');
 app=new PIXI.Application({resizeTo:host,backgroundColor:0x111a12,antialias:true,resolution:Math.min(devicePixelRatio||1,2),autoDensity:true});
 host.appendChild(app.view);app.stage.sortableChildren=true;
 root=new PIXI.Container();root.sortableChildren=true;app.stage.addChild(root);
 terrainLayer=new PIXI.Container();objectLayer=new PIXI.Container();artifactLayer=new PIXI.Container();agentLayer=new PIXI.Container();fxWorld=new PIXI.Container();
 terrainLayer.zIndex=0;objectLayer.zIndex=20;artifactLayer.zIndex=30;agentLayer.zIndex=40;fxWorld.zIndex=50;root.addChild(terrainLayer,objectLayer,artifactLayer,agentLayer,fxWorld);
 screenFx=new PIXI.Container();screenFx.zIndex=100;app.stage.addChild(screenFx);
 wireCamera();wireUI();app.ticker.add(tick);
 await loadWorld(true);setInterval(()=>loadWorld(false),12000);
 window.addEventListener('resize',()=>{drawScreenFx();if(camera.mode!=='free')frameActivity(false);else updateCamera(true)});
}
async function loadWorld(first){let w=null;for(const u of [`${RAW}?v=${Date.now()}`,`./world/state.json?v=${Date.now()}`]){try{const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(String(r.status));w=await r.json();break}catch(e){console.warn('world source failed',u,e)}}if(!w?.worldModel)return;const changed=lastTick!==w.meta?.tickNumber;current=w;lastTick=w.meta?.tickNumber;if(changed||first){renderStatic();renderUI();drawMiniMap();renderAgents();if(first)frameActivity(true)}drawScreenFx();$('#loading')?.classList.add('hidden')}

function zoneMoisture(type){const z=current?.worldModel?.fields?.soilMoisture?.zones||{};if(type==='forest')return((z.forest??.45)+(z.log??.4))/2;if(type==='wetland')return z.reeds??.9;return z.meadow??z.camp??.35}
function terrainInfluence(t,x,y){const p=wp(t.center),r=((t.radiusM||20)/2)*PX,d=Math.hypot(x-p.x,y-p.y);return clamp(1-d/r,0,1)}
function biomeAt(x,y){let best={type:'meadow',score:.02,terrain:null};for(const t of current.worldModel?.terrain||[]){const s=terrainInfluence(t,x,y);if(s>best.score)best={type:t.type,score:s,terrain:t}}return best}
function terrainColor(type,moist,jitter){let c=type==='forest'?colors.forest:type==='wetland'?colors.wetland:colors.meadow;if(moist>.65)c=mix(c,colors.meadowWet,clamp((moist-.65)*.7,0,.2));return shade(c,jitter)}
function renderStatic(){terrainLayer.removeChildren().forEach(d=>d.destroy({children:true}));objectLayer.removeChildren().forEach(d=>d.destroy({children:true}));artifactLayer.removeChildren().forEach(d=>d.destroy({children:true}));selectables.clear();hoverLabels.length=0;waterGlints.length=0;drawTerrain();const objects=(current.worldModel?.objects||[]).filter(o=>o.state?.active!==false);objects.filter(o=>!o.parentId).forEach(drawObject);objects.filter(o=>o.parentId).forEach(drawComponent);(current.artifacts||[]).filter(a=>a.status==='active'||a.status==='remnant').forEach(drawArtifact)}
function drawTerrain(){
 const tile=70,R=rng(`terrain-${current.day}-${current.worldModel.version}`),g=new PIXI.Graphics();
 for(let y=0;y<WORLD_PX;y+=tile)for(let x=0;x<WORLD_PX;x+=tile){const cx=x+tile/2,cy=y+tile/2,b=biomeAt(cx,cy),m=zoneMoisture(b.type),j=(R()-.5)*.08;g.beginFill(terrainColor(b.type,m,j),1).drawRect(x,y,tile+1,tile+1).endFill();if(m>.72){g.beginFill(colors.mud,.10).drawEllipse(cx+(R()-.5)*25,cy+(R()-.5)*22,10+R()*20,4+R()*8).endFill()}}
 terrainLayer.addChild(g);drawGroundTexture();drawCreek();drawAggregateVegetation();
 const edge=new PIXI.Graphics();edge.lineStyle(4,0x132219,.35).drawRect(3,3,WORLD_PX-6,WORLD_PX-6);terrainLayer.addChild(edge)
}
function drawGroundTexture(){const R=rng('ground-texture'),g=new PIXI.Graphics();for(let i=0;i<900;i++){const x=R()*WORLD_PX,y=R()*WORLD_PX,b=biomeAt(x,y);if(b.type==='meadow'){g.lineStyle(1,0x93a56c,.13+R()*.12).moveTo(x,y).lineTo(x+(R()-.5)*4,y-4-R()*5)}else if(b.type==='forest'&&R()>.4){g.beginFill(0x1f3427,.15).drawEllipse(x,y,2+R()*5,1+R()*2).endFill()}else if(b.type==='wetland'&&R()>.25){g.lineStyle(1.5,0x83965f,.25).moveTo(x,y+4).lineTo(x+(R()-.5)*3,y-8-R()*9)}}terrainLayer.addChild(g)}
function drawAggregateVegetation(){for(const t of current.worldModel?.terrain||[]){const p=wp(t.center),r=((t.radiusM||20)/2)*PX,R=rng(t.id);if(t.type==='forest'){for(let i=0;i<78;i++){const a=R()*Math.PI*2,rr=Math.sqrt(R())*r*.98,x=p.x+Math.cos(a)*rr,y=p.y+Math.sin(a)*rr,sz=10+R()*15;const c=new PIXI.Graphics();c.beginFill(colors.shadow,.18).drawEllipse(x+4,y+7,sz*.9,sz*.42).endFill();c.beginFill(i%3?colors.forest:colors.forest2,.95).drawCircle(x,y,sz).endFill();c.beginFill(0x4d6a4a,.55).drawCircle(x-5,y-5,sz*.55).endFill();terrainLayer.addChild(c)}}else if(t.type==='wetland'){const g=new PIXI.Graphics();for(let i=0;i<105;i++){const a=R()*Math.PI*2,rr=Math.sqrt(R())*r,x=p.x+Math.cos(a)*rr,y=p.y+Math.sin(a)*rr,h=10+R()*22;g.lineStyle(1.5,colors.reed,.35).moveTo(x,y+4).lineTo(x+(R()-.5)*3,y-h)}terrainLayer.addChild(g)}}}
function drawCreek(){const creek=(current.worldModel?.objects||[]).find(o=>o.type==='creek_segment');if(!creek?.geometry?.points)return;const pts=creek.geometry.points.map(([x,y])=>wp({x,y})),depth=current.worldModel?.fields?.waterDepth?.objects?.[creek.id]??.42,width=36+depth*18;const bank=new PIXI.Graphics();bank.lineStyle(width+20,mix(colors.bank,colors.mud,depth*.32),.9).moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(p=>bank.lineTo(p.x,p.y));terrainLayer.addChild(bank);const water=new PIXI.Graphics();water.lineStyle(width,mix(colors.water,colors.waterDark,depth*.45),.96).moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(p=>water.lineTo(p.x,p.y));terrainLayer.addChild(water);const hi=new PIXI.Graphics();hi.lineStyle(3,0xccebef,.26).moveTo(pts[0].x,pts[0].y-4);pts.slice(1).forEach(p=>hi.lineTo(p.x,p.y-4));terrainLayer.addChild(hi);const R=rng(creek.id);for(let i=0;i<24;i++){const seg=i%(pts.length-1),q=R(),a=pts[seg],b=pts[seg+1],x=a.x+(b.x-a.x)*q,y=a.y+(b.y-a.y)*q+(R()-.5)*width*.5,s=2+R()*5;const rock=new PIXI.Graphics();rock.beginFill(R()>.5?colors.rock:colors.rockDark,.8).drawEllipse(x,y,s,s*.65).endFill();terrainLayer.addChild(rock)}for(let i=0;i<10;i++){const gl=new PIXI.Graphics();gl.lineStyle(2,0xe0f5f4,.2).moveTo(-9,0).lineTo(9,0);gl._seed=i;gl._pts=pts;terrainLayer.addChild(gl);waterGlints.push(gl)}}

function makeSelectable(display,data,kind='object'){display.eventMode='static';display.cursor='pointer';display.on('pointertap',e=>{e.stopPropagation();openInspector(data,kind)});selectables.set(data.id,display);return display}
function labelFor(c,text,y=34){const t=new PIXI.Text(text,{fontFamily:'Arial',fontSize:12,fontWeight:'600',fill:0xf0f5ed,stroke:0x09110b,strokeThickness:4});t.anchor.set(.5);t.y=y;t.alpha=0;c.addChild(t);hoverLabels.push(t);c.on('pointerover',()=>t._hover=true);c.on('pointerout',()=>t._hover=false);return t}
function wetWoodColor(o){const m=Number(o.material?.moisturePct??28);return mix(colors.wood,colors.woodWet,clamp((m-12)/55,0,.72))}
function drawObject(o){const p=wp(o.position),c=new PIXI.Container();c.position.set(p.x,p.y);c.zIndex=p.y;const R=rng(o.id),g=new PIXI.Graphics();
 if(o.type==='camp_area'){for(let i=0;i<25;i++){const a=R()*Math.PI*2,rr=Math.sqrt(R())*78,x=Math.cos(a)*rr,y=Math.sin(a)*rr*.62;g.beginFill(colors.mud,.055+R()*.06).drawEllipse(x,y,8+R()*20,3+R()*8).endFill()}}
 else if(o.type==='berry_patch'){const fruit=Math.max(0,o.state?.ediblePortions||0),count=o.state?.exhausted?4:10;for(let i=0;i<count;i++){const x=(R()-.5)*92,y=(R()-.5)*54,sz=(o.state?.exhausted?7:10)+R()*8;g.beginFill(o.state?.exhausted?colors.leafDry:colors.leaf,.96).drawCircle(x,y,sz).endFill();if(i<fruit*2){g.beginFill(colors.berry,.95).drawCircle(x+(R()-.5)*10,y+(R()-.5)*9,2.8).endFill()}}}
 else if(o.type==='fallen_tree'){const len=(o.geometry?.lengthM||4.8)*26,wc=wetWoodColor(o);g.lineStyle(22,colors.woodDark,.98).moveTo(-len/2,0).lineTo(len/2,0);g.lineStyle(15,wc,.98).moveTo(-len/2,0).lineTo(len/2,0);g.lineStyle(2,shade(wc,.18),.42).moveTo(-len/2+8,-3).lineTo(len/2-8,-3);if(!o.resolution?.componentsInstantiated)for(let i=0;i<4;i++){const x=-len*.34+i*len*.22,dir=i%2?-1:1;g.lineStyle(7,wc,.94).moveTo(x,0).lineTo(x+dir*(22+R()*24),dir*(18+R()*21))}c.rotation=((o.geometry?.orientationDeg||0)-90)*Math.PI/180}
 else if(o.type==='stone_field'){for(let i=0;i<18;i++){const a=R()*Math.PI*2,rr=Math.sqrt(R())*72,x=Math.cos(a)*rr,y=Math.sin(a)*rr*.55,sz=5+R()*9;g.beginFill(i%2?colors.rock:colors.rockDark,.97).drawEllipse(x,y,sz,sz*.7).endFill();g.lineStyle(1,0xb2bbb4,.18).drawEllipse(x-1,y-2,sz*.65,sz*.35)}}
 else if(o.type==='clay_bank'){g.beginFill(mix(colors.clay,colors.mud,.18),.85).drawEllipse(0,0,76,39).endFill();for(let i=0;i<13;i++)g.beginFill(i%2?0xc28a66:0x79513d,.18+R()*.12).drawEllipse((R()-.5)*110,(R()-.5)*48,5+R()*12,2+R()*5).endFill()}
 else if(o.type==='reed_marsh'){for(let i=0;i<48;i++){const x=(R()-.5)*108,y=(R()-.5)*82,h=20+R()*38;g.lineStyle(2,colors.reed,.9).moveTo(x,y+9).lineTo(x+(R()-.5)*5,y-h);if(i%3===0)g.beginFill(0x81643d,.82).drawEllipse(x,y-h,2,6).endFill()}}
 else if(o.type==='frontier'){for(let i=0;i<10;i++)g.beginFill(0xd1d8d0,.025+R()*.025).drawCircle((R()-.5)*170,(R()-.5)*190,45+R()*80).endFill()}
 else if(o.type==='branch_shelter'){g.beginFill(colors.shadow,.18).drawEllipse(5,24,54,18).endFill();g.beginFill(0x5a402c,.96).moveTo(-48,26).lineTo(0,-48).lineTo(51,26).lineTo(34,26).lineTo(0,-25).lineTo(-31,26).closePath().endFill();g.lineStyle(4,0x98714a,.9).moveTo(-42,23).lineTo(0,-44).lineTo(45,23);for(let i=-25;i<=25;i+=10)g.lineStyle(2,0x76553a,.65).moveTo(i,13).lineTo(i+20,-18)}
 else if(o.type==='camp_fire'){const glow=new PIXI.Graphics();glow.beginFill(colors.fire2,.15).drawCircle(0,0,70).endFill();glow.name='fireGlow';c.addChild(glow);for(let i=0;i<8;i++){const a=i/8*Math.PI*2;g.beginFill(colors.rockDark,.95).drawCircle(Math.cos(a)*20,Math.sin(a)*12,5).endFill()}g.lineStyle(6,colors.woodDark,.98).moveTo(-16,7).lineTo(16,-5).moveTo(-16,-5).lineTo(16,7);const f=new PIXI.Graphics();f.beginFill(colors.fire,.96).drawPolygon([-11,12,0,-27,11,12]).endFill();f.beginFill(colors.fire2,.94).drawPolygon([-6,10,0,-15,6,10]).endFill();f.name='flame';c.addChild(f)}
 else if(o.type==='drying_rack'){g.lineStyle(6,wetWoodColor(o),.96).moveTo(-34,22).lineTo(-23,-24).moveTo(34,22).lineTo(23,-24).moveTo(-29,-10).lineTo(29,-10);for(let i=-18;i<=18;i+=9)g.lineStyle(2,0xa88c62,.9).moveTo(i,-10).lineTo(i,15)}
 else if(o.type==='animal_tracks'){const clarity=clamp(o.state?.clarity??.7,.1,1);g.alpha=.35+.6*clarity;for(let i=0;i<8;i++){const x=i*11-38,y=(i%2?5:-5)+i*1.8;g.beginFill(0x241b15,.68).drawEllipse(x,y,4,6).endFill();g.beginFill(0x241b15,.55).drawCircle(x-4,y-4,2).drawCircle(x,y-6,2).drawCircle(x+4,y-4,2).endFill()}}
 else return;c.addChildAt(g,0);makeSelectable(c,o);if(!['camp_area','frontier'].includes(o.type))labelFor(c,o.label,o.type==='fallen_tree'?42:38);objectLayer.addChild(c)}
function drawComponent(o){const p=wp(o.position),c=new PIXI.Container();c.position.set(p.x,p.y);c.zIndex=p.y+2;const g=new PIXI.Graphics();if(o.type==='branch'){const wc=wetWoodColor(o);g.lineStyle(6,wc,.98).moveTo(-17,0).lineTo(17,0);g.lineStyle(1,shade(wc,.2),.35).moveTo(-15,-2).lineTo(13,-2)}else if(o.type==='rock'){g.beginFill(colors.rock,.97).drawEllipse(0,0,9,6).endFill()}else if(o.type==='berry_bush'){g.beginFill(colors.leaf,.97).drawCircle(0,0,13).endFill()}else if(o.type==='clay_deposit'){g.beginFill(colors.clay,.93).drawEllipse(0,0,14,8).endFill()}else if(o.type==='reed_stand'){for(let i=-10;i<=10;i+=4)g.lineStyle(2,colors.reed,.93).moveTo(i,9).lineTo(i+(i%3),-22-Math.abs(i))}else return;c.addChild(g);makeSelectable(c,o);labelFor(c,o.label,25);objectLayer.addChild(c)}
function drawArtifact(a){const p=wp(a.coordinates||{x:50,y:50}),c=new PIXI.Container();c.position.set(p.x+12,p.y-10);c.zIndex=p.y+6;const g=new PIXI.Graphics(),type=a.type||'';if(type.includes('ClayVessel')){g.lineStyle(2,0xe0b08a,.9).beginFill(0x9a694c,.96).drawEllipse(0,3,10,13).endFill().moveTo(-7,-5).lineTo(7,-5)}else if(type.includes('sharpStone'))g.beginFill(0xaab2ac,.98).drawPolygon([-11,8,0,-11,10,7]).endFill();else if(type.includes('Pole'))g.lineStyle(5,colors.wood,.98).moveTo(-18,9).lineTo(18,-9);else if(type.includes('cordage'))g.lineStyle(3,0xb9a06a,.92).drawCircle(0,0,10);else g.beginFill(0xd5c58c,.92).drawCircle(0,0,6).endFill();c.addChild(g);makeSelectable(c,a,'artifact');artifactLayer.addChild(c)}

function heartbeatProgress(){if(!current)return 1;const t=current.meta?.lastAdvancedAt?new Date(current.meta.lastAdvancedAt).getTime():Date.now(),period=(current.meta?.heartbeatMinutes||5)*60000;return clamp((Date.now()-t)/period,0,1)}
function phaseState(a){const plan=a.activeAction,p=heartbeatProgress();if(!plan?.phases?.length)return{phase:'idle',label:'Between actions',x:a.coordinates?.x??50,y:a.coordinates?.y??50,from:a.coordinates,to:a.coordinates};const phase=plan.phases.find(x=>p>=x.start&&p<x.end)||plan.phases.at(-1),from=plan.from||a.coordinates,to=plan.to||a.coordinates;let x=to.x,y=to.y;if(plan.moving){const travel=plan.phases.find(x=>x.id==='travel');if(travel&&p<travel.start){x=from.x;y=from.y}else if(travel&&p<travel.end){const q=clamp((p-travel.start)/(travel.end-travel.start),0,1);x=from.x+(to.x-from.x)*q;y=from.y+(to.y-from.y)*q}}return{phase:phase.id,label:phase.label,x,y,from,to}}
function createAgentSprite(a,index){const c=new PIXI.Container();c.zIndex=999;c.scale.set(1.32);const shadow=new PIXI.Graphics();shadow.beginFill(colors.shadow,.35).drawEllipse(0,17,18,7).endFill();const legs=new PIXI.Graphics();legs.lineStyle(5,0x262e29,1).moveTo(-6,8).lineTo(-8,21).moveTo(6,8).lineTo(8,21);legs.name='legs';const body=new PIXI.Graphics();body.beginFill(index?colors.ivo:colors.mara).drawRoundedRect(-11,-9,22,28,7).endFill();body.name='body';const head=new PIXI.Graphics();head.beginFill(index?colors.skinB:colors.skinA).drawCircle(0,-18,9).endFill();head.name='head';const hair=new PIXI.Graphics();hair.beginFill(index?0x2c231f:0x5a3427,.96).drawEllipse(0,-22,9,5).endFill();hair.name='hair';const armL=new PIXI.Graphics(),armR=new PIXI.Graphics();armL.lineStyle(4,index?0x5b5e86:0x587761,1).moveTo(-8,-1).lineTo(-15,9);armR.lineStyle(4,index?0x5b5e86:0x587761,1).moveTo(8,-1).lineTo(15,9);armL.name='armL';armR.name='armR';const name=new PIXI.Text(a.name,{fontFamily:'Arial',fontSize:13,fontWeight:'700',fill:0xf2f6ef,stroke:0x07100a,strokeThickness:4});name.anchor.set(.5);name.y=-39;const action=new PIXI.Text('',{fontFamily:'Arial',fontSize:9,fill:0xc4d1c3,stroke:0x07100a,strokeThickness:3});action.anchor.set(.5);action.y=34;const talk=new PIXI.Graphics();talk.beginFill(0xf2f6ef,.88).drawRoundedRect(15,-39,24,14,7).endFill().beginFill(0xf2f6ef,.88).drawPolygon([18,-26,14,-20,25,-26]).endFill();for(let i=0;i<3;i++)talk.beginFill(0x405344,.8).drawCircle(22+i*6,-32,1.5).endFill();talk.visible=false;talk.name='talk';c.addChild(shadow,legs,body,head,hair,armL,armR,name,action,talk);c.eventMode='static';c.cursor='pointer';c.on('pointertap',e=>{e.stopPropagation();openInspector(a,'agent')});c._parts={legs,body,head,hair,armL,armR,name,action,talk};agentLayer.addChild(c);agents.set(a.id,c);return c}
function renderAgents(){if(!current)return;current.agents.forEach((a,i)=>{let c=agents.get(a.id);if(!c)c=createAgentSprite(a,i);c._data=a})}
function tick(delta){if(!current)return;const t=performance.now()/1000;current.agents.forEach((a,i)=>{const c=agents.get(a.id);if(!c)return;const s=phaseState(a),p=wp(s),parts=c._parts;c.position.set(p.x,p.y);c.zIndex=p.y+20;const intent=a.currentAction||a.mind?.intent||'',isTalk=/talk|speak|teach/i.test(intent),isRest=/rest|sleep/i.test(intent);parts.talk.visible=isTalk&&s.phase!=='travel';parts.action.text=s.phase==='travel'?'walking':isTalk?'talking':isRest?'resting':s.phase==='interact'?'working':'';const fs=wp(s.from||s),ts=wp(s.to||s);if(s.phase==='travel'&&Math.hypot(ts.x-fs.x,ts.y-fs.y)>2)c.rotation=Math.atan2(ts.y-fs.y,ts.x-fs.x)+Math.PI/2;else c.rotation=0;if(s.phase==='travel'){parts.legs.rotation=Math.sin(t*10+i)*.22;parts.body.y=Math.sin(t*10+i)*1.4;parts.armL.rotation=Math.sin(t*10+i)*.18;parts.armR.rotation=-Math.sin(t*10+i)*.18}else if(isRest){parts.legs.rotation=.45;parts.body.rotation=-.2;parts.body.y=8;parts.head.y=5;parts.armL.rotation=.45;parts.armR.rotation=.3}else if(s.phase==='interact'){parts.armR.rotation=Math.sin(t*7+i)*.45;parts.armL.rotation=-.15;parts.body.y=Math.sin(t*5+i)*.8;parts.legs.rotation=0}else{parts.legs.rotation=0;parts.body.rotation=0;parts.body.y=Math.sin(t*2+i)*.45;parts.head.y=0;parts.armL.rotation=parts.armR.rotation=0}});animateFire(t);animateWater(t);animateRain(delta);animateCamera(delta);updateLabels()}
function animateFire(t){for(const c of objectLayer.children){const f=c.getChildByName?.('flame');if(f){f.scale.y=.84+Math.sin(t*8)*.16;f.rotation=Math.sin(t*5)*.07}const glow=c.getChildByName?.('fireGlow');if(glow)glow.alpha=.1+Math.sin(t*3)*.025}}
function animateWater(t){waterGlints.forEach((g,i)=>{const pts=g._pts;if(!pts?.length)return;const q=(t*.045+i*.113)%1,total=pts.length-1,u=q*total,idx=Math.min(total-1,Math.floor(u)),f=u-idx,a=pts[idx],b=pts[idx+1];g.position.set(a.x+(b.x-a.x)*f,a.y+(b.y-a.y)*f);g.alpha=.08+.16*(.5+.5*Math.sin(t*2+i))})}
let rainDrops=[];
function drawScreenFx(){if(!app)return;screenFx.removeChildren().forEach(d=>d.destroy({children:true}));rainDrops=[];const f=current?.worldModel?.fields||{},precip=f.precipitation?.global||0;if(precip>0){for(let i=0;i<Math.round(24+precip*38);i++){const g=new PIXI.Graphics();g.lineStyle(1,0xd7eef0,.10+Math.random()*.13).moveTo(0,0).lineTo(-3,8+Math.random()*7);g.x=Math.random()*app.screen.width;g.y=Math.random()*app.screen.height;g._speed=4+Math.random()*6;screenFx.addChild(g);rainDrops.push(g)}}const light=f.light?.global??.5,darkness=clamp(.34-light*.34,0,.31);if(darkness>.015){const g=new PIXI.Graphics();g.beginFill(0x07101a,darkness).drawRect(0,0,app.screen.width,app.screen.height).endFill();g.eventMode='none';screenFx.addChild(g)}if(current?.weather==='cloudy'){const g=new PIXI.Graphics();g.beginFill(0xa9bac0,.035).drawRect(0,0,app.screen.width,app.screen.height).endFill();screenFx.addChild(g)}}
function animateRain(delta){for(const d of rainDrops){d.y+=d._speed*delta;d.x-=d._speed*.2*delta;if(d.y>app.screen.height+20){d.y=-20;d.x=Math.random()*app.screen.width}if(d.x<-20)d.x=app.screen.width+20}}
function updateLabels(){const a=clamp((camera.scale-1.05)/.65,0,.9);hoverLabels.forEach(l=>l.alpha=l._hover?1:a*.5)}

function beginManual(){camera.mode='free';camera.manualUntil=Date.now()+30000;syncButtons()}
function zoomAt(screen,factor){const old=camera.scale,next=clamp(old*factor,MIN_ZOOM,MAX_ZOOM),w=screenToWorld(screen,old);camera.scale=next;camera.x=w.x-(screen.x-app.screen.width/2)/next;camera.y=w.y-(screen.y-app.screen.height/2)/next;beginManual();updateCamera(true)}
function wireCamera(){const canvas=app.view;canvas.style.touchAction='none';
 canvas.addEventListener('pointerdown',e=>{const p=screenPoint(e);pointers.set(e.pointerId,p);canvas.setPointerCapture?.(e.pointerId);$('#worldViewport').classList.add('dragging');camera.vx=camera.vy=0;if(pointers.size===1){gesture={type:'drag',id:e.pointerId,start:p,last:p,cx:camera.x,cy:camera.y,time:performance.now(),moved:false,lastTime:performance.now()}}else if(pointers.size===2){const ps=[...pointers.values()],mid={x:(ps[0].x+ps[1].x)/2,y:(ps[0].y+ps[1].y)/2};gesture={type:'pinch',startDist:dist2(ps[0],ps[1]),startScale:camera.scale,anchor:screenToWorld(mid),lastMid:mid};beginManual()}},{passive:false});
 canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;e.preventDefault();const p=screenPoint(e);pointers.set(e.pointerId,p);if(pointers.size>=2){const ps=[...pointers.values()].slice(0,2),mid={x:(ps[0].x+ps[1].x)/2,y:(ps[0].y+ps[1].y)/2},d=dist2(ps[0],ps[1]);if(gesture?.type!=='pinch'){gesture={type:'pinch',startDist:d,startScale:camera.scale,anchor:screenToWorld(mid),lastMid:mid}}const next=clamp(gesture.startScale*(d/Math.max(20,gesture.startDist)),MIN_ZOOM,MAX_ZOOM);camera.scale=next;camera.x=gesture.anchor.x-(mid.x-app.screen.width/2)/next;camera.y=gesture.anchor.y-(mid.y-app.screen.height/2)/next;gesture.lastMid=mid;beginManual();updateCamera(true);return}if(gesture?.type==='drag'&&gesture.id===e.pointerId){const dx=p.x-gesture.start.x,dy=p.y-gesture.start.y;if(Math.abs(dx)+Math.abs(dy)>5)gesture.moved=true;if(gesture.moved){const now=performance.now(),dt=Math.max(8,now-gesture.lastTime),ldx=p.x-gesture.last.x,ldy=p.y-gesture.last.y;camera.x=gesture.cx-dx/camera.scale;camera.y=gesture.cy-dy/camera.scale;camera.vx=(-ldx/camera.scale)/(dt/16.67);camera.vy=(-ldy/camera.scale)/(dt/16.67);gesture.last=p;gesture.lastTime=now;beginManual();updateCamera(true)}}},{passive:false});
 const end=e=>{const p=pointers.get(e.pointerId)||screenPoint(e),was=gesture;pointers.delete(e.pointerId);if(!pointers.size){$('#worldViewport').classList.remove('dragging');if(was?.type==='drag'&&!was.moved){const now=performance.now();if(now-lastTap.time<300&&Math.hypot(p.x-lastTap.x,p.y-lastTap.y)<28){zoomAt(p,1.55);lastTap.time=0}else lastTap={time:now,x:p.x,y:p.y}}gesture=null}else if(pointers.size===1){const [id,q]=[...pointers.entries()][0];gesture={type:'drag',id,start:q,last:q,cx:camera.x,cy:camera.y,time:performance.now(),moved:false,lastTime:performance.now()}}};canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);
 canvas.addEventListener('wheel',e=>{e.preventDefault();zoomAt(screenPoint(e),Math.exp(-e.deltaY*.001))},{passive:false})}
function animateCamera(delta){if(camera.mode==='free'&&!pointers.size&&(Math.abs(camera.vx)+Math.abs(camera.vy)>.02)){camera.x+=camera.vx*delta;camera.y+=camera.vy*delta;camera.vx*=Math.pow(.9,delta);camera.vy*=Math.pow(.9,delta);updateCamera(true)}else updateCamera(false)}
function activityTarget(){if(!current)return{x:WORLD_PX*.55,y:WORLD_PX*.64};const top=current.liveThreads?.[0],threadAgent=top?.agentIds?.length&&current.agents.find(a=>a.id===top.agentIds[0]),a=threadAgent||current.agents.find(x=>x.activeAction?.moving)||current.agents.find(x=>x.activeAction?.physicalProposal)||current.agents[0];return a?wp(phaseState(a)):{x:WORLD_PX*.55,y:WORLD_PX*.64}}
function frameActivity(initial=false){if(!current)return;const target=activityTarget(),mobile=app.screen.width<700;camera.x=target.x;camera.y=target.y;camera.scale=mobile?1.12:1.0;camera.mode='auto';camera.manualUntil=0;camera.vx=camera.vy=0;syncButtons();updateCamera(true);if(initial)showToast('Pinch to zoom · drag to explore · tap objects to inspect')}
function fitWorld(){if(!current)return;const objs=(current.worldModel.objects||[]).filter(o=>o.state?.active!==false&&o.position&&o.type!=='frontier'),pts=objs.map(o=>wp(o.position));if(!pts.length)return;const minX=Math.min(...pts.map(p=>p.x))-170,maxX=Math.max(...pts.map(p=>p.x))+170,minY=Math.min(...pts.map(p=>p.y))-170,maxY=Math.max(...pts.map(p=>p.y))+170;camera.x=(minX+maxX)/2;camera.y=(minY+maxY)/2;camera.scale=clamp(Math.min(app.screen.width/(maxX-minX),app.screen.height/(maxY-minY))*.9,MIN_ZOOM,1.15);camera.mode='free';syncButtons();updateCamera(true)}
function focusAgent(id){const a=current?.agents?.find(a=>a.id===id);if(!a)return;camera.mode=id;camera.manualUntil=0;camera.scale=Math.max(camera.scale,app.screen.width<700?1.25:1.12);camera.vx=camera.vy=0;syncButtons();updateCamera(true)}
function updateCamera(force){if(!root||!app)return;let target={x:camera.x,y:camera.y};if(camera.mode==='auto'&&Date.now()>camera.manualUntil)target=activityTarget();else if(camera.mode.startsWith('agent-')){const a=current?.agents?.find(a=>a.id===camera.mode);if(a)target=wp(phaseState(a))}const speed=force?1:.07;camera.x+=(target.x-camera.x)*speed;camera.y+=(target.y-camera.y)*speed;camera.x=clamp(camera.x,-200,WORLD_PX+200);camera.y=clamp(camera.y,-200,WORLD_PX+200);root.scale.set(camera.scale);root.position.set(app.screen.width/2-camera.x*camera.scale,app.screen.height/2-camera.y*camera.scale)}
function wireUI(){document.querySelectorAll('[data-camera]').forEach(b=>b.addEventListener('click',()=>{const m=b.dataset.camera;if(m==='auto')frameActivity(false);else focusAgent(m)}));$('#zoomIn')?.addEventListener('click',()=>zoomAt({x:app.screen.width/2,y:app.screen.height/2},1.22));$('#zoomOut')?.addEventListener('click',()=>zoomAt({x:app.screen.width/2,y:app.screen.height/2},1/1.22));$('#fitWorld')?.addEventListener('click',()=>frameActivity(false));$('#closeInspector')?.addEventListener('click',()=>$('#inspector').classList.remove('open'));const top=document.querySelector('.threadTop'),panel=document.querySelector('.threadPanel');top?.addEventListener('click',()=>panel?.classList.toggle('expanded'))}
function syncButtons(){document.querySelectorAll('[data-camera]').forEach(b=>b.classList.toggle('active',b.dataset.camera===camera.mode))}

function renderUI(){const status=$('#worldStatus');if(status)status.innerHTML=`<strong>● OBJECT WORLD · ${esc(current.version||'?')}</strong><span>Day ${current.day} · ${String(current.hour).padStart(2,'0')}:00 · ${Math.round(current.temperature)}°F · ${esc(current.weather)}</span>`;const threads=$('#threads'),list=current.liveThreads||[];if(threads){threads.innerHTML=list.length?list.map(t=>`<article class="thread ${t.urgency>=85?'urgent':t.urgency>=60?'high':''}"><b>${esc(t.title)}</b><p>${esc(t.summary)}</p><small>${esc(t.kind)} · urgency ${t.urgency}</small></article>`).join(''):'<article class="thread"><b>Quiet stretch</b><p>No high-signal unresolved thread right now.</p></article>';$('#threadCount').textContent=`${list.length} active thread${list.length===1?'':'s'}`}updateFocusCard()}
function updateFocusCard(){if(!current)return;let a=camera.mode.startsWith('agent-')?current.agents.find(x=>x.id===camera.mode):null;if(!a){const top=current.liveThreads?.[0];a=(top?.agentIds?.length&&current.agents.find(x=>x.id===top.agentIds[0]))||current.agents[0]}if(!a)return;const s=phaseState(a),el=$('#focusCard');if(el)el.innerHTML=`<div class="focusInner"><small>${esc(s.label).toUpperCase()} · ${esc(a.position).toUpperCase()}</small><strong>${esc(a.name)} — ${esc(a.mind?.currentGoal||a.currentAction||'Responding to the world')}</strong><p>${esc(a.mind?.intent||a.currentAction||'')}</p></div>`}
function showToast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2600)}
function openInspector(data,kind){const panel=$('#inspector'),title=$('#inspectTitle'),type=$('#inspectType'),body=$('#inspectBody');if(!panel)return;type.textContent=kind==='agent'?'AUTONOMOUS AGENT':kind==='artifact'?'PERSISTENT ARTIFACT':'CANONICAL WORLD OBJECT';title.textContent=data.name||data.label||data.id;if(kind==='agent')body.innerHTML=agentInspector(data);else if(kind==='artifact')body.innerHTML=artifactInspector(data);else body.innerHTML=objectInspector(data);panel.classList.add('open')}
function flatten(obj,prefix=''){const out=[];for(const[k,v]of Object.entries(obj||{})){if(v==null)continue;const key=prefix?`${prefix}.${k}`:k;if(typeof v==='object'&&!Array.isArray(v))out.push(...flatten(v,key));else out.push([key,Array.isArray(v)?v.join(', '):String(v)])}return out}
function objectInspector(o){const physical=Object.entries(o.physical||{}).filter(([,v])=>v===true).map(([k])=>k),props=[['ID',o.id],['Type',o.type],['Zone',o.zone],['Resolution',o.resolution?.level||'—'],['Parent',o.parentId||'independent'],['Position',`${o.position?.x?.toFixed?.(1)??o.position?.x}, ${o.position?.y?.toFixed?.(1)??o.position?.y}`]],material=flatten(o.material||{}).slice(0,10),state=flatten(o.state||{}).slice(0,10);return `<div class="kv">${props.map(([k,v])=>`<span>${esc(k)}</span><b>${esc(v)}</b>`).join('')}</div><div class="pillRow">${physical.map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</div>${material.length?`<div class="kv">${material.map(([k,v])=>`<span>${esc(k)}</span><b>${esc(v)}</b>`).join('')}</div>`:''}${state.length?`<div class="kv">${state.map(([k,v])=>`<span>state.${esc(k)}</span><b>${esc(v)}</b>`).join('')}</div>`:''}<div class="historyList"><h3>OBJECT HISTORY</h3>${(o.history||[]).slice(-7).reverse().map(h=>`<div class="historyItem">D${h.day} ${String(h.hour).padStart(2,'0')}:00 · ${esc(h.detail||h.type)}</div>`).join('')||'<div class="historyItem">No recorded object-specific events yet.</div>'}</div>`}
function agentInspector(a){const n=a.needs||{};return `<div class="kv"><span>ID</span><b>${esc(a.id)}</b><span>Location</span><b>${esc(a.position)}</b><span>Hydration</span><b>${Math.round(n.hydration||0)}%</b><span>Satiety</span><b>${Math.round(n.hunger||0)}%</b><span>Energy</span><b>${Math.round(n.energy||0)}%</b><span>Warmth</span><b>${Math.round(n.warmth||0)}%</b><span>Brain</span><b>${esc(a.mind?.brainMode||'unknown')}</b><span>Goal</span><b>${esc(a.mind?.currentGoal||'—')}</b><span>Intent</span><b>${esc(a.mind?.intent||a.currentAction||'—')}</b></div><div class="pillRow">${Object.keys(a.skills||{}).map(s=>`<span class="pill">${esc(s)}</span>`).join('')}</div><div class="historyList"><h3>RECENT MEMORIES</h3>${(a.memories||[]).slice(0,6).map(m=>`<div class="historyItem">${esc(m.text)}</div>`).join('')}</div>`}
function artifactInspector(a){return `<div class="kv"><span>ID</span><b>${esc(a.id)}</b><span>Type</span><b>${esc(a.type)}</b><span>Status</span><b>${esc(a.status)}</b><span>Carrier</span><b>${esc(a.carrierId||'none')}</b><span>Position</span><b>${esc(a.position)}</b><span>Created</span><b>Day ${a.created?.day??'?'} · ${String(a.created?.hour??0).padStart(2,'0')}:00</b><span>Provenance</span><b>${esc(a.provenance||'—')}</b></div><div class="pillRow">${(a.properties||[]).map(p=>`<span class="pill">${esc(p)}</span>`).join('')}</div>`}
function drawMiniMap(){const c=$('#miniMapCanvas');if(!c||!current)return;const dpr=Math.min(devicePixelRatio||1,2),r=c.getBoundingClientRect();if(!r.width||!r.height)return;c.width=r.width*dpr;c.height=r.height*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);x.fillStyle='#18261b';x.fillRect(0,0,r.width,r.height);const sx=r.width/100,sy=r.height/100,creek=(current.worldModel.objects||[]).find(o=>o.type==='creek_segment');if(creek?.geometry?.points){x.strokeStyle='#68a9bd';x.lineWidth=3;x.beginPath();creek.geometry.points.forEach(([px,py],i)=>{const X=px*sx,Y=(100-py)*sy;i?x.lineTo(X,Y):x.moveTo(X,Y)});x.stroke()}for(const o of current.worldModel.objects||[]){if(o.state?.active===false||!o.position)continue;x.fillStyle=o.kind==='structure'?'#d2ad69':o.physical?.biological?'#75a35d':'#a1aaa2';x.beginPath();x.arc(o.position.x*sx,(100-o.position.y)*sy,2,0,Math.PI*2);x.fill()}for(const a of current.agents){x.fillStyle=a.id.endsWith('mara')?'#9bd6a9':'#a9acd9';x.beginPath();x.arc(a.coordinates.x*sx,(100-a.coordinates.y)*sy,3,0,Math.PI*2);x.fill()}}
init().catch(e=>{console.error(e);const l=$('#loading');if(l)l.innerHTML=`<div class="loadingBox"><div class="loadingMark">!</div><strong>Renderer failed to start</strong><p>${esc(e.message||e)}</p></div>`});
})();