(()=>{
'use strict';
const RAW='https://raw.githubusercontent.com/kyle8824/chatgptfarm/main/world/state.json';
const U=100,PX=26,W=U*PX,MIN=.46,MAX=3.4;
const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const wp=p=>({x:(p?.x??50)*PX,y:(100-(p?.y??50))*PX});
const C={ground:0x6f815c,ground2:0x7d8e68,forestGround:0x496149,forestDark:0x263c2e,forestLeaf:0x496d48,forestHi:0x678260,wet:0x5f7865,water:0x6eb6c9,waterDark:0x477f95,bank:0x857963,mud:0x6d6048,wood:0x8b6240,woodWet:0x594738,woodDark:0x493226,leaf:0x3e713f,leafDry:0x677053,berry:0xd5525e,rock:0x9aa29c,rock2:0x66716a,clay:0xb87a55,reed:0x8ba45f,fire:0xf09a42,fire2:0xffd36a,mara:0x75a983,ivo:0x8185bb,skinA:0xd1a080,skinB:0xbb8b70,shadow:0x0b120d};
let app,root,terrain,objects,artifacts,agentsLayer,screenFx,current,lastTick=null;
let camera={x:W*.56,y:W*.64,scale:1.35,mode:'auto',manualUntil:0,vx:0,vy:0};
const agentSprites=new Map(),pointers=new Map(),selectables=new Map();let gesture=null,lastTap={t:0,x:0,y:0},selection=null,rain=[];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function hash(s){let h=2166136261;for(let i=0;i<String(s).length;i++){h^=String(s).charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=hash(seed)||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function mix(a,b,t){const ar=a>>16&255,ag=a>>8&255,ab=a&255,br=b>>16&255,bg=b>>8&255,bb=b&255;return((Math.round(ar+(br-ar)*t)<<16)|(Math.round(ag+(bg-ag)*t)<<8)|Math.round(ab+(bb-ab)*t))>>>0}
function shade(c,f){return mix(c,f>0?0xffffff:0x000000,Math.min(1,Math.abs(f)))}
function sp(e){const r=app.view.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function viewAnchor(){const mobile=(app?.screen?.width||999)<650;return{x:app.screen.width/2,y:mobile?app.screen.height*.405:app.screen.height*.50}}
function s2w(s,z=camera.scale){const a=viewAnchor();return{x:(s.x-a.x)/z+camera.x,y:(s.y-a.y)/z+camera.y}}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
async function init(){const host=$('#worldViewport');app=new PIXI.Application({resizeTo:host,backgroundColor:C.ground,antialias:true,resolution:Math.min(devicePixelRatio||1,2),autoDensity:true});host.appendChild(app.view);app.stage.sortableChildren=true;root=new PIXI.Container();root.sortableChildren=true;app.stage.addChild(root);terrain=new PIXI.Container();objects=new PIXI.Container();artifacts=new PIXI.Container();agentsLayer=new PIXI.Container();terrain.zIndex=0;objects.zIndex=20;artifacts.zIndex=30;agentsLayer.zIndex=40;root.addChild(terrain,objects,artifacts,agentsLayer);screenFx=new PIXI.Container();screenFx.zIndex=100;app.stage.addChild(screenFx);wireCamera();wireUI();app.ticker.add(tick);await load(true);setInterval(()=>load(false),12000);window.addEventListener('resize',()=>{drawAtmosphere();updateCamera(true)})}
async function load(first){let w=null;for(const u of [`${RAW}?v=${Date.now()}`,`./world/state.json?v=${Date.now()}`]){try{const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(String(r.status));w=await r.json();break}catch(e){console.warn('world source failed',u,e)}}if(!w?.worldModel)return;const changed=lastTick!==w.meta?.tickNumber;current=w;lastTick=w.meta?.tickNumber;if(changed||first){renderWorld();renderUI();renderAgents();if(first)frameActivity(true)}drawAtmosphere();$('#loading')?.classList.add('hidden')}
function influence(t,x,y){const p=wp(t.center),r=((t.radiusM||20)/2)*PX;return clamp(1-Math.hypot(x-p.x,y-p.y)/r,0,1)}
function terrainBy(type){return(current.worldModel?.terrain||[]).filter(t=>t.type===type)}
function field(type,x,y){return terrainBy(type).reduce((m,t)=>Math.max(m,influence(t,x,y)),0)}
function renderWorld(){for(const l of [terrain,objects,artifacts])l.removeChildren().forEach(d=>d.destroy({children:true}));selectables.clear();drawGround();drawCreek();drawAggregateTerrain();const os=(current.worldModel.objects||[]).filter(o=>o.state?.active!==false);os.filter(o=>!o.parentId).forEach(drawObject);os.filter(o=>o.parentId).forEach(drawComponent);(current.artifacts||[]).filter(a=>a.status==='active'||a.status==='remnant').forEach(drawArtifact)}
function drawGround(){const base=new PIXI.Graphics();base.beginFill(C.ground).drawRect(0,0,W,W).endFill();terrain.addChild(base);const R=rng('ground-v5'),patches=new PIXI.Graphics();for(let i=0;i<1450;i++){const x=R()*W,y=R()*W,f=field('forest',x,y),w=field('wetland',x,y),rx=22+R()*92,ry=10+R()*42;let col=C.ground2,a=.045+R()*.07;if(f>.08){col=mix(C.forestGround,C.ground,f*.26);a=.07+.13*f}else if(w>.08){col=mix(C.wet,C.mud,.10);a=.065+.12*w}else if(R()>.68){col=mix(C.ground2,0xa0a873,.18);a=.04+.04*R()}patches.beginFill(col,a).drawEllipse(x,y,rx,ry).endFill()}terrain.addChild(patches);const detail=new PIXI.Graphics();for(let i=0;i<2800;i++){const x=R()*W,y=R()*W,f=field('forest',x,y),w=field('wetland',x,y);if(w>.2&&R()<.62){detail.lineStyle(1.6,C.reed,.30+.22*w).moveTo(x,y+4).lineTo(x+(R()-.5)*4,y-8-R()*14)}else if(f>.2&&R()<.55){detail.beginFill(C.forestDark,.14+.13*f).drawEllipse(x,y,2+R()*6,1+R()*3).endFill();if(R()<.22)detail.beginFill(C.forestHi,.12).drawCircle(x+(R()-.5)*6,y+(R()-.5)*4,1.5+R()*2.5).endFill()}else if(R()<.68){detail.lineStyle(1.3,C.ground2,.20+R()*.10).moveTo(x,y+2).lineTo(x+(R()-.5)*4,y-5-R()*8);if(R()<.16)detail.beginFill(C.mud,.10).drawEllipse(x+3,y+3,3+R()*7,1+R()*3).endFill()}}terrain.addChild(detail);const micro=new PIXI.Graphics();for(let i=0;i<900;i++){const x=R()*W,y=R()*W,f=field('forest',x,y),w=field('wetland',x,y);if(f>.28){micro.beginFill(R()>.5?0x334c35:0x5b704f,.22).drawCircle(x,y,2+R()*4).endFill()}else if(w>.28){micro.beginFill(C.mud,.12).drawEllipse(x,y,5+R()*10,2+R()*4).endFill()}else if(R()<.34){micro.beginFill(0x929b78,.18).drawEllipse(x,y,2+R()*4,1+R()*2).endFill()}}terrain.addChild(micro)}
function drawTree(x,y,s,R){const c=new PIXI.Container();c.position.set(x,y);c.zIndex=y;const shadow=new PIXI.Graphics();shadow.beginFill(C.shadow,.16).drawEllipse(4,12,s*.8,s*.34).endFill();const trunk=new PIXI.Graphics();trunk.beginFill(0x5a3f2b,.96).drawRoundedRect(-3,-2,6,15,2).endFill();const crown=new PIXI.Graphics();crown.beginFill(C.forestLeaf,.98).drawCircle(-s*.25,-s*.20,s*.52).drawCircle(s*.25,-s*.18,s*.55).drawCircle(0,-s*.52,s*.62).endFill();crown.beginFill(C.forestHi,.45).drawCircle(-s*.18,-s*.65,s*.28).endFill();c.addChild(shadow,trunk,crown);terrain.addChild(c)}
function drawAggregateTerrain(){for(const t of current.worldModel.terrain||[]){const p=wp(t.center),r=((t.radiusM||20)/2)*PX,R=rng(`${t.id}-v4`);if(t.type==='forest'){for(let i=0;i<68;i++){const a=R()*Math.PI*2,rr=Math.sqrt(R())*r*.96;drawTree(p.x+Math.cos(a)*rr,p.y+Math.sin(a)*rr,13+R()*12,R)}}else if(t.type==='wetland'){const g=new PIXI.Graphics();for(let i=0;i<120;i++){const a=R()*Math.PI*2,rr=Math.sqrt(R())*r,x=p.x+Math.cos(a)*rr,y=p.y+Math.sin(a)*rr,h=15+R()*28;g.lineStyle(2,C.reed,.5).moveTo(x,y+5).lineTo(x+(R()-.5)*3,y-h);if(i%4===0)g.beginFill(0x82623d,.55).drawEllipse(x,y-h,2,6).endFill()}terrain.addChild(g)}}}
function drawCreek(){const creek=(current.worldModel.objects||[]).find(o=>o.type==='creek_segment');if(!creek?.geometry?.points)return;const pts=creek.geometry.points.map(([x,y])=>wp({x,y})),depth=current.worldModel?.fields?.waterDepth?.objects?.[creek.id]??.42,width=48+depth*20;const bank=new PIXI.Graphics();bank.lineStyle(width+30,mix(C.bank,C.mud,.28),.92).moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(p=>bank.lineTo(p.x,p.y));terrain.addChild(bank);const water=new PIXI.Graphics();water.lineStyle(width,mix(C.water,C.waterDark,depth*.35),.98).moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(p=>water.lineTo(p.x,p.y));terrain.addChild(water);const R=rng('creek-v4');for(let i=0;i<30;i++){const s=i%(pts.length-1),q=R(),a=pts[s],b=pts[s+1],x=a.x+(b.x-a.x)*q,y=a.y+(b.y-a.y)*q+(R()-.5)*width*.62,z=3+R()*6;const rock=new PIXI.Graphics();rock.beginFill(R()>.5?C.rock:C.rock2,.9).drawEllipse(x,y,z,z*.65).endFill();terrain.addChild(rock)}}
function makeSelectable(c,data,kind='object'){c.eventMode='static';c.cursor='pointer';c.on('pointertap',e=>{e.stopPropagation();showSelection(c);openInspector(data,kind)});selectables.set(data.id,c);return c}
function showSelection(c){selection?.destroy();selection=new PIXI.Graphics();selection.lineStyle(2,0xb6f79d,.9).drawCircle(0,0,32);c.addChild(selection)}
function label(c,text,y=38){const t=new PIXI.Text(text,{fontFamily:'Arial',fontSize:12,fontWeight:'600',fill:0xf4f7f1,stroke:0x09110b,strokeThickness:4});t.anchor.set(.5);t.y=y;t.alpha=0;c.addChild(t);c.on('pointerover',()=>t.alpha=.95);c.on('pointerout',()=>t.alpha=0)}
function wetWood(o){const m=Number(o.material?.moisturePct??28);return mix(C.wood,C.woodWet,clamp((m-12)/55,0,.75))}
function drawObject(o){if(o.type==='creek_segment')return;const p=wp(o.position),c=new PIXI.Container();c.position.set(p.x,p.y);c.zIndex=p.y;const R=rng(o.id),g=new PIXI.Graphics();if(o.type==='camp_area'){for(let i=0;i<18;i++){const a=R()*Math.PI*2,rr=Math.sqrt(R())*90;g.beginFill(C.mud,.07).drawEllipse(Math.cos(a)*rr,Math.sin(a)*rr*.58,8+R()*20,3+R()*7).endFill()}}
else if(o.type==='berry_patch'){const fruit=Math.max(0,o.state?.ediblePortions||0),count=o.state?.exhausted?4:12;for(let i=0;i<count;i++){const x=(R()-.5)*110,y=(R()-.5)*64,s=(o.state?.exhausted?7:11)+R()*8;g.beginFill(o.state?.exhausted?C.leafDry:C.leaf,.98).drawCircle(x,y,s).endFill();g.beginFill(shade(o.state?.exhausted?C.leafDry:C.leaf,.12),.45).drawCircle(x-4,y-5,s*.45).endFill();if(i<fruit*2)g.beginFill(C.berry,.95).drawCircle(x+(R()-.5)*10,y+(R()-.5)*8,3).endFill()}}
else if(o.type==='fallen_tree'){const len=(o.geometry?.lengthM||4.8)*29,wc=wetWood(o);g.lineStyle(25,C.woodDark,.98).moveTo(-len/2,0).lineTo(len/2,0);g.lineStyle(17,wc,.99).moveTo(-len/2,0).lineTo(len/2,0);g.lineStyle(2,shade(wc,.2),.5).moveTo(-len/2+9,-4).lineTo(len/2-9,-4);if(!o.resolution?.componentsInstantiated)for(let i=0;i<4;i++){const x=-len*.34+i*len*.22,d=i%2?-1:1;g.lineStyle(7,wc,.96).moveTo(x,0).lineTo(x+d*(24+R()*24),d*(18+R()*21))}c.rotation=((o.geometry?.orientationDeg||0)-90)*Math.PI/180}
else if(o.type==='stone_field'){for(let i=0;i<18;i++){const a=R()*Math.PI*2,rr=Math.sqrt(R())*78,x=Math.cos(a)*rr,y=Math.sin(a)*rr*.5,s=6+R()*10;g.beginFill(i%2?C.rock:C.rock2,.98).drawEllipse(x,y,s,s*.7).endFill();g.beginFill(0xd2d8d3,.17).drawEllipse(x-2,y-2,s*.55,s*.25).endFill()}}
else if(o.type==='clay_bank'){g.beginFill(mix(C.clay,C.mud,.14),.9).drawEllipse(0,0,84,43).endFill();for(let i=0;i<13;i++)g.beginFill(i%2?0xd19a73:0x77513c,.2+R()*.12).drawEllipse((R()-.5)*118,(R()-.5)*52,5+R()*12,2+R()*5).endFill()}
else if(o.type==='reed_marsh'){g.beginFill(C.wet,.34).drawEllipse(0,9,102,60).endFill();for(let i=0;i<9;i++){const px=(R()-.5)*150,py=(R()-.5)*70;g.beginFill(C.waterDark,.14).drawEllipse(px,py+15,12+R()*24,4+R()*9).endFill()}for(let i=0;i<86;i++){const x=(R()-.5)*150,y=(R()-.5)*104,h=26+R()*52;g.lineStyle(2.4,C.reed,.94).moveTo(x,y+10).lineTo(x+(R()-.5)*6,y-h);if(i%3===0)g.beginFill(0x86623d,.9).drawEllipse(x,y-h,2.6,7).endFill()}}
else if(o.type==='frontier'){for(let i=0;i<12;i++){const x=(R()-.5)*210,y=(R()-.5)*220,r=40+R()*75;g.beginFill(0xdbe1da,.014+R()*.015).drawCircle(x,y,r).endFill()}}
else if(o.type==='branch_shelter'){const shadow=new PIXI.Graphics();shadow.beginFill(C.shadow,.18).drawEllipse(3,25,55,16).endFill();c.addChild(shadow);g.beginFill(0x5f462f,.98).moveTo(-52,29).lineTo(0,-50).lineTo(54,29).lineTo(36,29).lineTo(0,-26).lineTo(-31,29).closePath().endFill();g.lineStyle(4,0x9a7449,.9).moveTo(-46,26).lineTo(0,-47).lineTo(47,26)}
else if(o.type==='camp_fire'){const glow=new PIXI.Graphics();glow.beginFill(C.fire2,.14).drawCircle(0,0,72).endFill();c.addChild(glow);g.beginFill(C.rock2,.95);for(let i=0;i<8;i++){const a=i/8*Math.PI*2;g.drawCircle(Math.cos(a)*20,Math.sin(a)*12+8,5)}g.endFill();g.lineStyle(6,C.woodDark,.98).moveTo(-19,13).lineTo(19,3).moveTo(-19,3).lineTo(19,13);const f=new PIXI.Graphics();f.beginFill(C.fire,.98).drawPolygon([-12,12,0,-31,12,12]).endFill();f.beginFill(C.fire2,.95).drawPolygon([-6,9,0,-15,6,9]).endFill();f.name='flame';c.addChild(f)}
else if(o.type==='drying_rack'){g.lineStyle(6,C.wood,.98).moveTo(-36,24).lineTo(-24,-27).moveTo(36,24).lineTo(24,-27).moveTo(-31,-10).lineTo(31,-10);for(let i=-18;i<=18;i+=9)g.lineStyle(2,0xb09a69,.86).moveTo(i,-10).lineTo(i,16)}
else if(o.type==='animal_tracks'){const clarity=clamp(o.state?.clarity??.72,.1,1);for(let i=0;i<7;i++){const x=i*12-35,y=(i%2?6:-5)+i*2;g.beginFill(0x2b2119,.5*clarity).drawEllipse(x,y,4,6).endFill();g.beginFill(0x2b2119,.36*clarity).drawCircle(x-4,y-4,2).drawCircle(x,y-6,2).drawCircle(x+4,y-4,2).endFill()}}
else return;c.addChildAt(g,0);makeSelectable(c,o);if(!['camp_area','frontier'].includes(o.type))label(c,o.label);objects.addChild(c)}
function drawComponent(o){const p=wp(o.position),c=new PIXI.Container();c.position.set(p.x,p.y);c.zIndex=p.y+3;const g=new PIXI.Graphics();if(o.type==='branch')g.lineStyle(6,C.wood,.98).moveTo(-17,0).lineTo(17,0);else if(o.type==='rock')g.beginFill(C.rock,.98).drawEllipse(0,0,10,7).endFill();else if(o.type==='berry_bush')g.beginFill(C.leaf,.98).drawCircle(0,0,13).endFill();else if(o.type==='clay_deposit')g.beginFill(C.clay,.92).drawEllipse(0,0,14,8).endFill();else if(o.type==='reed_stand'){for(let i=-9;i<=9;i+=4)g.lineStyle(2,C.reed,.95).moveTo(i,9).lineTo(i,-22-Math.abs(i))}else if(o.type==='trunk')g.lineStyle(20,C.wood,.98).moveTo(-24,0).lineTo(24,0);else return;c.addChild(g);makeSelectable(c,o);label(c,o.label,28);objects.addChild(c)}
function drawArtifact(a){const p=wp(a.coordinates||{x:50,y:50}),c=new PIXI.Container();c.position.set(p.x+12,p.y-10);c.zIndex=p.y+8;const g=new PIXI.Graphics(),t=a.type||'';if(/ClayVessel/i.test(t)){g.lineStyle(2,0xe0b28b,.9).beginFill(0xa87150,.98).drawEllipse(0,3,10,13).endFill().moveTo(-7,-5).lineTo(7,-5)}else if(/sharpStone/i.test(t))g.beginFill(0xa9b1aa,.98).drawPolygon([-11,8,0,-11,10,7]).endFill();else if(/Pole/i.test(t))g.lineStyle(5,C.wood,.98).moveTo(-18,9).lineTo(18,-9);else if(/cordage/i.test(t))g.lineStyle(3,0xc3aa70,.95).drawCircle(0,0,10);else g.beginFill(0xd3c38a,.92).drawCircle(0,0,6).endFill();c.addChild(g);makeSelectable(c,a,'artifact');artifacts.addChild(c)}
function progress(){if(!current)return 1;const t=current.meta?.lastAdvancedAt?new Date(current.meta.lastAdvancedAt).getTime():Date.now(),period=(current.meta?.heartbeatMinutes||5)*60000;return clamp((Date.now()-t)/period,0,1)}
function phase(a){const plan=a.activeAction,p=progress();if(!plan?.phases?.length)return{phase:'idle',label:'Between actions',x:a.coordinates?.x??50,y:a.coordinates?.y??50};const ph=plan.phases.find(x=>p>=x.start&&p<x.end)||plan.phases.at(-1),from=plan.from||a.coordinates,to=plan.to||a.coordinates;let x=to.x,y=to.y;if(plan.moving){const tr=plan.phases.find(x=>x.id==='travel');if(tr&&p<tr.start){x=from.x;y=from.y}else if(tr&&p<tr.end){const q=clamp((p-tr.start)/(tr.end-tr.start),0,1);x=from.x+(to.x-from.x)*q;y=from.y+(to.y-from.y)*q}}return{phase:ph.id,label:ph.label,x,y}}
function makeAgent(a,i){const c=new PIXI.Container();c.zIndex=1000;const sh=new PIXI.Graphics();sh.beginFill(C.shadow,.28).drawEllipse(0,18,21,8).endFill();const legs=new PIXI.Graphics();legs.lineStyle(6,0x29312c,1).moveTo(-6,10).lineTo(-8,24).moveTo(6,10).lineTo(8,24);const body=new PIXI.Graphics();body.beginFill(i?C.ivo:C.mara).drawRoundedRect(-13,-10,26,32,9).endFill();const head=new PIXI.Graphics();head.beginFill(i?C.skinB:C.skinA).drawCircle(0,-22,10).endFill();const hair=new PIXI.Graphics();hair.beginFill(i?0x2d2927:0x5b3d2d).drawEllipse(0,-26,10,5).endFill();const arm=new PIXI.Graphics();arm.lineStyle(5,i?0x5b5f8c:0x587b64,1).moveTo(10,-1).lineTo(18,10);const prop=new PIXI.Container();prop.position.set(20,4);const name=new PIXI.Text(a.name,{fontFamily:'Arial',fontSize:13,fontWeight:'700',fill:0xffffff,stroke:0x08100b,strokeThickness:4});name.anchor.set(.5);name.y=-45;const status=new PIXI.Text('',{fontFamily:'Arial',fontSize:9,fill:0xd7e1d6,stroke:0x08100b,strokeThickness:3});status.anchor.set(.5);status.y=34;c.addChild(sh,legs,body,head,hair,arm,prop,name,status);c.eventMode='static';c.cursor='pointer';c.on('pointertap',e=>{e.stopPropagation();showSelection(c);openInspector(a,'agent')});c._p={legs,body,head,hair,arm,prop,status};agentsLayer.addChild(c);agentSprites.set(a.id,c);return c}
function renderAgents(){current.agents.forEach((a,i)=>{let c=agentSprites.get(a.id);if(!c)c=makeAgent(a,i);c._data=a})}
function tick(d){if(!current)return;const t=performance.now()/1000;for(const [i,a] of current.agents.entries()){const c=agentSprites.get(a.id);if(!c)continue;const s=phase(a),p=wp(s),q=c._p;window.ChatGPTFarmActionVisuals?.redraw(q.prop,a,s,t,C,PIXI);c.position.set(p.x,p.y);c.zIndex=p.y+20;const talk=/talk/i.test(a.currentAction||a.mind?.intent||''),rest=/rest|sleep/i.test(a.currentAction||a.mind?.intent||'');q.status.text=s.phase==='travel'?'walking':talk?'talking':rest?'resting':s.phase==='interact'?'working':'';q.status.alpha=q.status.text?.8:0;if(s.phase==='travel'){q.legs.rotation=Math.sin(t*10+i)*.2;q.body.y=Math.sin(t*10+i)*1.5;q.arm.rotation=-Math.sin(t*10+i)*.16;c.rotation=0}else if(rest){q.legs.rotation=.4;q.body.rotation=-.18;q.body.y=9;q.head.y=6;q.hair.y=6;q.arm.rotation=.5}else if(s.phase==='interact'){q.arm.rotation=Math.sin(t*7+i)*.35;q.body.y=Math.sin(t*5+i)*.8;q.legs.rotation=0}else{q.legs.rotation=0;q.body.rotation=0;q.body.y=Math.sin(t*2+i)*.4;q.head.y=0;q.hair.y=0;q.arm.rotation=0}}for(const c of objects.children){const f=c.getChildByName?.('flame');if(f){f.scale.y=.87+Math.sin(t*8)*.14;f.rotation=Math.sin(t*5)*.07}}for(const r of rain){r.y+=r._s*d;r.x-=r._s*.2*d;if(r.y>app.screen.height+20){r.y=-20;r.x=Math.random()*app.screen.width}}applyInertia(d);updateCamera(false)}
function drawAtmosphere(){screenFx.removeChildren().forEach(d=>d.destroy({children:true}));rain=[];const f=current?.worldModel?.fields||{},pr=f.precipitation?.global||0;if(pr>0){for(let i=0;i<Math.round(25+pr*35);i++){const g=new PIXI.Graphics();g.lineStyle(1,0xd8ecec,.11+Math.random()*.10).moveTo(0,0).lineTo(-3,8+Math.random()*8);g.x=Math.random()*app.screen.width;g.y=Math.random()*app.screen.height;g._s=4+Math.random()*7;screenFx.addChild(g);rain.push(g)}}const light=f.light?.global??.5,dark=clamp(.34-light*.35,0,.30);if(dark>.015){const g=new PIXI.Graphics();g.beginFill(0x08111a,dark).drawRect(0,0,app.screen.width,app.screen.height).endFill();g.eventMode='none';screenFx.addChild(g)}}
function setFree(){camera.mode='free';camera.manualUntil=Date.now()+30000;syncButtons()}
function zoomAt(pt,z){const old=camera.scale,next=clamp(z,MIN,MAX),world=s2w(pt,old),a=viewAnchor();camera.scale=next;camera.x=world.x-(pt.x-a.x)/next;camera.y=world.y-(pt.y-a.y)/next;setFree();updateCamera(true)}
function wireCamera(){const cv=app.view;cv.style.touchAction='none';cv.addEventListener('pointerdown',e=>{const p=sp(e);pointers.set(e.pointerId,p);cv.setPointerCapture?.(e.pointerId);camera.vx=camera.vy=0;if(pointers.size===1)gesture={type:'pan',id:e.pointerId,start:p,last:p,cx:camera.x,cy:camera.y,moved:false,time:performance.now()};else if(pointers.size===2){const [a,b]=[...pointers.values()],mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};gesture={type:'pinch',dist:dist(a,b),scale:camera.scale,world:s2w(mid),mid}}});cv.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const p=sp(e);pointers.set(e.pointerId,p);if(pointers.size===2){const [a,b]=[...pointers.values()],mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};if(gesture?.type!=='pinch')gesture={type:'pinch',dist:dist(a,b),scale:camera.scale,world:s2w(mid),mid};const nz=clamp(gesture.scale*(dist(a,b)/Math.max(20,gesture.dist)),MIN,MAX);camera.scale=nz;camera.x=gesture.world.x-(mid.x-app.screen.width/2)/nz;camera.y=gesture.world.y-(mid.y-app.screen.height/2)/nz;setFree();updateCamera(true);return}if(gesture?.type==='pan'&&gesture.id===e.pointerId){const dx=p.x-gesture.start.x,dy=p.y-gesture.start.y;if(Math.abs(dx)+Math.abs(dy)>5)gesture.moved=true;if(gesture.moved){camera.x=gesture.cx-dx/camera.scale;camera.y=gesture.cy-dy/camera.scale;const dt=Math.max(12,performance.now()-gesture.time);camera.vx=-(p.x-gesture.last.x)/camera.scale/dt*16;camera.vy=-(p.y-gesture.last.y)/camera.scale/dt*16;gesture.last=p;gesture.time=performance.now();setFree();updateCamera(true)}}});const end=e=>{const p=sp(e),was=gesture;pointers.delete(e.pointerId);if(was?.type==='pan'&&!was.moved){const now=Date.now();if(now-lastTap.t<330&&dist(p,lastTap)<34){zoomAt(p,camera.scale*1.5);lastTap.t=0}else{lastTap={t:now,x:p.x,y:p.y};$('#inspector')?.classList.remove('open');selection?.destroy();selection=null}}if(!pointers.size)gesture=null;else if(pointers.size===1){const [q]=pointers.values();gesture={type:'pan',id:[...pointers.keys()][0],start:q,last:q,cx:camera.x,cy:camera.y,moved:false,time:performance.now()}}};cv.addEventListener('pointerup',end);cv.addEventListener('pointercancel',end);cv.addEventListener('wheel',e=>{e.preventDefault();zoomAt(sp(e),camera.scale*Math.exp(-e.deltaY*.001))},{passive:false})}
function applyInertia(d){if(camera.mode!=='free'||pointers.size)return;if(Math.abs(camera.vx)+Math.abs(camera.vy)<.02)return;camera.x+=camera.vx*d;camera.y+=camera.vy*d;camera.vx*=Math.pow(.90,d);camera.vy*=Math.pow(.90,d)}
function autoAgent(){const top=current?.liveThreads?.[0];if(top?.agentIds?.length){const a=current.agents.find(x=>x.id===top.agentIds[0]);if(a)return a}return current?.agents?.find(x=>x.activeAction?.moving)||current?.agents?.find(x=>phase(x).phase==='interact')||current?.agents?.[0]}
function actionFrame(a){if(!a)return{x:W*.55,y:W*.62,scale:1.35};const s=phase(a),pts=[wp(s)],plan=a.activeAction||{};if(plan.to)pts.push(wp(plan.to));if(plan.moving&&plan.from)pts.push(wp(plan.from));const social=/talk|teach|share|speak/i.test(`${a.currentAction||''} ${a.mind?.intent||''}`);if(social){const other=current?.agents?.find(x=>x.id!==a.id);if(other)pts.push(wp(phase(other)))}let minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y));const mobile=app.screen.width<650,safeW=app.screen.width*(mobile?.88:.76),safeH=app.screen.height*(mobile?.48:.70),spanX=Math.max(120,maxX-minX),spanY=Math.max(100,maxY-minY),pad=mobile?150:210;let scale=clamp(Math.min(safeW/(spanX+pad),safeH/(spanY+pad)),mobile?1.05:.82,mobile?1.95:1.65);if(pts.length===1||Math.max(spanX,spanY)<150)scale=mobile?1.72:1.42;return{x:(minX+maxX)/2,y:(minY+maxY)/2,scale}}
function frameActivity(force){if(!current)return;const f=actionFrame(autoAgent());camera.x=f.x;camera.y=f.y;camera.scale=f.scale;camera.mode='auto';camera.manualUntil=0;camera.vx=camera.vy=0;syncButtons();updateCamera(force)}
function updateCamera(force){if(!root||!app)return;let target={x:camera.x,y:camera.y,scale:camera.scale};if(camera.mode==='auto'&&Date.now()>camera.manualUntil)target=actionFrame(autoAgent());else if(camera.mode.startsWith('agent-')){const a=current?.agents?.find(x=>x.id===camera.mode);if(a)target=actionFrame(a)}const k=force?1:.065;camera.x+=(target.x-camera.x)*k;camera.y+=(target.y-camera.y)*k;camera.scale+=(target.scale-camera.scale)*(force?1:.045);const a=viewAnchor();root.scale.set(camera.scale);root.position.set(a.x-camera.x*camera.scale,a.y-camera.y*camera.scale)}
function wireUI(){document.querySelectorAll('[data-camera]').forEach(b=>b.addEventListener('click',()=>{const m=b.dataset.camera;if(m==='auto')frameActivity(true);else{camera.mode=m;camera.manualUntil=0;camera.scale=Math.max(camera.scale,1.45);syncButtons();updateCamera(true)}}));$('#zoomIn')?.addEventListener('click',()=>zoomAt({x:app.screen.width/2,y:app.screen.height/2},camera.scale*1.2));$('#zoomOut')?.addEventListener('click',()=>zoomAt({x:app.screen.width/2,y:app.screen.height/2},camera.scale/1.2));$('#fitWorld')?.addEventListener('click',()=>frameActivity(true));$('#closeInspector')?.addEventListener('click',()=>$('#inspector').classList.remove('open'));$('.threadTop')?.addEventListener('click',()=>$('.threadPanel')?.classList.toggle('expanded'))}
function syncButtons(){document.querySelectorAll('[data-camera]').forEach(b=>b.classList.toggle('active',b.dataset.camera===camera.mode))}
function renderUI(){const s=$('#worldStatus');if(s)s.innerHTML=`<strong>● OBJECT WORLD · ${esc(current.version||'?')}</strong><span>Day ${current.day} · ${String(current.hour).padStart(2,'0')}:00 · ${Math.round(current.temperature)}°F · ${esc(current.weather)}</span>`;const list=current.liveThreads||[],t=$('#threads');if(t){t.innerHTML=list.length?list.map(x=>`<article class="thread ${x.urgency>=85?'urgent':x.urgency>=60?'high':''}"><b>${esc(x.title)}</b><p>${esc(x.summary)}</p><small>${esc(x.kind)} · urgency ${x.urgency}</small></article>`).join(''):'<article class="thread"><b>Quiet stretch</b><p>No high-signal unresolved thread.</p></article>';$('#threadCount').textContent=`${list.length} active thread${list.length===1?'':'s'}`}updateFocus()}
function updateFocus(){const a=autoAgent();if(!a)return;const s=phase(a),v=window.ChatGPTFarmActionVisuals,d=v?.descriptor(a),where=v?.placeLabel(a.position)||a.position,what=d?.label?` · ${d.label}`:'';$('#focusCard').innerHTML=`<div class="focusInner"><small>${esc(s.label).toUpperCase()} · ${esc(where).toUpperCase()}${esc(what).toUpperCase()}</small><strong>${esc(a.name)} — ${esc(a.mind?.currentGoal||a.currentAction||'Responding to the world')}</strong><p>${esc(a.mind?.intent||a.currentAction||'')}</p></div>`}
function flatten(o,p=''){const r=[];for(const[k,v]of Object.entries(o||{})){if(v==null)continue;const key=p?`${p}.${k}`:k;if(typeof v==='object'&&!Array.isArray(v))r.push(...flatten(v,key));else r.push([key,Array.isArray(v)?v.join(', '):String(v)])}return r}
function openInspector(d,k){const panel=$('#inspector');if(!panel)return;$('#inspectType').textContent=k==='agent'?'AUTONOMOUS AGENT':k==='artifact'?'PERSISTENT ARTIFACT':'CANONICAL WORLD OBJECT';$('#inspectTitle').textContent=d.name||d.label||d.id;$('#inspectBody').innerHTML=k==='agent'?agentInspector(d):k==='artifact'?artifactInspector(d):objectInspector(d);panel.classList.add('open')}
function objectInspector(o){const phys=Object.entries(o.physical||{}).filter(([,v])=>v===true).map(([k])=>k),props=[['ID',o.id],['Type',o.type],['Zone',o.zone],['Resolution',o.resolution?.level||'—'],['Parent',o.parentId||'independent'],['Position',`${o.position?.x??'?'}, ${o.position?.y??'?'}`]],mat=flatten(o.material||{}).slice(0,8),st=flatten(o.state||{}).slice(0,8);return `<div class="kv">${props.map(([k,v])=>`<span>${esc(k)}</span><b>${esc(v)}</b>`).join('')}</div><div class="pillRow">${phys.map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</div>${mat.length?`<div class="kv">${mat.map(([k,v])=>`<span>${esc(k)}</span><b>${esc(v)}</b>`).join('')}</div>`:''}${st.length?`<div class="kv">${st.map(([k,v])=>`<span>state.${esc(k)}</span><b>${esc(v)}</b>`).join('')}</div>`:''}`}
function agentInspector(a){const n=a.needs||{};return `<div class="kv"><span>ID</span><b>${esc(a.id)}</b><span>Location</span><b>${esc(a.position)}</b><span>Hydration</span><b>${Math.round(n.hydration||0)}%</b><span>Satiety</span><b>${Math.round(n.hunger||0)}%</b><span>Energy</span><b>${Math.round(n.energy||0)}%</b><span>Warmth</span><b>${Math.round(n.warmth||0)}%</b><span>Goal</span><b>${esc(a.mind?.currentGoal||'—')}</b><span>Intent</span><b>${esc(a.mind?.intent||a.currentAction||'—')}</b></div>`}
function artifactInspector(a){return `<div class="kv"><span>ID</span><b>${esc(a.id)}</b><span>Type</span><b>${esc(a.type)}</b><span>Status</span><b>${esc(a.status)}</b><span>Carrier</span><b>${esc(a.carrierId||'none')}</b><span>Position</span><b>${esc(a.position)}</b></div>`}
init().catch(e=>{console.error(e);const l=$('#loading');if(l)l.innerHTML=`<div class="loadingBox"><div class="loadingMark">!</div><strong>Renderer failed</strong><p>${esc(e.message||e)}</p></div>`});
})();