(()=>{
'use strict';
const RAW='https://raw.githubusercontent.com/kyle8824/chatgptfarm/main/world/state.json';
const U=100,PX=24,W=U*PX,MIN=.42,MAX=3.2;
const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const wp=p=>({x:(p?.x??50)*PX,y:(100-(p?.y??50))*PX});
const C={ground:0x627654,meadow:0x70845d,meadow2:0x7d9068,forest:0x2d4936,forest2:0x3e5c43,wet:0x496b5d,water:0x68aabd,water2:0x427d92,bank:0x77735c,mud:0x655944,wood:0x795538,woodWet:0x493b31,woodDark:0x443126,leaf:0x315f37,leafDry:0x556545,berry:0xca4e5b,rock:0x89918a,rock2:0x58625b,clay:0xaa714f,reed:0x768e59,fire:0xf39b45,fire2:0xffd46c,mara:0x6f9b79,ivo:0x7c7fad,skinA:0xc99b7a,skinB:0xb88970,shadow:0x08100b};
let app,root,terrain,objects,artifacts,agentLayer,fx,screenFx,current,lastTick=null;
let camera={x:W*.55,y:W*.64,scale:1.2,mode:'auto',manualUntil:0,vx:0,vy:0};
const agents=new Map(),selectables=new Map(),pointers=new Map(),waterGlints=[];let gesture=null,lastTap={t:0,x:0,y:0},selectionRing=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function hash(s){let h=2166136261;for(let i=0;i<String(s).length;i++){h^=String(s).charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=hash(seed)||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function mix(a,b,t){const ar=a>>16&255,ag=a>>8&255,ab=a&255,br=b>>16&255,bg=b>>8&255,bb=b&255;return((Math.round(ar+(br-ar)*t)<<16)|(Math.round(ag+(bg-ag)*t)<<8)|Math.round(ab+(bb-ab)*t))>>>0}
function shade(c,f){return mix(c,f>0?0xffffff:0x000000,Math.min(1,Math.abs(f)))}
function screenPoint(e){const r=app.view.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function screenToWorld(s,z=camera.scale){return{x:(s.x-app.screen.width/2)/z+camera.x,y:(s.y-app.screen.height/2)/z+camera.y}}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
async function init(){const host=$('#worldViewport');app=new PIXI.Application({resizeTo:host,backgroundColor:0x111a12,antialias:true,resolution:Math.min(devicePixelRatio||1,2),autoDensity:true});host.appendChild(app.view);app.stage.sortableChildren=true;root=new PIXI.Container();root.sortableChildren=true;app.stage.addChild(root);terrain=new PIXI.Container();objects=new PIXI.Container();artifacts=new PIXI.Container();agentLayer=new PIXI.Container();fx=new PIXI.Container();terrain.zIndex=0;objects.zIndex=20;artifacts.zIndex=30;agentLayer.zIndex=40;fx.zIndex=50;root.addChild(terrain,objects,artifacts,agentLayer,fx);screenFx=new PIXI.Container();screenFx.zIndex=100;app.stage.addChild(screenFx);wireCamera();wireUI();app.ticker.add(tick);await loadWorld(true);setInterval(()=>loadWorld(false),12000);window.addEventListener('resize',()=>{drawScreenFx();if(camera.mode!=='free')frameActivity(false);else updateCamera(true)})}
async function loadWorld(first){let w=null;for(const u of [`${RAW}?v=${Date.now()}`,`./world/state.json?v=${Date.now()}`]){try{const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(String(r.status));w=await r.json();break}catch(e){console.warn('world source failed',u,e)}}if(!w?.worldModel)return;const changed=lastTick!==w.meta?.tickNumber;current=w;lastTick=w.meta?.tickNumber;if(changed||first){renderWorld();renderUI();renderAgents();if(first)frameActivity(true)}drawScreenFx();$('#loading')?.classList.add('hidden')}
function influence(t,x,y){const p=wp(t.center),r=((t.radiusM||20)/2)*PX;return clamp(1-Math.hypot(x-p.x,y-p.y)/r,0,1)}
function terrains(type){return(current.worldModel?.terrain||[]).filter(t=>t.type===type)}
function fieldAt(type,x,y){return terrains(type).reduce((m,t)=>Math.max(m,influence(t,x,y)),0)}
function renderWorld(){for(const l of [terrain,objects,artifacts])l.removeChildren().forEach(d=>d.destroy({children:true}));selectables.clear();waterGlints.length=0;drawGround();drawCreek();drawVegetation();const os=(current.worldModel?.objects||[]).filter(o=>o.state?.active!==false);os.filter(o=>!o.parentId).forEach(drawObject);os.filter(o=>o.parentId).forEach(drawComponent);(current.artifacts||[]).filter(a=>a.status==='active'||a.status==='remnant').forEach(drawArtifact)}
function drawGround(){const base=new PIXI.Graphics();base.beginFill(C.ground).drawRect(0,0,W,W).endFill();terrain.addChild(base);const R=rng(`ground-${current.worldModel.version}`),patches=new PIXI.Graphics();for(let i=0;i<1150;i++){const x=R()*W,y=R()*W,f=fieldAt('forest',x,y),wet=fieldAt('wetland',x,y);let col=C.meadow,alpha=.035+R()*.055,rx=16+R()*70,ry=8+R()*38;if(f>.12){col=mix(C.forest,C.forest2,R()*.45);alpha=.05+.16*f;rx*=1.1;ry*=1.1}else if(wet>.12){col=mix(C.wet,C.mud,R()*.15);alpha=.06+.14*wet}else col=R()>.48?C.meadow:C.meadow2;patches.beginFill(col,alpha).drawEllipse(x,y,rx,ry).endFill()}terrain.addChild(patches);const detail=new PIXI.Graphics();for(let i=0;i<1800;i++){const x=R()*W,y=R()*W,f=fieldAt('forest',x,y),wet=fieldAt('wetland',x,y);if(wet>.25&&R()<.7){detail.lineStyle(1.3,C.reed,.18+.2*wet).moveTo(x,y+4).lineTo(x+(R()-.5)*3,y-7-R()*10)}else if(f>.25&&R()<.55){detail.beginFill(0x20372a,.10+.12*f).drawEllipse(x,y,2+R()*5,1+R()*2.4).endFill()}else if(R()<.58){detail.lineStyle(1,C.meadow2,.12+R()*.12).moveTo(x,y).lineTo(x+(R()-.5)*3,y-3-R()*5)}}terrain.addChild(detail)}
function drawCreek(){const creek=(current.worldModel.objects||[]).find(o=>o.type==='creek_segment');if(!creek?.geometry?.points)return;const pts=creek.geometry.points.map(([x,y])=>wp({x,y})),depth=current.worldModel?.fields?.waterDepth?.objects?.[creek.id]??.42,width=44+depth*20;const bank=new PIXI.Graphics();bank.lineStyle(width+26,mix(C.bank,C.mud,depth*.35),.92).moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(p=>bank.lineTo(p.x,p.y));terrain.addChild(bank);const water=new PIXI.Graphics();water.lineStyle(width,mix(C.water,C.water2,depth*.45),.98).moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(p=>water.lineTo(p.x,p.y));terrain.addChild(water);const R=rng(creek.id);for(let i=0;i<34;i++){const s=i%(pts.length-1),q=R(),a=pts[s],b=pts[s+1],x=a.x+(b.x-a.x)*q,y=a.y+(b.y-a.y)*q+(R()-.5)*width*.62,z=3+R()*6;const r=new PIXI.Graphics();r.beginFill(R()>.5?C.rock:C.rock2,.82).drawEllipse(x,y,z,z*.7).endFill();terrain.addChild(r)}for(let i=0;i<14;i++){const gl=new PIXI.Graphics();gl.lineStyle(2,0xe5f6f5,.22).moveTo(-10,0).lineTo(10,0);gl._seed=i;gl._pts=pts;terrain.addChild(gl);waterGlints.push(gl)}}
function drawVegetation(){for(const t of current.worldModel.terrain||[]){const p=wp(t.center),r=((t.radiusM||20)/2)*PX,R=rng(t.id+'-veg');if(t.type==='forest'){for(let i=0;i<105;i++){const a=R()*Math.PI*2,rr=Math.sqrt(R())*r*.98,x=p.x+Math.cos(a)*rr,y=p.y+Math.sin(a)*rr,sz=10+R()*16;const g=new PIXI.Graphics();g.beginFill(C.shadow,.18).drawEllipse(x+4,y+7,sz*.85,sz*.4).endFill();g.beginFill(i%3?C.forest:C.forest2,.97).drawCircle(x,y,sz).endFill();g.beginFill(0x4d6a4a,.55).drawCircle(x-5,y-5,sz*.52).endFill();terrain.addChild(g)}}else if(t.type==='wetland'){const g=new PIXI.Graphics();for(let i=0;i<135;i++){const a=R()*Math.PI*2,rr=Math.sqrt(R())*r,x=p.x+Math.cos(a)*rr,y=p.y+Math.sin(a)*rr,h=12+R()*26;g.lineStyle(1.7,C.reed,.35).moveTo(x,y+4).lineTo(x+(R()-.5)*3,y-h)}terrain.addChild(g)}}}
function selectable(c,data,kind='object'){c.eventMode='static';c.cursor='pointer';c.on('pointertap',e=>{e.stopPropagation();showSelection(c);openInspector(data,kind)});selectables.set(data.id,c);return c}
function showSelection(c){if(selectionRing){selectionRing.destroy();selectionRing=null}selectionRing=new PIXI.Graphics();selectionRing.lineStyle(2,0xb7f59b,.85).drawCircle(0,0,28);selectionRing.zIndex=9999;c.addChild(selectionRing)}
function label(c,text,y=36){const t=new PIXI.Text(text,{fontFamily:'Arial',fontSize:12,fontWeight:'600',fill:0xf2f7ef,stroke:0x09110b,strokeThickness:4});t.anchor.set(.5);t.y=y;t.alpha=0;c.addChild(t);c.on('pointerover',()=>t.alpha=.95);c.on('pointerout',()=>t.alpha=0)}
function wetWood(o){const m=Number(o.material?.moisturePct??28);return mix(C.wood,C.woodWet,clamp((m-12)/55,0,.75))}
function drawObject(o){if(o.type==='creek_segment')return;const p=wp(o.position),c=new PIXI.Container();c.position.set(p.x,p.y);c.zIndex=p.y;const R=rng(o.id),g=new PIXI.Graphics();if(o.type==='camp_area'){for(let i=0;i<26;i++){const a=R()*Math.PI*2,rr=Math.sqrt(R())*82;g.beginFill(C.mud,.055+R()*.055).drawEllipse(Math.cos(a)*rr,Math.sin(a)*rr*.62,8+R()*19,3+R()*7).endFill()}}
else if(o.type==='berry_patch'){const fruit=Math.max(0,o.state?.ediblePortions||0),count=o.state?.exhausted?4:11;for(let i=0;i<count;i++){const x=(R()-.5)*100,y=(R()-.5)*58,s=(o.state?.exhausted?7:11)+R()*8;g.beginFill(o.state?.exhausted?C.leafDry:C.leaf,.97).drawCircle(x,y,s).endFill();if(i<fruit*2)g.beginFill(C.berry,.95).drawCircle(x+(R()-.5)*11,y+(R()-.5)*10,3).endFill()}}
else if(o.type==='fallen_tree'){const len=(o.geometry?.lengthM||4.8)*27,wc=wetWood(o);g.lineStyle(23,C.woodDark,.98).moveTo(-len/2,0).lineTo(len/2,0);g.lineStyle(16,wc,.98).moveTo(-len/2,0).lineTo(len/2,0);g.lineStyle(2,shade(wc,.18),.4).moveTo(-len/2+8,-3).lineTo(len/2-8,-3);if(!o.resolution?.componentsInstantiated)for(let i=0;i<4;i++){const x=-len*.34+i*len*.22,d=i%2?-1:1;g.lineStyle(7,wc,.95).moveTo(x,0).lineTo(x+d*(22+R()*24),d*(18+R()*21))}c.rotation=((o.geometry?.orientationDeg||0)-90)*Math.PI/180}
else if(o.type==='stone_field'){for(let i=0;i<20;i++){const a=R()*Math.PI*2,rr=Math.sqrt(R())*76,x=Math.cos(a)*rr,y=Math.sin(a)*rr*.55,s=5+R()*10;g.beginFill(i%2?C.rock:C.rock2,.97).drawEllipse(x,y,s,s*.7).endFill()}}
else if(o.type==='clay_bank'){g.beginFill(mix(C.clay,C.mud,.18),.88).drawEllipse(0,0,80,41).endFill();for(let i=0;i<14;i++)g.beginFill(i%2?0xc58b66:0x76503c,.18+R()*.12).drawEllipse((R()-.5)*114,(R()-.5)*50,5+R()*12,2+R()*5).endFill()}
else if(o.type==='reed_marsh'){for(let i=0;i<52;i++){const x=(R()-.5)*112,y=(R()-.5)*86,h=21+R()*40;g.lineStyle(2,C.reed,.9).moveTo(x,y+9).lineTo(x+(R()-.5)*5,y-h);if(i%3===0)g.beginFill(0x81643d,.82).drawEllipse(x,y-h,2,6).endFill()}}
else if(o.type==='frontier'){for(let i=0;i<15;i++){const x=(R()-.5)*210,y=(R()-.5)*220,r=35+R()*70;g.beginFill(0xd7ddd5,.018+R()*.018).drawCircle(x,y,r).endFill()}}
else if(o.type==='branch_shelter'){g.beginFill(0x5b4330,.96).moveTo(-48,27).lineTo(0,-45).lineTo(50,27).lineTo(34,27).lineTo(0,-23).lineTo(-29,27).closePath().endFill();g.lineStyle(3,0x936f49,.85).moveTo(-42,25).lineTo(0,-42).lineTo(43,25)}
else if(o.type==='camp_fire'){const glow=new PIXI.Graphics();glow.beginFill(C.fire2,.13).drawCircle(0,0,64).endFill();c.addChild(glow);g.beginFill(C.woodDark,.98).drawRoundedRect(-25,10,50,7,3).endFill();const f=new PIXI.Graphics();f.beginFill(C.fire,.98).drawPolygon([-11,12,0,-27,11,12]).endFill();f.beginFill(C.fire2,.92).drawPolygon([-6,9,0,-13,6,9]).endFill();f.name='flame';c.addChild(f)}
else if(o.type==='drying_rack'){g.lineStyle(6,C.wood,.96).moveTo(-34,22).lineTo(-23,-24).moveTo(34,22).lineTo(23,-24).moveTo(-30,-9).lineTo(30,-9);for(let i=-18;i<=18;i+=9)g.lineStyle(2,0x927955,.84).moveTo(i,-9).lineTo(i,16)}
else if(o.type==='animal_tracks'){const clarity=clamp(Number(o.state?.clarity??.72),.08,1);g.alpha=.32+.58*clarity;for(let i=0;i<8;i++){const x=i*11-37,y=(i%2?5:-5)+i*2;g.beginFill(0x261c16,.65).drawEllipse(x,y,4.5,6.5).endFill()}}
else return;c.addChildAt(g,0);selectable(c,o);if(!['camp_area','frontier'].includes(o.type))label(c,o.label,o.type==='fallen_tree'?42:38);objects.addChild(c)}
function drawComponent(o){const p=wp(o.position),c=new PIXI.Container();c.position.set(p.x,p.y);c.zIndex=p.y+2;const g=new PIXI.Graphics();if(o.type==='branch')g.lineStyle(6,wetWood(o),.98).moveTo(-17,0).lineTo(17,0);else if(o.type==='rock')g.beginFill(C.rock,.97).drawEllipse(0,0,10,7).endFill();else if(o.type==='berry_bush')g.beginFill(C.leaf,.97).drawCircle(0,0,13).endFill();else if(o.type==='clay_deposit')g.beginFill(C.clay,.92).drawEllipse(0,0,14,8).endFill();else if(o.type==='reed_stand')for(let i=-10;i<=10;i+=4)g.lineStyle(2,C.reed,.92).moveTo(i,9).lineTo(i+(i%3),-20-Math.abs(i));else return;c.addChild(g);selectable(c,o);objects.addChild(c)}
function drawArtifact(a){const p=wp(a.coordinates||{x:50,y:50}),c=new PIXI.Container();c.position.set(p.x+12,p.y-10);c.zIndex=p.y+6;const g=new PIXI.Graphics(),t=a.type||'';if(t.includes('ClayVessel')){g.lineStyle(2,0xd7a984,.9).beginFill(0x9d6b4e,.96).drawEllipse(0,3,10,12).endFill()}else if(t.includes('sharpStone'))g.beginFill(0xa4ada6,.97).drawPolygon([-10,8,0,-11,10,7]).endFill();else if(t.includes('Pole'))g.lineStyle(5,C.wood,.97).moveTo(-18,10).lineTo(18,-10);else if(t.includes('cordage'))g.lineStyle(3,0xb8a069,.92).drawCircle(0,0,10);else g.beginFill(0xd5c58c,.92).drawCircle(0,0,6).endFill();c.addChild(g);selectable(c,a,'artifact');artifacts.addChild(c)}
function heartbeat(){if(!current)return 1;const t=current.meta?.lastAdvancedAt?new Date(current.meta.lastAdvancedAt).getTime():Date.now(),period=(current.meta?.heartbeatMinutes||5)*60000;return clamp((Date.now()-t)/period,0,1)}
function phase(a){const plan=a.activeAction,p=heartbeat();if(!plan?.phases?.length)return{phase:'idle',label:'Between actions',x:a.coordinates?.x??50,y:a.coordinates?.y??50};const ph=plan.phases.find(x=>p>=x.start&&p<x.end)||plan.phases.at(-1),from=plan.from||a.coordinates,to=plan.to||a.coordinates;let x=to.x,y=to.y;if(plan.moving){const tr=plan.phases.find(x=>x.id==='travel');if(tr&&p<tr.start){x=from.x;y=from.y}else if(tr&&p<tr.end){const q=clamp((p-tr.start)/(tr.end-tr.start),0,1);x=from.x+(to.x-from.x)*q;y=from.y+(to.y-from.y)*q}}return{phase:ph.id,label:ph.label,x,y}}
function makeAgent(a,i){const c=new PIXI.Container();c.zIndex=999;const shadow=new PIXI.Graphics();shadow.beginFill(C.shadow,.3).drawEllipse(0,19,22,8).endFill();const legs=new PIXI.Graphics();legs.lineStyle(6,0x29302c,1).moveTo(-6,8).lineTo(-8,22).moveTo(6,8).lineTo(8,22);const body=new PIXI.Graphics();body.beginFill(i?C.ivo:C.mara).drawRoundedRect(-13,-11,26,32,8).endFill();const head=new PIXI.Graphics();head.beginFill(i?C.skinB:C.skinA).drawCircle(0,-22,10).endFill();const arm=new PIXI.Graphics();arm.lineStyle(5,i?0x5a5d85:0x577762,1).moveTo(9,-1).lineTo(18,9);const name=new PIXI.Text(a.name,{fontFamily:'Arial',fontSize:14,fontWeight:'700',fill:0xf4f8f1,stroke:0x07100a,strokeThickness:4});name.anchor.set(.5);name.y=-46;const action=new PIXI.Text('',{fontFamily:'Arial',fontSize:10,fill:0xd4dfd1,stroke:0x07100a,strokeThickness:3});action.anchor.set(.5);action.y=37;c.addChild(shadow,legs,body,head,arm,name,action);c.eventMode='static';c.cursor='pointer';c.on('pointertap',e=>{e.stopPropagation();showSelection(c);openInspector(a,'agent')});c._p={legs,body,head,arm,action};agentLayer.addChild(c);agents.set(a.id,c);return c}
function renderAgents(){if(!current)return;for(const [id,c] of agents)if(!current.agents.some(a=>a.id===id)){c.destroy({children:true});agents.delete(id)}current.agents.forEach((a,i)=>{let c=agents.get(a.id);if(!c)c=makeAgent(a,i);c._data=a})}
function tick(delta){if(!current)return;const t=performance.now()/1000;current.agents.forEach((a,i)=>{const c=agents.get(a.id);if(!c)return;const s=phase(a),p=wp(s),q=c._p;c.position.set(p.x,p.y);c.zIndex=p.y+20;q.action.text=s.phase==='travel'?'walking':s.phase==='interact'?(a.currentAction||'working').toLowerCase().slice(0,20):s.phase==='resolve'?'finishing':'';const talk=/talk/i.test(a.currentAction||a.mind?.intent||''),rest=/rest/i.test(a.currentAction||a.mind?.intent||'');q.body.rotation=0;q.head.y=0;q.legs.rotation=0;q.arm.rotation=0;if(s.phase==='travel'){q.legs.rotation=Math.sin(t*9+i)*.2;q.body.y=Math.sin(t*9+i)*1.4;q.arm.rotation=-Math.sin(t*9+i)*.17}else if(rest){q.legs.rotation=.38;q.body.rotation=-.2;q.body.y=8;q.head.y=6;q.arm.rotation=.5}else if(s.phase==='interact'){q.arm.rotation=Math.sin(t*6+i)*.38;q.body.y=Math.sin(t*5+i)*.9}if(talk&&s.phase!=='travel')q.action.text='talking'});animateWorld(t,delta);updateCamera(false)}
function animateWorld(t,delta){for(const c of objects.children){const f=c.getChildByName?.('flame');if(f){f.scale.y=.86+Math.sin(t*8)*.15;f.rotation=Math.sin(t*5)*.07}}for(const g of waterGlints){const pts=g._pts,s=(g._seed+Math.floor(t*.45))%(pts.length-1),q=(Math.sin(t*.8+g._seed)+1)/2,a=pts[s],b=pts[s+1];g.position.set(a.x+(b.x-a.x)*q,a.y+(b.y-a.y)*q)}for(const d of screenFx.children){if(d._rain){d.y+=d._speed*delta;d.x-=d._speed*.22*delta;if(d.y>app.screen.height+20){d.y=-20;d.x=Math.random()*app.screen.width}}}if(camera.mode==='free'&&!gesture&&pointers.size===0&&(Math.abs(camera.vx)>.02||Math.abs(camera.vy)>.02)){camera.x+=camera.vx;camera.y+=camera.vy;camera.vx*=.9;camera.vy*=.9}}
function drawScreenFx(){screenFx.removeChildren().forEach(d=>d.destroy({children:true}));if(!current)return;const f=current.worldModel.fields||{},prec=f.precipitation?.global||0;if(prec>0){for(let i=0;i<Math.round(24+prec*34);i++){const g=new PIXI.Graphics();g.lineStyle(1,0xd7ecee,.10+Math.random()*.12).moveTo(0,0).lineTo(-3,9+Math.random()*7);g.x=Math.random()*app.screen.width;g.y=Math.random()*app.screen.height;g._speed=5+Math.random()*7;g._rain=true;screenFx.addChild(g)}}const light=f.light?.global??.5,dark=clamp(.33-light*.32,0,.3);if(dark>.01){const g=new PIXI.Graphics();g.beginFill(0x071019,dark).drawRect(0,0,app.screen.width,app.screen.height).endFill();g.eventMode='none';screenFx.addChild(g)}}
function zoomAt(point,next){const old=camera.scale,w=screenToWorld(point,old);camera.scale=clamp(next,MIN,MAX);camera.x=w.x-(point.x-app.screen.width/2)/camera.scale;camera.y=w.y-(point.y-app.screen.height/2)/camera.scale;camera.mode='free';camera.manualUntil=Date.now()+30000;syncButtons();updateCamera(true)}
function wireCamera(){const canvas=app.view;canvas.style.touchAction='none';const resetGesture=()=>{if(pointers.size===1){const [p]=pointers.values();gesture={type:'pan',start:{...p},cx:camera.x,cy:camera.y,last:{...p},lastTime:performance.now()}}else if(pointers.size>=2){const [a,b]=[...pointers.values()];const mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};gesture={type:'pinch',startDist:dist(a,b),startScale:camera.scale,anchor:screenToWorld(mid),mid}}else gesture=null};canvas.addEventListener('pointerdown',e=>{const p=screenPoint(e);pointers.set(e.pointerId,p);canvas.setPointerCapture?.(e.pointerId);resetGesture()});canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const p=screenPoint(e);pointers.set(e.pointerId,p);if(pointers.size>=2){const [a,b]=[...pointers.values()],mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2},d=dist(a,b);if(gesture?.type!=='pinch')resetGesture();const next=clamp(gesture.startScale*(d/Math.max(20,gesture.startDist)),MIN,MAX);camera.scale=next;camera.x=gesture.anchor.x-(mid.x-app.screen.width/2)/next;camera.y=gesture.anchor.y-(mid.y-app.screen.height/2)/next;camera.mode='free';camera.manualUntil=Date.now()+30000;camera.vx=camera.vy=0;syncButtons();updateCamera(true)}else if(gesture?.type==='pan'){const now=performance.now(),dx=p.x-gesture.start.x,dy=p.y-gesture.start.y;camera.x=gesture.cx-dx/camera.scale;camera.y=gesture.cy-dy/camera.scale;const dt=Math.max(8,now-gesture.lastTime);camera.vx=-(p.x-gesture.last.x)/camera.scale*(16/dt);camera.vy=-(p.y-gesture.last.y)/camera.scale*(16/dt);gesture.last={...p};gesture.lastTime=now;camera.mode='free';camera.manualUntil=Date.now()+30000;syncButtons();updateCamera(true)}});const end=e=>{const p=screenPoint(e),wasSingle=pointers.size===1;pointers.delete(e.pointerId);if(wasSingle&&gesture?.type==='pan'&&dist(p,gesture.start)<10){const now=Date.now();if(now-lastTap.t<320&&dist(p,lastTap)<32){zoomAt(p,camera.scale*1.55);lastTap.t=0}else lastTap={t:now,x:p.x,y:p.y}}resetGesture()};canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('wheel',e=>{e.preventDefault();zoomAt(screenPoint(e),camera.scale*Math.exp(-e.deltaY*.001))},{passive:false});app.stage.eventMode='static';app.stage.hitArea=app.screen;app.stage.on('pointertap',()=>{$('#inspector')?.classList.remove('open');if(selectionRing){selectionRing.destroy();selectionRing=null}})}
function activityTarget(){if(!current)return{x:W*.55,y:W*.64};const top=current.liveThreads?.[0];let a=top?.agentIds?.length?current.agents.find(x=>x.id===top.agentIds[0]):null;if(!a)a=current.agents.find(x=>x.activeAction?.moving)||current.agents.find(x=>x.activeAction?.physicalProposal)||current.agents[0];return wp(phase(a))}
function frameActivity(force=true){const t=activityTarget();camera.x=t.x;camera.y=t.y;camera.scale=innerWidth<651?1.28:1.05;camera.mode='auto';camera.manualUntil=0;camera.vx=camera.vy=0;syncButtons();updateCamera(force)}
function focusAgent(id){const a=current?.agents?.find(a=>a.id===id);if(!a)return;const p=wp(phase(a));camera.x=p.x;camera.y=p.y;camera.scale=Math.max(camera.scale,innerWidth<651?1.45:1.2);camera.mode=id;camera.manualUntil=0;camera.vx=camera.vy=0;syncButtons();updateCamera(true)}
function updateCamera(force){if(!root||!app)return;let target={x:camera.x,y:camera.y};if(camera.mode==='auto'&&Date.now()>camera.manualUntil)target=activityTarget();else if(camera.mode.startsWith('agent-')){const a=current?.agents?.find(a=>a.id===camera.mode);if(a)target=wp(phase(a))}const s=force?1:.065;camera.x+=(target.x-camera.x)*s;camera.y+=(target.y-camera.y)*s;root.scale.set(camera.scale);root.position.set(app.screen.width/2-camera.x*camera.scale,app.screen.height/2-camera.y*camera.scale)}
function wireUI(){document.querySelectorAll('[data-camera]').forEach(b=>b.addEventListener('click',()=>{const m=b.dataset.camera;if(m==='auto')frameActivity(true);else focusAgent(m)}));$('#zoomIn')?.addEventListener('click',()=>zoomAt({x:app.screen.width/2,y:app.screen.height/2},camera.scale*1.22));$('#zoomOut')?.addEventListener('click',()=>zoomAt({x:app.screen.width/2,y:app.screen.height/2},camera.scale/1.22));$('#fitWorld')?.addEventListener('click',()=>frameActivity(true));$('#closeInspector')?.addEventListener('click',()=>$('#inspector').classList.remove('open'));$('.threadTop')?.addEventListener('click',()=>$('.threadPanel')?.classList.toggle('expanded'))}
function syncButtons(){document.querySelectorAll('[data-camera]').forEach(b=>b.classList.toggle('active',b.dataset.camera===camera.mode))}
function renderUI(){const s=$('#worldStatus');if(s)s.innerHTML=`<strong>● OBJECT WORLD · ${esc(current.version||'?')}</strong><span>Day ${current.day} · ${String(current.hour).padStart(2,'0')}:00 · ${Math.round(current.temperature)}°F · ${esc(current.weather)}</span>`;const list=current.liveThreads||[],th=$('#threads');if(th){th.innerHTML=list.length?list.map(t=>`<article class="thread ${t.urgency>=85?'urgent':t.urgency>=60?'high':''}"><b>${esc(t.title)}</b><p>${esc(t.summary)}</p><small>${esc(t.kind)} · urgency ${t.urgency}</small></article>`).join(''):'<article class="thread"><b>Quiet stretch</b><p>No high-signal unresolved thread right now.</p></article>';$('#threadCount').textContent=`${list.length} active thread${list.length===1?'':'s'}`}updateFocus()}
function updateFocus(){let a=camera.mode.startsWith('agent-')?current.agents.find(x=>x.id===camera.mode):null;if(!a){const top=current.liveThreads?.[0];a=(top?.agentIds?.length&&current.agents.find(x=>x.id===top.agentIds[0]))||current.agents[0]}if(!a)return;const s=phase(a);$('#focusCard').innerHTML=`<div class="focusInner"><small>${esc(s.label).toUpperCase()} · ${esc(a.position).toUpperCase()}</small><strong>${esc(a.name)} — ${esc(a.mind?.currentGoal||a.currentAction||'Responding to the world')}</strong><p>${esc(a.mind?.intent||a.currentAction||'')}</p></div>`}
function flatten(o,p=''){const out=[];for(const[k,v]of Object.entries(o||{})){if(v==null)continue;const key=p?`${p}.${k}`:k;if(typeof v==='object'&&!Array.isArray(v))out.push(...flatten(v,key));else out.push([key,Array.isArray(v)?v.join(', '):String(v)])}return out}
function openInspector(d,k){const p=$('#inspector');if(!p)return;$('#inspectType').textContent=k==='agent'?'AUTONOMOUS AGENT':k==='artifact'?'PERSISTENT ARTIFACT':'CANONICAL WORLD OBJECT';$('#inspectTitle').textContent=d.name||d.label||d.id;$('#inspectBody').innerHTML=k==='agent'?agentInspector(d):k==='artifact'?artifactInspector(d):objectInspector(d);p.classList.add('open')}
function objectInspector(o){const phys=Object.entries(o.physical||{}).filter(([,v])=>v===true).map(([k])=>k),props=[['ID',o.id],['Type',o.type],['Zone',o.zone],['Resolution',o.resolution?.level||'—'],['Parent',o.parentId||'independent'],['Position',`${o.position?.x??'?'}, ${o.position?.y??'?'}`]],mat=flatten(o.material||{}).slice(0,7),st=flatten(o.state||{}).slice(0,7);return `<div class="kv">${props.map(([k,v])=>`<span>${esc(k)}</span><b>${esc(v)}</b>`).join('')}</div><div class="pillRow">${phys.map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</div>${mat.length?`<div class="kv">${mat.map(([k,v])=>`<span>${esc(k)}</span><b>${esc(v)}</b>`).join('')}</div>`:''}${st.length?`<div class="kv">${st.map(([k,v])=>`<span>state.${esc(k)}</span><b>${esc(v)}</b>`).join('')}</div>`:''}<div class="historyList"><h3>OBJECT HISTORY</h3>${(o.history||[]).slice(-5).reverse().map(h=>`<div class="historyItem">D${h.day} ${String(h.hour).padStart(2,'0')}:00 · ${esc(h.detail||h.type)}</div>`).join('')||'<div class="historyItem">No recorded object-specific events yet.</div>'}</div>`}
function agentInspector(a){const n=a.needs||{};return `<div class="kv"><span>ID</span><b>${esc(a.id)}</b><span>Location</span><b>${esc(a.position)}</b><span>Hydration</span><b>${Math.round(n.hydration||0)}%</b><span>Satiety</span><b>${Math.round(n.hunger||0)}%</b><span>Energy</span><b>${Math.round(n.energy||0)}%</b><span>Warmth</span><b>${Math.round(n.warmth||0)}%</b><span>Goal</span><b>${esc(a.mind?.currentGoal||'—')}</b><span>Intent</span><b>${esc(a.mind?.intent||a.currentAction||'—')}</b></div>`}
function artifactInspector(a){return `<div class="kv"><span>ID</span><b>${esc(a.id)}</b><span>Type</span><b>${esc(a.type)}</b><span>Status</span><b>${esc(a.status)}</b><span>Carrier</span><b>${esc(a.carrierId||'none')}</b><span>Created</span><b>Day ${a.created?.day??'?'} · ${String(a.created?.hour??0).padStart(2,'0')}:00</b></div>`}
init().catch(e=>{console.error(e);const l=$('#loading');if(l)l.innerHTML=`<div class="loadingBox"><div class="loadingMark">!</div><strong>Renderer failed</strong><p>${esc(e.message||e)}</p></div>`})
})();