import seed from './seed.mjs';
import {prepare,step,applyEvent} from './elapsed.mjs';
let world,last,revision=0,queue=Promise.resolve(),db,rate=6,fault=null;
const serial=fn=>{const p=queue.then(fn);queue=p.catch(()=>{});return p;};
async function database(){return new Promise((resolve,reject)=>{const request=indexedDB.open('farm-isolated-elapsed-preview-v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('state');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function saved(){return new Promise((resolve,reject)=>{const req=db.transaction('state').objectStore('state').get('world');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function persist(){return new Promise((resolve,reject)=>{const tx=db.transaction('state','readwrite');tx.objectStore('state').put(world,'world');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
async function initialize(){db=await database();world=await saved()||prepare(await seed());last=Date.now();setInterval(()=>serial(async()=>{if(fault)return;const now=Date.now(),elapsed=Math.min(2000,Math.max(0,now-last));last=now;let rest=elapsed/1000*rate;while(rest>1e-8){const dt=Math.min(6,rest);await step(world,dt,{wallTime:now,fallbackReason:'browser_preview_no_provider'});rest-=dt;}revision++;await persist();}).catch(e=>{fault=e.message;self.postMessage({fault});}),1000);}
function snapshot(){const w=structuredClone(world),now=Date.now();w.runtime={execution:'elapsed-only',environment:'browser-preview',serverTime:now,start:last,end:last+3000,nextUpdateAt:now+1000,revision,status:fault?'error':'running',error:fault,decisionSource:'fallback',rate,computedThrough:last,futureFrames:0};return w;}
self.onmessage=e=>serial(async()=>{try{if(!world)await initialize();if(e.data.event){if(e.data.event.type==='rate'){if(![6,24].includes(e.data.event.value))throw Error('Unsupported clock speed');rate=e.data.event.value;}else{applyEvent(world,e.data.event);await persist();}}self.postMessage({id:e.data.id,world:snapshot()});}catch(error){self.postMessage({id:e.data.id,error:error.message});}});
