import {Miniflare,convertV4MiniflareOptions} from '../cloudflare/node_modules/miniflare/dist/src/index.js';
import {build} from '../cloudflare/node_modules/esbuild/lib/main.js';
import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const temp=await fs.mkdtemp(path.join(os.tmpdir(),'elapsed-live-'));
await build({entryPoints:[new URL('./worker.mjs',import.meta.url).pathname],bundle:true,format:'esm',platform:'browser',external:['cloudflare:workers'],outfile:path.join(temp,'worker.mjs')});
const options={workers:[{name:'live-test',modules:true,modulesRoot:temp,scriptPath:path.join(temp,'worker.mjs'),compatibilityDate:'2026-09-01',durableObjects:{LIVE_PREVIEW:{className:'LivePreviewWorld',useSQLite:true}},bindings:{PREVIEW_ADMIN_KEY:'test-only'}}]};
const create=()=>new Miniflare({...convertV4MiniflareOptions(options),resourcePersistencePath:path.join(temp,'storage')});let mf=create();
const read=async()=>{const r=await mf.dispatchFetch('https://test.invalid/state');assert.equal(r.status,200);return r.json();};
try{const a=await read();assert.equal(a.runtime.futureFrames,0);await new Promise(r=>setTimeout(r,4000));const b=await read();assert(b.meta.tickNumber>a.meta.tickNumber,'alarm advances without visitors');assert(b.runtime.computedThrough<=b.runtime.serverTime,'no computed future');const ids=b.agents.map(a=>a.id);await mf.dispose();mf=create();const c=await read();assert(c.meta.tickNumber>=b.meta.tickNumber);assert.deepEqual(c.agents.map(a=>a.id),ids);const denied=await mf.dispatchFetch('https://test.invalid/event',{method:'POST',body:JSON.stringify({type:'rain'})});assert.equal(denied.status,401);const event=await mf.dispatchFetch('https://test.invalid/event',{method:'POST',headers:{Authorization:'Bearer test-only'},body:JSON.stringify({type:'rain'})});assert.equal(event.status,200);assert.equal((await event.json()).weather,'rain');console.log('PASS real workerd: unattended alarms, no future states, persisted restart, authenticated live event');}finally{await mf.dispose();await fs.rm(temp,{recursive:true,force:true});}
