import{knows,knowsClay,knowsReeds,knowsTracks,knowsGameTrail,knowsTubers}from'./core.js';
import{ensureWorldModel,worldObjectForZone,findWorldObject,activeWorldObjects,objectSnapshot}from'./world-model.js';
export const PHYSICAL_VERBS=['move','inspect','search','follow','strike','cut','shape','bind','twist','heat','place','combine','dig','test'];
export const PHYSICAL_CONFIGURATIONS=['none','straight','pointed','hollow','twisted','bound','raised','wrapped'];
const sameZone=(p,q)=>p===q||(p==='meadow'&&['berries','stones'].includes(q))||(p==='forest'&&q==='log')||(p==='edge'&&q==='reeds')||(p==='creek'&&q==='clay');
const propTokens=o=>{const x=[];for(const[k,v]of Object.entries(o?.physical||{}))if(v===true)x.push(k);for(const[k,v]of Object.entries(o?.material||{}))if(v===true)x.push(k);return[...new Set(x)]};
export function deriveSupports({kind='world',physical={},properties=[]}={}){const p=new Set([...properties,...Object.entries(physical).filter(([,v])=>v===true).map(([k])=>k)]),out=new Set(['inspect']);if(p.has('navigable')||kind==='place')out.add('move');if(p.has('navigable')||p.has('harvestable')||p.has('biological')||p.has('wetland'))out.add('search');if(p.has('tracks')||p.has('directionalSign')){out.add('follow');out.add('search');out.add('test')}if(p.has('wood')){for(const v of ['cut','shape','bind','heat','place','combine','test'])out.add(v)}if(p.has('stone')||p.has('hard')||p.has('impact')){for(const v of ['strike','cut','bind','place','combine','test'])out.add(v)}if(p.has('clay')||p.has('plastic')||p.has('moldable')){for(const v of ['shape','heat','combine','place','test'])out.add(v)}if(p.has('reeds')||p.has('fibrous')||p.has('flexible')||p.has('tension-bearing')){for(const v of ['twist','bind','combine','place','test'])out.add(v)}if(p.has('fire')||p.has('heat')){out.add('heat');out.add('place');out.add('test')}if(p.has('underground')||p.has('tuber'))out.add('dig');if(p.has('carryable')){out.add('place');out.add('combine');out.add('test')}return[...out]}
const O=(id,label,kind,position,quantity,properties,extra={})=>{const physical=extra.physical||{};return{id,label,kind,position,quantity,properties,supports:extra.supports||deriveSupports({kind,physical,properties}),...extra}};
function knownZones(a){const x=['camp','creek','berries','log','stones','edge'];if(knowsClay(a))x.push('clay');if(knowsReeds(a))x.push('reeds');return x}
function placeObject(w,a,zone){const obj=worldObjectForZone(w,zone);if(!obj)return null;const local=sameZone(a.position,zone);return O(`place:${zone}`,obj.label,'place',zone,1,propTokens(obj),{worldObjectId:obj.id,worldObject:objectSnapshot(obj),physical:obj.physical,supports:local?deriveSupports({kind:'place',physical:obj.physical,properties:propTokens(obj)}):['move']})}
function localProjection(o,id,label,q,props=[],extra={}){return O(id,label,'world',o.zone,q,[...new Set([...propTokens(o),...props])],{worldObjectId:o.id,worldObject:objectSnapshot(o),physical:o.physical,...extra})}
export function buildAffordanceView(w,a){ensureWorldModel(w);const o=[];for(const zone of knownZones(a)){const place=placeObject(w,a,zone);if(place)o.push(place)}
 const creek=findWorldObject(w,'OBJ-CREEK-001'),berries=findWorldObject(w,'OBJ-BERRIES-001'),tree=findWorldObject(w,'OBJ-TREE-001'),stones=findWorldObject(w,'OBJ-STONES-001'),clay=findWorldObject(w,'OBJ-CLAY-001'),reeds=findWorldObject(w,'OBJ-REEDS-001');
 if(creek?.state?.potable!==false&&sameZone(a.position,'creek'))o.push(localProjection(creek,'creek_water','creek water',1,['water','liquid','potable','wet'],{supports:['inspect','test']}));
 if(berries&&sameZone(a.position,'berries')&&(berries.state.ediblePortions||0)>0)o.push(localProjection(berries,'wild_berries','wild berries',berries.state.ediblePortions,['food','edible','perishable'],{supports:['inspect','search','test']}));
 if(tree&&sameZone(a.position,'log')){if((tree.state.availableDryBranches||0)>0)o.push(localProjection(tree,'dry_branches','dry branches',tree.state.availableDryBranches,['wood','dry','rigid','flammable','cuttable']));if((tree.state.availableWetBranches||0)>0)o.push(localProjection(tree,'wet_branches','wet branches',tree.state.availableWetBranches,['wood','wet','rigid','flammable','cuttable']))}
 if(stones&&sameZone(a.position,'stones')&&(stones.state.looseStones||0)>0)o.push(localProjection(stones,'loose_stones','loose stones',stones.state.looseStones,['stone','hard','fracturable','impact']));
 if(clay&&knowsClay(a)&&sameZone(a.position,'clay')&&(clay.state.harvestableUnits||0)>0)o.push(localProjection(clay,'clay_bank_material','sticky creek-bank clay',clay.state.harvestableUnits,['clay','wet','plastic','moldable']));
 if(reeds&&knowsReeds(a)&&sameZone(a.position,'reeds')&&(reeds.state.harvestableStalkBundles||0)>0)o.push(localProjection(reeds,'reed_stalks','flexible reed stalks',reeds.state.harvestableStalkBundles,['reeds','fibrous','flexible','cuttable']));
 const tracks=findWorldObject(w,'OBJ-TRACKS-001');if(tracks&&tracks.state.active&&knowsTracks(a)&&sameZone(a.position,tracks.zone))o.push(O('animal_tracks',tracks.label,'feature',tracks.zone,1,propTokens(tracks),{worldObjectId:tracks.id,worldObject:objectSnapshot(tracks),physical:tracks.physical}));if(w.ecology.gameTrail&&knowsGameTrail(a)&&sameZone(a.position,'reeds'))o.push(O('game_trail','narrow game trail','feature','reeds',1,['trail','animal-sign','directionalSign']));if(w.ecology.smallGame>0&&sameZone(a.position,'reeds'))o.push(O('small_game','small wild animal','creature','reeds',w.ecology.smallGame,['animal','mobile','meat-source','alert']));if(w.ecology.tuberPatch&&knowsTubers(a)&&sameZone(a.position,'reeds'))o.push(O('tuber_patch','patch of underground tubers','world','reeds',w.ecology.tubers,['tuber','underground','unknown-edibility']));const fire=findWorldObject(w,'OBJ-FIRE-001');if(fire?.state?.active&&sameZone(a.position,'camp'))o.push(O('camp_fire',fire.label,'structure','camp',1,propTokens(fire),{worldObjectId:fire.id,worldObject:objectSnapshot(fire),physical:fire.physical}));
 for(const entity of activeWorldObjects(w).filter(x=>x.parentId&&sameZone(a.position,x.zone))){const props=propTokens(entity);o.push(O(`entity:${entity.id}`,entity.label,'entity',entity.zone,1,props,{worldObjectId:entity.id,worldObject:objectSnapshot(entity),physical:entity.physical}))}
 const c=(k,id,label,p)=>{if((a.inventory[k]||0)>0)o.push(O(id,label,'carried','carried',a.inventory[k],p,{inventoryKey:k}))};c('berries','carried_berries','carried berries',['food','edible','perishable']);c('dryWood','carried_dry_branch','carried dry branch',['wood','dry','rigid','flammable']);c('wetWood','carried_wet_branch','carried wet branch',['wood','wet','rigid','flammable']);c('stones','carried_stone','carried stone',['stone','hard','fracturable','impact']);c('sharpStone','sharp_stone','sharp stone flake',['stone','sharp','hard','cutting-edge']);c('clay','clay_lump','lump of wet clay',['clay','wet','plastic','moldable']);c('reeds','carried_reeds','carried reeds',['reeds','fibrous','flexible']);c('cordage','cordage','twisted cordage',['cordage','fibrous','flexible','tension-bearing']);c('woodPole','wood_pole','straight wooden pole',['wood','dry','rigid','long']);c('pointedPole','pointed_pole','pointed wooden pole',['wood','dry','rigid','long','pointed']);c('boundSharpTool','bound_sharp_tool','sharp stone bound to a wooden pole',['wood','stone','sharp','bound','long']);c('rawClayVessel','raw_clay_vessel','unfired hollow clay form',['clay','hollow','fragile','wet']);c('firedVessel','fired_vessel','fired clay vessel',['clay','hollow','hard','water-resistant']);c('rawMeat','raw_meat','raw meat',['meat','raw','food','perishable']);c('cookedMeat','cooked_meat','cooked meat',['meat','cooked','food','edible']);c('tubers','carried_tuber','dug marsh tuber',['tuber','root','unknown-edibility']);return{verbs:[...PHYSICAL_VERBS],configurations:[...PHYSICAL_CONFIGURATIONS],objects:o,worldModelVersion:w.worldModel.version,environmentFields:w.worldModel.fields}}
export function normalizePhysicalProposal(p){return p&&typeof p==='object'?{verb:String(p.verb||''),primaryObjectId:String(p.primaryObjectId||''),secondaryObjectId:String(p.secondaryObjectId||'none'),configuration:String(p.configuration||'none'),purpose:String(p.purpose||'').slice(0,180)}:null}
export function validatePhysicalProposal(context,proposal){const p=normalizePhysicalProposal(proposal);if(!p||!PHYSICAL_VERBS.includes(p.verb)||!PHYSICAL_CONFIGURATIONS.includes(p.configuration))return{ok:false,reason:'invalid primitive or configuration',proposal:p};const m=new Map(context.affordances.objects.map(x=>[x.id,x])),primary=m.get(p.primaryObjectId),secondary=p.secondaryObjectId==='none'?null:m.get(p.secondaryObjectId);if(!primary)return{ok:false,reason:'primary object is not accessible',proposal:p};if(p.secondaryObjectId!=='none'&&!secondary)return{ok:false,reason:'secondary object is not accessible',proposal:p};if(!primary.supports.includes(p.verb))return{ok:false,reason:`${primary.label} does not support ${p.verb}`,proposal:p};if(p.verb==='move'&&primary.kind!=='place')return{ok:false,reason:'move requires a known place',proposal:p};return{ok:true,proposal:p,primary,secondary}}