const TRACKED={sharpStone:{label:'sharp stone flake',glyph:'◆'},rawClayVessel:{label:'unfired clay vessel',glyph:'◡'},firedVessel:{label:'fired clay vessel',glyph:'◉'},cordage:{label:'twisted cordage',glyph:'∿'},woodPole:{label:'worked wooden pole',glyph:'╱'},pointedPole:{label:'pointed wooden pole',glyph:'↗'},boundSharpTool:{label:'bound composite tool',glyph:'⚒'}};
const now=(w)=>({day:w.day,hour:w.hour});
function init(w){w.artifacts||=[];w.seq||={};w.seq.artifact??=1;return w.artifacts}
const activeFor=(w,a,key)=>init(w).filter(x=>x.inventoryKey===key&&x.status==='active'&&x.carrierId===a.id);
export function createArtifact(w,a,key,{label=null,glyph=null,properties=[],provenance=null,status='active',position=null,carrierId=a?.id||null}={}){init(w);const base=TRACKED[key]||{};const art={id:`ART-${String(w.seq.artifact++).padStart(4,'0')}`,type:key,inventoryKey:key,label:label||base.label||key,glyph:glyph||base.glyph||'•',properties:[...properties],status,carrierId,position:position||a?.position||'camp',coordinates:null,created:now(w),provenance:provenance||null,ended:null};w.artifacts.push(art);return art}
export function consumeArtifact(w,a,key,{status='transformed',provenance=null}={}){const art=activeFor(w,a,key)[0];if(!art)return null;art.status=status;art.ended=now(w);if(provenance)art.provenance=provenance;return art}
export function leaveRemnant(w,a,type,label,glyph,properties=[],provenance=null){return createArtifact(w,a,type,{label,glyph,properties,provenance,status:'remnant',position:a.position,carrierId:null})}
export function ensureArtifactLedger(w){init(w);for(const a of w.agents||[]){for(const key of Object.keys(TRACKED)){const qty=Math.max(0,Math.floor(a.inventory?.[key]||0));const active=activeFor(w,a,key);if(active.length<qty){for(let i=active.length;i<qty;i++)createArtifact(w,a,key,{properties:['legacy-or-untracked-origin'],provenance:'backfilled from canonical inventory'})}else if(active.length>qty){for(const art of active.slice(qty)){art.status='consumed';art.ended=now(w);art.provenance=art.provenance||'reconciled against canonical inventory'}}}}return w.artifacts}
export function syncArtifactLocations(w,coordForPosition){ensureArtifactLedger(w);for(const art of w.artifacts){if(art.status==='active'&&art.carrierId){const a=w.agents.find(x=>x.id===art.carrierId);if(a){art.position=a.position;art.coordinates=coordForPosition(a.position)}}else if(!art.coordinates)art.coordinates=coordForPosition(art.position)}w.artifacts=w.artifacts.slice(-120);return w.artifacts}
export const artifactDefinition=key=>TRACKED[key]||null;