export const WORLD_VERSION='0.5';
export const PHYSICS_VERSION='affordance-0.5';
export const clamp=(n,min=0,max=100)=>Math.max(min,Math.min(max,n));
export const pairKey=(a,b)=>[a,b].sort().join('|');
export const clone=x=>JSON.parse(JSON.stringify(x));
export const noise=(day,hour,salt=0)=>{const x=Math.sin((day*24+hour+salt)*12.9898)*43758.5453;return x-Math.floor(x)};
export const hasTag=(m,t)=>m.tags?.includes(t);
export const INVENTORY_DEFAULTS={berries:0,dryWood:0,wetWood:0,stones:0,clay:0,reeds:0,sharpStone:0,rawClayVessel:0,firedVessel:0,cordage:0,woodPole:0,pointedPole:0,boundSharpTool:0,rawMeat:0,cookedMeat:0,tubers:0};

function makeAgent(id,name,position,needs,traits){return{id,name,position,needs,inventory:{...INVENTORY_DEFAULTS},memories:[],beliefs:{},traits,skills:{},experiments:{},affordanceAttempts:{},currentAction:'Waking up',mind:{brainMode:'fallback',currentGoal:'Understand the immediate situation',intent:'Observe and survive',confidence:0,decisionSummary:'',model:null,recentActions:[],lastReferencedMemoryIds:[],lastPhysicalProposal:null}}}
export function createWorld(){const mara=makeAgent('agent-mara','Mara','meadow',{hydration:66,hunger:72,energy:82,warmth:62},{curiosity:.78,cooperation:.68,caution:.54});const ivo=makeAgent('agent-ivo','Ivo','forest',{hydration:74,hunger:68,energy:78,warmth:58},{curiosity:.62,cooperation:.77,caution:.46});return{version:WORLD_VERSION,day:1,hour:6,temperature:49,weather:'clear',resources:{berries:18,dryWood:12,wetWood:6,stones:24,clay:10,reeds:14,creekWater:true},structures:{shelter:false,fire:false,cache:false,dryingRack:false},discovered:{creek:true,berries:true,fallenLog:true,stoneField:true,east:false,west:false,clayBank:false,reedBed:false},ecology:{animalTracks:false,gameTrail:false,smallGame:0,tuberPatch:false,tubers:8,tubersEdible:true},agents:[mara,ivo],relationships:{[pairKey(mara.id,ivo.id)]:{trust:34,familiarity:12,affinity:50,lastInteraction:null,sharedMemories:0,techniquesShared:0}},discoveries:[],history:[],dna:[],seq:{event:1,memory:1,decision:1,discovery:1,physical:1},meta:{canonical:true,lastAdvancedAt:null,tickNumber:0,mindMode:'fallback',aiDecisions:0,fallbackDecisions:0,physicsVersion:PHYSICS_VERSION}}}

export function migrateWorld(w){
 if(!w.agents){const old=w.agent||makeAgent('agent-mara','Mara','meadow',{hydration:66,hunger:72,energy:82,warmth:62},{curiosity:.78,cooperation:.68,caution:.54});w.agents=[old,makeAgent('agent-ivo','Ivo','forest',{hydration:74,hunger:68,energy:78,warmth:58},{curiosity:.62,cooperation:.77,caution:.46})];delete w.agent}
 w.version=WORLD_VERSION;w.resources||={};Object.assign(w.resources,{berries:w.resources.berries??18,dryWood:w.resources.dryWood??12,wetWood:w.resources.wetWood??6,stones:w.resources.stones??24,clay:w.resources.clay??10,reeds:w.resources.reeds??14,creekWater:w.resources.creekWater??true});
 w.structures||={};Object.assign(w.structures,{shelter:w.structures.shelter??false,fire:w.structures.fire??false,cache:w.structures.cache??false,dryingRack:w.structures.dryingRack??false});
 w.discovered||={};Object.assign(w.discovered,{creek:w.discovered.creek??true,berries:w.discovered.berries??true,fallenLog:w.discovered.fallenLog??true,stoneField:w.discovered.stoneField??true,east:w.discovered.east??false,west:w.discovered.west??false,clayBank:w.discovered.clayBank??false,reedBed:w.discovered.reedBed??false});
 w.ecology||={};Object.assign(w.ecology,{animalTracks:w.ecology.animalTracks??!!w.discovered.reedBed,gameTrail:w.ecology.gameTrail??false,smallGame:w.ecology.smallGame??0,tuberPatch:w.ecology.tuberPatch??false,tubers:w.ecology.tubers??8,tubersEdible:w.ecology.tubersEdible??true});
 w.relationships||={[pairKey('agent-mara','agent-ivo')]:{trust:34,familiarity:12,affinity:50,lastInteraction:null,sharedMemories:0,techniquesShared:0}};const rel=w.relationships[pairKey('agent-mara','agent-ivo')];if(rel)Object.assign(rel,{trust:rel.trust??34,familiarity:rel.familiarity??12,affinity:rel.affinity??50,sharedMemories:rel.sharedMemories??0,techniquesShared:rel.techniquesShared??0});
 w.discoveries||=[];w.history||=[];w.dna||=[];w.seq||={};for(const k of ['event','memory','decision','discovery','physical'])w.seq[k]??=1;w.meta||={};Object.assign(w.meta,{canonical:w.meta.canonical??true,tickNumber:w.meta.tickNumber??0,aiDecisions:w.meta.aiDecisions??0,fallbackDecisions:w.meta.fallbackDecisions??0,mindMode:w.meta.mindMode??'fallback',physicsVersion:PHYSICS_VERSION});
 for(const a of w.agents){a.traits||={curiosity:.6,cooperation:.6,caution:.5};a.memories||=[];a.beliefs||={};a.skills||={};a.experiments||={};a.affordanceAttempts||={};a.inventory||={};for(const[k,v]of Object.entries(INVENTORY_DEFAULTS))a.inventory[k]??=v;a.mind||={};Object.assign(a.mind,{brainMode:a.mind.brainMode??'fallback',currentGoal:a.mind.currentGoal??'Stay alive and understand the world',intent:a.mind.intent??'Respond to current conditions',confidence:a.mind.confidence??0,decisionSummary:a.mind.decisionSummary??'',model:a.mind.model??null,recentActions:a.mind.recentActions??[],lastReferencedMemoryIds:a.mind.lastReferencedMemoryIds??[],lastPhysicalProposal:a.mind.lastPhysicalProposal??null})}
 return w;
}
export function addEvent(w,type,title,detail,meta={}){w.history.unshift({id:`E-${String(w.seq.event++).padStart(5,'0')}`,day:w.day,hour:w.hour,type,title,detail,...meta});w.history=w.history.slice(0,900)}
export function remember(w,a,text,{importance=5,tags=[],source=null,confidence=.75}={}){const hit=a.memories.find(m=>m.text===text);if(hit){hit.confidence=clamp((hit.confidence??.7)+.04,0,1);hit.lastSeen=`${w.day}:${w.hour}`;return hit}const prefix=a.id.endsWith('ivo')?'I':'M',m={id:`M-${prefix}${String(w.seq.memory++).padStart(3,'0')}`,text,importance,tags,source:source||`experience:${w.day}-${w.hour}`,confidence,lastSeen:`${w.day}:${w.hour}`};a.memories.unshift(m);a.memories=a.memories.slice(0,120);addEvent(w,'learn',`${a.name} formed a memory`,text,{agentId:a.id,memoryId:m.id});return m}
export const otherAgent=(w,a)=>w.agents.find(x=>x.id!==a.id);
export const relationship=(w,a,b)=>w.relationships[pairKey(a.id,b.id)];
export const knows=(a,skill)=>(a.skills?.[skill]||0)>0;
export const knowledgeText=a=>a.memories.map(m=>`${m.text} ${(m.tags||[]).join(' ')}`).join(' ').toLowerCase();
export const knowsClay=a=>a.position==='clay'||/\bclay\b/.test(knowledgeText(a))||a.inventory.clay>0||a.inventory.rawClayVessel>0||a.inventory.firedVessel>0||knows(a,'clay-shaping')||knows(a,'fired-clay');
export const knowsReeds=a=>a.position==='reeds'||/\breeds?\b|cordage|marsh/.test(knowledgeText(a))||a.inventory.reeds>0||a.inventory.cordage>0||knows(a,'cordage');
export const knowsTracks=a=>/animal tracks|tracks|game trail/.test(knowledgeText(a))||knows(a,'track-reading');
export const knowsGameTrail=a=>/game trail/.test(knowledgeText(a));
export const knowsTubers=a=>/tuber|root patch|underground roots/.test(knowledgeText(a));
export function recordDiscovery(w,a,key,title,detail,effect){let d=w.discoveries.find(x=>x.key===key);if(!d){d={id:`DISC-${String(w.seq.discovery++).padStart(3,'0')}`,key,title,detail,effect,firstAgentId:a.id,firstAgentName:a.name,day:w.day,hour:w.hour};w.discoveries.unshift(d);addEvent(w,'discovery',`WORLD DISCOVERY · ${title}`,`${a.name} is the first to discover: ${detail}`,{agentId:a.id,discoveryId:d.id,discoveryKey:key})}return d}
export function learnSkill(w,a,key,level,memoryText,discovery=null){a.skills[key]=Math.max(a.skills[key]||0,level);if(memoryText)remember(w,a,memoryText,{importance:9,tags:['technique',key],confidence:.94});if(discovery)recordDiscovery(w,a,key,discovery.title,discovery.detail,discovery.effect)}
export const spendEnergy=(a,n)=>a.needs.energy=clamp(a.needs.energy-n);
export const invConsume=(a,k,n=1)=>{if((a.inventory[k]||0)<n)return false;a.inventory[k]-=n;return true};
export function updateWeather(w){const x=noise(w.day,w.hour,9);if([5,12,18].includes(w.hour))w.weather=x>.72?'rain':x>.46?'cloudy':'clear';const daylight=Math.sin(((w.hour-6)/24)*Math.PI*2);w.temperature=Math.round(52+10*daylight-(w.weather==='rain'?7:w.weather==='cloudy'?3:0));if(w.weather==='rain'){w.resources.wetWood=Math.min(14,w.resources.wetWood+1);for(const a of w.agents)a.needs.warmth=clamp(a.needs.warmth-3)}}
function regrow(w){w.resources.berries=Math.min(20,w.resources.berries+2);w.resources.reeds=Math.min(18,w.resources.reeds+1);if(noise(w.day,0,188)>.35)w.resources.dryWood=Math.min(12,w.resources.dryWood+1);if(w.ecology.tuberPatch)w.ecology.tubers=Math.min(10,w.ecology.tubers+1)}
function environmentTick(w){for(const a of w.agents){const n=a.needs;n.hydration=clamp(n.hydration-(a.inventory.firedVessel>0?5.5:6.5));n.hunger=clamp(n.hunger-4.2);n.energy=clamp(n.energy-2.8);const cold=w.temperature<50?5:w.temperature<58?2:0;n.warmth=clamp(n.warmth-cold+(w.structures.fire?5:0)+(w.structures.shelter&&a.position==='camp'?2:0))}const chance=w.weather==='clear'?.56:w.weather==='cloudy'?.24:.04;if(w.resources.wetWood>0&&noise(w.day,w.hour,78)<chance){w.resources.wetWood--;w.resources.dryWood++;addEvent(w,'world','A fallen branch dried','Moving air and weather dried exposed wood enough to make it useful as dry fuel.')}if(w.structures.dryingRack&&w.resources.wetWood>0&&noise(w.day,w.hour,79)<.62){w.resources.wetWood--;w.resources.dryWood++}if(w.structures.fire&&noise(w.day,w.hour,44)>.76){w.structures.fire=false;addEvent(w,'world','The fire fades','Without more fuel, the small fire burns down to ash.')}if(w.ecology.gameTrail&&w.ecology.smallGame<2&&noise(w.day,w.hour,117)>.82)w.ecology.smallGame++}
export function finishHour(w){environmentTick(w);w.hour++;if(w.hour>=24){w.hour=0;w.day++;regrow(w)}updateWeather(w)}