// Living Basin ecology is intentionally simulation-first; model escalation remains optional.
// v1.0: persistent wild behavior, habitat/time/weather weighting, realistic avoidance, and substrate-aware sign.
export const ECOLOGY_VERSION='living-basin-1.0.0';

const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
const unit=(w,salt)=>{const x=Math.sin((w.day*24+w.hour+hash(salt)%10000)*12.9898)*43758.5453;return x-Math.floor(x)};
const dist=(a,b)=>Math.hypot((a?.x||0)-(b?.x||0),(a?.y||0)-(b?.y||0));
const bound=p=>({x:clamp(p.x,1,99),y:clamp(p.y,1,99)});
const point=(x,y)=>({x,y});
const creekPoints=[[2,18.5],[12,21],[27,18],[43,22],[58,19],[72,23],[86,21],[98,23.7]].map(([x,y])=>({x,y}));
const habitat={
 deer:[point(18,34),point(26,42),point(41,40),point(57,39),point(74,36),point(84,31)],
 rabbit:[point(28,30),point(38,34),point(52,31),point(68,34),point(78,28),point(20,27)],
 bear:[point(8,46),point(12,55),point(24,52),point(82,49),point(91,42),point(88,56)]
};
const SPECIES={
 deer:{step:3.35,fearRadius:17,panicRadius:7.5,traceChance:.26,traceSize:1},
 rabbit:{step:2.2,fearRadius:10,panicRadius:4.2,traceChance:.11,traceSize:.48},
 bear:{step:3.05,fearRadius:24,panicRadius:9,traceChance:.34,traceSize:1.45},
 fish:{step:4.2,fearRadius:0,panicRadius:0,traceChance:0,traceSize:0}
};
function animal(id,species,label,x,y,extra={}){return{id,species,label,position:{x,y},previousPosition:{x,y},target:{x,y},home:{x,y},activity:'rest',behavior:'calm',behaviorUntil:0,behaviorGoal:{x,y},fear:0,needs:{energy:80,hunger:72,thirst:75},active:true,ageClass:'adult',history:[],ai:{eligible:true,mode:'simulation',calls:0,lastDecisionAt:null},movement:{from:{x,y},to:{x,y},worldDay:1,worldHour:6},...extra}}
function ensureArrays(e){e.events||=[];e.traces||=[];e.eventCooldowns||={}}
function nearestCreek(p){return creekPoints.reduce((best,q)=>dist(p,q)<dist(p,best)?q:best,creekPoints[0])}
function worldStamp(w){return w.day*24+w.hour}
function segmentOfDay(w){if(w.hour>=5&&w.hour<=8)return'dawn';if(w.hour>=17&&w.hour<=21)return'dusk';if(w.hour>=9&&w.hour<17)return'day';return'night'}
function activityDrive(w,a){const seg=segmentOfDay(w),rain=w.weather==='rain';let d=.5;if(a.species==='deer')d=seg==='dawn'||seg==='dusk'?1:seg==='night'?.52:.34;else if(a.species==='rabbit')d=seg==='dawn'||seg==='dusk'?1:seg==='night'?.56:.18;else if(a.species==='bear')d=seg==='dawn'||seg==='dusk'?.78:seg==='night'?.56:.46;else if(a.species==='fish')d=seg==='dawn'||seg==='dusk'?.9:.62;if(rain)d*=a.species==='rabbit'?.45:a.species==='deer'?.76:.9;return clamp(d,0,1)}
function chooseHabitat(w,a){const all=habitat[a.species]||[a.home||point(50,40)],home=a.home||a.position;let choices=all;if(a.species==='rabbit')choices=[...all].sort((x,y)=>dist(x,home)-dist(y,home)).slice(0,2);else if(a.species==='deer')choices=[...all].sort((x,y)=>dist(x,home)-dist(y,home)).slice(0,4);const period=Math.floor(worldStamp(w)/6),i=hash(`${a.id}:${period}:habitat`)%choices.length;return choices[i]}
function creekTarget(w,a){return creekPoints[hash(`${a.id}:${Math.floor(worldStamp(w)/5)}:creek`)%creekPoints.length]}
function fleeFrom(a,threat,amount){const dx=a.position.x-threat.x,dy=a.position.y-threat.y,m=Math.hypot(dx,dy)||1;return bound({x:a.position.x+dx/m*amount,y:a.position.y+dy/m*amount})}
function jitter(w,a,p,scale=3,salt='jitter'){const ax=unit(w,`${a.id}:${salt}:x`)*2-1,ay=unit(w,`${a.id}:${salt}:y`)*2-1;return bound({x:p.x+ax*scale,y:p.y+ay*scale})}
function moveToward(from,goal,maxStep){const dx=goal.x-from.x,dy=goal.y-from.y,d=Math.hypot(dx,dy);if(!d||d<=maxStep)return bound(goal);return bound({x:from.x+dx/d*maxStep,y:from.y+dy/d*maxStep})}
function hold(w,a,{activity,behavior,goal=a.position,hours=2}){a.activity=activity;a.behavior=behavior;a.behaviorGoal=bound(goal);a.behaviorUntil=worldStamp(w)+Math.max(1,hours);return a.behaviorGoal}
function nearestAgent(w,a){let best=null,d=Infinity;for(const p of w.agents||[]){const c=p.coordinates;if(!c)continue;const q=dist(a.position,c);if(q<d){d=q;best={agent:p,distance:q,position:c}}}return best}
function ecoEvent(w,{kind,title,detail,animal=null,agent=null,importance=4,cooldown=5,key=null}){const e=w.ecologySystem,stamp=worldStamp(w),coolKey=key||`${kind}:${animal?.id||''}:${agent?.id||''}`;if((e.eventCooldowns[coolKey]??-999)+cooldown>stamp)return null;e.eventCooldowns[coolKey]=stamp;const out={id:`ECO-${w.day}-${String(w.hour).padStart(2,'0')}-${String(e.events.length+1).padStart(3,'0')}`,day:w.day,hour:w.hour,kind,title,detail,importance,animalId:animal?.id||null,species:animal?.species||null,agentId:agent?.id||null};e.events.unshift(out);e.events=e.events.slice(0,60);return out}
function heading(from,to){return Math.atan2(to.y-from.y,to.x-from.x)}
function traceSuitability(w,p){const d=dist(p,nearestCreek(p));let s=d<2.5?.95:d<5?.68:d<9?.35:.12;if(w.weather==='rain')s*=d<7?1.22:.7;return clamp(s,.05,1)}
function addTrace(w,a,from,to){const s=SPECIES[a.species],moved=dist(from,to);if(!s?.traceChance||a.species==='fish'||moved<.85)return;const suitability=traceSuitability(w,from),panic=a.activity==='flee'?1.35:1,chance=Math.min(.72,s.traceChance*suitability*panic);if(unit(w,`${a.id}:trace:${a.history.length}`)>chance)return;const e=w.ecologySystem,m={x:from.x+(to.x-from.x)*.58,y:from.y+(to.y-from.y)*.58},id=`TRACE-${a.id}-${w.day}-${String(w.hour).padStart(2,'0')}`;if(e.traces.some(x=>x.id===id))return;const creekD=dist(m,nearestCreek(m)),substrate=creekD<4?'mud':creekD<8?'soft-ground':'forest-floor';e.traces.unshift({id,sourceId:a.id,species:a.species,label:`${a.species} tracks`,position:bound(m),heading:heading(from,to),clarity:substrate==='mud'?.9:substrate==='soft-ground'?.72:.55,size:s.traceSize,substrate,ageHours:0,created:{day:w.day,hour:w.hour},active:true});e.traces=e.traces.slice(0,24)}
function ageTraces(w){const rain=w.weather==='rain';for(const t of w.ecologySystem.traces){t.ageHours=(t.ageHours||0)+1;const decay=rain?.15:t.substrate==='mud'?.026:t.substrate==='soft-ground'?.042:.065;t.clarity=clamp((t.clarity??.7)-decay,0,1);if(t.ageHours>18||t.clarity<.18)t.active=false}w.ecologySystem.traces=w.ecologySystem.traces.filter(x=>x.active).slice(0,24)}
function updateNeeds(a){const moving=['move','flee','swim'].includes(a.activity);if(a.species==='rabbit'){a.needs.hunger=clamp(a.needs.hunger-1.55);a.needs.thirst=clamp(a.needs.thirst-.35)}else if(a.species==='bear'){a.needs.hunger=clamp(a.needs.hunger-1.8);a.needs.thirst=clamp(a.needs.thirst-1.05)}else if(a.species==='deer'){a.needs.hunger=clamp(a.needs.hunger-1.65);a.needs.thirst=clamp(a.needs.thirst-1.25)}else{a.needs.hunger=clamp(a.needs.hunger-.8);a.needs.thirst=clamp(a.needs.thirst-.5)}a.needs.energy=clamp(a.needs.energy-(a.activity==='flee'?5:moving?1.8:.5));if(a.activity==='rest'||a.activity==='hide')a.needs.energy=clamp(a.needs.energy+4.5)}
function persistRoutine(w,a){if((a.behaviorUntil||0)<=worldStamp(w)||!a.behaviorGoal)return null;if(a.activity==='rest'||a.activity==='hide'||a.activity==='freeze'||a.activity==='drink')return jitter(w,a,a.position,a.species==='rabbit'?.25:.55,'persist-still');if(a.activity==='graze'||a.activity==='forage')return jitter(w,a,a.behaviorGoal,a.species==='rabbit'?1.2:2.3,'persist-feed');return a.behaviorGoal}
function decideAnimal(w,a){
 const s=SPECIES[a.species]||SPECIES.deer,near=nearestAgent(w,a),drive=activityDrive(w,a);a.fear=clamp(a.fear-(a.species==='bear'?5:9));
 if(a.species==='fish'){const t=creekTarget(w,a);return hold(w,a,{activity:'swim',behavior:'schooling',goal:jitter(w,a,t,1.5,'fish'),hours:2})}
 // Wild animals should usually avoid people; only close approaches become encounter events.
 if(near&&near.distance<s.panicRadius){a.fear=100;const goal=fleeFrom(a,near.position,a.species==='rabbit'?11:a.species==='bear'?13:10);hold(w,a,{activity:'flee',behavior:a.species==='bear'?'withdrawing':'startled',goal,hours:a.species==='rabbit'?1:2});if(a.species!=='rabbit'||unit(w,`${a.id}:panic-event`)<.3)ecoEvent(w,{kind:a.species==='bear'?'bear-encounter':'wildlife-flight',title:a.species==='bear'?`${a.label} withdraws from ${near.agent.name}`:`${a.label} bolts from ${near.agent.name}`,detail:`${a.label} reacted at ${near.distance.toFixed(1)} world units and moved toward cover.`,animal:a,agent:near.agent,importance:a.species==='bear'?9:5,cooldown:a.species==='bear'?18:8});return goal}
 if(near&&near.distance<s.fearRadius){a.fear=Math.max(a.fear,a.species==='bear'?65:58);if(a.species==='rabbit'&&unit(w,`${a.id}:freeze`)<.72)return hold(w,a,{activity:'freeze',behavior:'motionless in cover',goal:a.position,hours:1});const goal=fleeFrom(a,near.position,a.species==='bear'?9:a.species==='deer'?5:6);return hold(w,a,{activity:'move',behavior:a.species==='bear'?'avoiding people':'wary',goal,hours:2})}
 // Cottontails generally obtain much of their water from vegetation; do not make them march to open water every time thirst drops.
 if(a.species!=='rabbit'&&a.needs.thirst<38){const water=nearestCreek(a.position);if(dist(a.position,water)<2.6){a.needs.thirst=clamp(a.needs.thirst+26);return hold(w,a,{activity:'drink',behavior:'drinking',goal:a.position,hours:1})}return hold(w,a,{activity:'move',behavior:'seeking water',goal:jitter(w,a,water,1,'water'),hours:2})}
 const persisted=persistRoutine(w,a);if(persisted)return persisted;
 const r=unit(w,`${a.id}:behavior`),home=a.home||a.position;
 if(a.needs.energy<36||drive<.24){const cover=a.species==='rabbit'?chooseHabitat(w,a):a.species==='deer'?chooseHabitat(w,a):home;return hold(w,a,{activity:a.species==='rabbit'?'hide':'rest',behavior:a.species==='rabbit'?'resting in cover':'resting',goal:jitter(w,a,cover,a.species==='rabbit'?.8:1.8,'rest'),hours:2+Math.floor(unit(w,`${a.id}:rest-hours`)*3)})}
 if(a.needs.hunger<48||r<.5+drive*.22){const food=chooseHabitat(w,a);a.needs.hunger=clamp(a.needs.hunger+(a.species==='bear'?6:7));return hold(w,a,{activity:a.species==='bear'?'forage':'graze',behavior:a.species==='bear'?'foraging':'feeding',goal:jitter(w,a,food,a.species==='rabbit'?1.4:a.species==='deer'?2.8:5,'feed'),hours:2+Math.floor(unit(w,`${a.id}:feed-hours`)*3)})}
 // Roaming is deliberately uncommon outside active periods. Rabbits stay tight to cover; bears range much farther.
 if(r<.62+drive*.26){const base=a.species==='rabbit'?chooseHabitat(w,a):a.species==='bear'?chooseHabitat(w,a):chooseHabitat(w,a),scale=a.species==='rabbit'?2.1:a.species==='bear'?7:4;return hold(w,a,{activity:'move',behavior:'roaming',goal:jitter(w,a,base,scale,'roam'),hours:2+Math.floor(unit(w,`${a.id}:roam-hours`)*2)})}
 return hold(w,a,{activity:a.species==='rabbit'?'hide':'rest',behavior:a.species==='rabbit'?'resting in cover':'resting',goal:jitter(w,a,home,a.species==='rabbit'?.7:1.5,'quiet'),hours:2})
}
function updateAmbient(w){const daylight=w.hour>=6&&w.hour<20?1:0,wet=w.weather==='rain'?1:0,twilight=(w.hour>=5&&w.hour<=8)||(w.hour>=18&&w.hour<=21);w.ecologySystem.ambient={birds:Math.round(clamp((daylight?55:12)+(twilight?28:0)-(wet?22:0)+unit(w,'birds')*18)),frogs:Math.round(clamp((!daylight?58:22)+(wet?26:0)+unit(w,'frogs')*14)),insects:Math.round(clamp((w.temperature-42)*1.9+(daylight?18:6)-(wet?8:0))),fishActivity:Math.round(clamp(42+(twilight?28:0)+(wet?14:0)+unit(w,'fish')*18)),seed:hash(`${w.day}:${w.hour}:${w.weather}`)}}
export function ensureEcology(w){
 w.settings||={};w.settings.ai||={};w.settings.ai.people||={};for(const a of w.agents||[])if(w.settings.ai.people[a.id]==null)w.settings.ai.people[a.id]=true;
 w.settings.ai.wildlife||={enabled:false,individuals:{}};w.settings.ai.usage||={track:true};
 w.ecologySystem||={version:ECOLOGY_VERSION,wildlife:[],ambient:{birds:0,frogs:0,insects:0,fishActivity:0},events:[],traces:[],eventCooldowns:{},lastAdvanced:null};
 w.ecologySystem.version=ECOLOGY_VERSION;w.ecologySystem.wildlife||=[];w.ecologySystem.ambient||={birds:0,frogs:0,insects:0,fishActivity:0};ensureArrays(w.ecologySystem);
 if(!w.ecologySystem.wildlife.length){w.ecologySystem.wildlife=[
  animal('W-DEER-001','deer','doe',24,37,{sex:'female'}),animal('W-DEER-002','deer','young buck',72,35,{sex:'male'}),
  animal('W-RABBIT-001','rabbit','cottontail',35,31),animal('W-RABBIT-002','rabbit','cottontail',62,33),animal('W-RABBIT-003','rabbit','cottontail',77,27),
  animal('W-BEAR-001','bear','black bear',91,50,{sex:'female',behavior:'wary'}),
  animal('W-FISH-001','fish','creek fish school',15,18.5,{ageClass:'school'}),animal('W-FISH-002','fish','creek fish school',67,23,{ageClass:'school'})
 ];}
 for(const x of w.ecologySystem.wildlife){x.previousPosition||={...x.position};x.target||={...x.position};x.home||={...x.position};x.behaviorGoal||={...x.target};x.behaviorUntil??=0;x.movement||={from:{...x.position},to:{...x.position},worldDay:w.day,worldHour:w.hour};x.ai||={eligible:true,mode:'simulation',calls:0,lastDecisionAt:null};x.history||=[];if(x.species==='fish'&&((x.position?.y||0)>50||(x.target?.y||0)>50||(x.movement?.to?.y||0)>50)){const q=creekPoints[hash(x.id)%creekPoints.length];x.position={...q};x.previousPosition={...q};x.target={...q};x.home={...q};x.behaviorGoal={...q};x.movement={from:{...q},to:{...q},goal:{...q},worldDay:w.day,worldHour:w.hour,speed:0};x.history.push({day:w.day,hour:w.hour,activity:'migration',behavior:'coordinate migration',from:null,to:{...q},goal:{...q}})}else if(x.behavior==='seeking water'&&(x.target?.y||0)>50){const q=nearestCreek(x.position);x.target={...q};x.behaviorGoal={...q};x.movement={...x.movement,to:{...x.position},goal:{...q}}}}
 updateAmbient(w);return w.ecologySystem;
}
export function advanceEcology(w){ensureEcology(w);ageTraces(w);for(const a of w.ecologySystem.wildlife){if(!a.active)continue;updateNeeds(a);const prevBehavior=a.behavior,from={...a.position},goal=decideAnimal(w,a),base=SPECIES[a.species]?.step||3;let mult=1;if(a.activity==='flee')mult=1.75;else if(['rest','hide','freeze','drink'].includes(a.activity))mult=.08;else if(a.activity==='graze'||a.activity==='forage')mult=.42;else if(a.species==='rabbit')mult=.68;const to=moveToward(from,goal,base*mult);a.previousPosition=from;a.target=goal;a.position=to;a.movement={from,to,goal,worldDay:w.day,worldHour:w.hour,speed:base*mult};addTrace(w,a,from,to);a.history.push({day:w.day,hour:w.hour,activity:a.activity,behavior:a.behavior,from,to,goal});if(a.history.length>48)a.history=a.history.slice(-48);if(prevBehavior!==a.behavior&&['feeding','foraging','resting'].includes(a.behavior)&&unit(w,`${a.id}:quiet-event`)<.07)ecoEvent(w,{kind:'wildlife-routine',title:`${a.label} is ${a.behavior}`,detail:`A routine wildlife behavior emerged from its needs, time of day and habitat.`,animal:a,importance:2,cooldown:18});a.ai.mode=(w.settings.ai.wildlife.individuals?.[a.id]??w.settings.ai.wildlife.enabled)?'eligible-ai':'simulation'}updateAmbient(w);w.ecologySystem.lastAdvanced={day:w.day,hour:w.hour};return w.ecologySystem}
function detectionRadius(w,x,radius){let r=radius;if(x.species==='rabbit')r=Math.min(r,['hide','freeze','rest'].includes(x.activity)?5.5:10);else if(x.species==='deer')r=Math.min(r,x.activity==='rest'?12:18);else if(x.species==='bear')r=Math.min(r,20);if(w.weather==='rain')r*=.82;return r}
export function visibleWildlifeForAgent(w,agent,radius=18){ensureEcology(w);const c=agent.coordinates;if(!c)return[];return w.ecologySystem.wildlife.filter(x=>x.active&&dist(c,x.position)<=detectionRadius(w,x,radius)).map(x=>({id:x.id,species:x.species,label:x.label,distance:Math.round(dist(c,x.position)*10)/10,behavior:x.behavior,activity:x.activity,fear:Math.round(x.fear)})).sort((a,b)=>a.distance-b.distance)}
export function visibleWildlifeTracesForAgent(w,agent,radius=12){ensureEcology(w);const c=agent.coordinates;if(!c)return[];return w.ecologySystem.traces.filter(x=>x.active&&(x.clarity??0)>=.32&&dist(c,x.position)<=radius).map(x=>({id:x.id,sourceId:x.sourceId,species:x.species,label:x.label,distance:Math.round(dist(c,x.position)*10)/10,clarity:Math.round((x.clarity||0)*100)/100,heading:x.heading,ageHours:x.ageHours,substrate:x.substrate||null})).sort((a,b)=>a.distance-b.distance)}
export function wildlifeAIEnabled(w,id=null){ensureEcology(w);if(id&&w.settings.ai.wildlife.individuals?.[id]!=null)return!!w.settings.ai.wildlife.individuals[id];return!!w.settings.ai.wildlife.enabled}
