import {recordPractice} from './craft-practice.js';
import{addEvent,remember,spendEnergy}from'./core.js';
import{validatePhysicalProposal}from'./affordances.js';
import{resolveWorldObject}from'./physical-world.js';
import{resolveMaterial}from'./physical-materials.js';
import{resolveEcology}from'./physical-ecology.js';
const key=p=>`${p.verb}:${p.primaryObjectId}:${p.secondaryObjectId}:${p.configuration}`;
export function resolvePhysicalAction(w,a,context,proposal,getLiveContext){const first=validatePhysicalProposal(context,proposal),pid=`P-${String(w.seq.physical++).padStart(5,'0')}`;if(!first.ok){const detail=`${a.name}'s attempted physical action could not begin: ${first.reason}.`;addEvent(w,'attempt','Physical attempt blocked',detail,{agentId:a.id,physicalId:pid,proposal:first.proposal});return{physicalId:pid,success:false,blocked:true,detail,proposal:first.proposal}}const live=validatePhysicalProposal(getLiveContext(),first.proposal);if(!live.ok){const detail=`${a.name} begins the attempt, but the needed object is no longer accessible.`;addEvent(w,'attempt','Physical attempt interrupted',detail,{agentId:a.id,physicalId:pid,proposal:first.proposal});return{physicalId:pid,success:false,conflict:true,detail,proposal:first.proposal}}const p=live.proposal,x=live.primary,y=live.secondary,k=key(p);a.affordanceAttempts[k]=(a.affordanceAttempts[k]||0)+1;const n=a.affordanceAttempts[k];spendEnergy(a,{move:3,inspect:2,search:7,follow:7,strike:6,cut:6,shape:5,bind:6,twist:5,heat:4,place:3,combine:5,dig:7,test:4}[p.verb]||4);let r={handled:false,success:false,detail:''};if(p.verb==='move'&&x.kind==='place'){a.position=x.position;r={handled:true,success:true,detail:`${a.name} moves to the ${x.label}.`}}if(!r.handled)r=resolveWorldObject(w,a,p,x,y,n);if(!r.handled)r=resolveEcology(w,a,p,x,y,n);if(!r.handled)r=resolveMaterial(w,a,p,x,y,n);if(!r.handled){r={handled:true,success:false,detail:`${a.name} tries to ${p.verb} ${x.label}${y?` with ${y.label}`:''}. No stable new effect emerges yet.`};remember(w,a,`Physical attempt ${n}: ${p.verb} ${x.label}${y?` with ${y.label}`:''} produced no stable effect.`,{importance:4,tags:['experiment','physical-attempt'],confidence:.64})}const practiceKey=p.verb==='follow'?'tracking':p.verb==='strike'&&x.id==='small_game'?'hunting':['cut','shape'].includes(p.verb)&&['carried_dry_branch','carried_wet_branch','wood_pole'].includes(x.id)?'woodworking':p.verb==='twist'?'fiberwork':p.verb==='bind'?'hafting':p.verb==='strike'&&x.id==='carried_stone'?'stoneworking':null;if(practiceKey&&r.handled)recordPractice(w,a,practiceKey,5,labelForPractice(p,x),r.success);const label=`${p.verb} ${x.label}${y?` + ${y.label}`:''}`;a.currentAction=label;const out={physicalId:pid,success:r.success,blocked:false,detail:r.detail,proposal:p,primary:x.id,secondary:y?.id||null,worldObjectId:r.worldObjectId||x.worldObjectId||null,resolvedComponents:r.resolvedComponents||[]};addEvent(w,r.success?'physical':'attempt',label,r.detail,{agentId:a.id,physicalId:pid,success:r.success,proposal:p,worldObjectId:out.worldObjectId});return out}
function labelForPractice(p,x){return p.verb+' '+x.id;}
