import{knows,knowsClay,knowsReeds,knowsTracks,knowsGameTrail}from'./core.js';
export const LOCATION_COORDS={camp:{x:64,y:34},creek:{x:48,y:19},berries:{x:29,y:31},log:{x:59,y:29},meadow:{x:43,y:31},edge:{x:78,y:42},forest:{x:14,y:38},stones:{x:73,y:24},clay:{x:86,y:21},reeds:{x:10,y:22}};
export const coordForPosition=p=>({...LOCATION_COORDS[p]||LOCATION_COORDS.meadow});
export function syncSpatial(w){w.spatial||={};w.spatial.locations=Object.fromEntries(Object.entries(LOCATION_COORDS).map(([id,c])=>[id,{id,...c}]));for(const a of w.agents){a.coordinates=coordForPosition(a.position);a.activeAction??=null}return w}
const distance=(a,b)=>Math.hypot((a.x||0)-(b.x||0),(a.y||0)-(b.y||0));
export function buildPlayback(w,a,{decisionId,label,actionId,from,to,outcome,physicalProposal=null}){const moving=distance(from,to)>2,phases=moving?[{id:'decide',label:'Deciding',start:0,end:.1},{id:'travel',label:'Traveling',start:.1,end:.58},{id:'interact',label:'Acting',start:.58,end:.86},{id:'resolve',label:'Resolving',start:.86,end:1}]:[{id:'decide',label:'Deciding',start:0,end:.12},{id:'interact',label:'Acting',start:.12,end:.82},{id:'resolve',label:'Resolving',start:.82,end:1}];a.activeAction={id:`A-${decisionId}`,decisionId,label,actionId,worldDay:w.day,worldHour:w.hour,from:{...from},to:{...to},target:{...to},moving,phases,outcome:{success:outcome?.success!==false,detail:outcome?.detail||''},physicalProposal};return a.activeAction}
const hoursSince=(w,stamp)=>{if(!stamp)return 999;const[d,h]=String(stamp).split(':').map(Number);return(w.day-d)*24+(w.hour-h)};
const thread=(id,title,urgency,summary,kind,agentIds=[],placeIds=[])=>({id,title,urgency,summary,kind,agentIds,placeIds});
export function deriveLiveThreads(w){const t=[],night=w.hour>=18||w.hour<6,minWarm=Math.min(...w.agents.map(a=>a.needs.warmth)),minEnergy=Math.min(...w.agents.map(a=>a.needs.energy)),minHydration=Math.min(...w.agents.map(a=>a.needs.hydration)),minSatiety=Math.min(...w.agents.map(a=>a.needs.hunger));if((night||w.temperature<45)&&!w.structures.fire&&minWarm<52)t.push(thread('cold-night','Cold night, no fire',95,`It is ${w.temperature}°F and the fire is out. The coldest agent is at ${Math.round(minWarm)}% warmth.`,'survival',w.agents.filter(a=>a.needs.warmth===minWarm).map(a=>a.id),['camp']));if(minEnergy<25){const a=w.agents.find(x=>x.needs.energy===minEnergy);t.push(thread('exhaustion',`${a.name} is running on fumes`,90,`${a.name}'s energy is ${Math.round(minEnergy)}%. Continuing strenuous work risks compounding the cold and hydration pressure.`,'survival',[a.id],[a.position]))}if(minHydration<35){const a=w.agents.find(x=>x.needs.hydration===minHydration);t.push(thread('dehydration',`${a.name} needs water`,92,`${a.name}'s hydration has fallen to ${Math.round(minHydration)}%. The creek remains the known reliable water source.`,'survival',[a.id],['creek']))}const carriedFood=w.agents.reduce((s,a)=>s+(a.inventory.berries||0)+(a.inventory.cookedMeat||0)+(a.inventory.tubers||0),0);if(minSatiety<38&&w.resources.berries+carriedFood<5)t.push(thread('food-pressure','Easy food is becoming scarce',84,`The lowest satiety is ${Math.round(minSatiety)}%, with only ${w.resources.berries+carriedFood} obvious food portions in or near the group.`,'survival',w.agents.map(a=>a.id),['berries']));if(w.ecology.animalTracks&&!w.ecology.gameTrail&&w.agents.some(knowsTracks))t.push(thread('tracks','Animal tracks remain unresolved',66,'At least one agent knows about the marsh tracks, but nobody has yet converted that sign into a reliable trail.','mystery',w.agents.filter(knowsTracks).map(a=>a.id),['reeds']));if(w.ecology.gameTrail&&w.ecology.smallGame===0)t.push(thread('game-trail','A game trail is known',61,'The trail is real, but no animal is currently in sight. Waiting, following or preparing may change that.','opportunity',w.agents.filter(knowsGameTrail).map(a=>a.id),['reeds']));for(const a of w.agents){if((a.inventory.rawClayVessel||0)>0&&!knows(a,'fired-clay'))t.push(thread(`clay-${a.id}`,`${a.name} has an unfired clay vessel`,56,'The shaped vessel persists, but its behavior under sustained heat is still unresolved.','experiment',[a.id],['camp']));const attempts=Object.entries(a.affordanceAttempts||{}).filter(([,n])=>n>0);if(attempts.length){const[k,n]=attempts.at(-1);t.push(thread(`attempt-${a.id}`,`${a.name} has an unresolved physical experiment`,42,`${n} attempt${n===1?'':'s'} at ${k.split(':').slice(0,2).join(' ')} have become part of ${a.name}'s experience.`,'experiment',[a.id],[a.position]))}}
const[a,b]=w.agents;if(a&&b){const asym=[];for(const skill of new Set([...Object.keys(a.skills||{}),...Object.keys(b.skills||{})]))if(knows(a,skill)!==knows(b,skill))asym.push(skill);if(asym.length)t.push(thread('knowledge-gap','Knowledge is unevenly distributed',48,`${asym.slice(0,3).join(', ')} ${asym.length===1?'is':'are'} known by only one agent. A future conversation could matter.`,'social',[a.id,b.id],[a.position,b.position]));const rel=w.relationships?.[[a.id,b.id].sort().join('|')];if(rel&&hoursSince(w,rel.lastInteraction)>14)t.push(thread('social-gap','Mara and Ivo have been apart for a while',34,`Their last recorded interaction was ${hoursSince(w,rel.lastInteraction)} world-hours ago.`,'social',[a.id,b.id],[a.position,b.position]))}
for(const a of w.agents){const i=a.inventory;if((i.sharpStone||0)>0&&((i.reeds||0)>=3||(i.cordage||0)>0)&&((i.dryWood||0)>0||(i.woodPole||0)>0||(i.pointedPole||0)>0))t.push(thread(`materials-${a.id}`,`${a.name} is carrying unusually complementary materials`,52,'Rigid material, a cutting edge, and flexible binding material are together. The world does not prescribe what to do with them.','opportunity',[a.id],[a.position]))}
w.liveThreads=t.sort((x,y)=>y.urgency-x.urgency).slice(0,6);return w.liveThreads}
export function updateSpectatorState(w){syncSpatial(w);deriveLiveThreads(w);return w}
