import {chromium} from '../character-preview/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const example=JSON.parse(await fs.readFile(new URL('./example.json',import.meta.url))),project={...example,id:'fixture-ivo-supply',name:'Ivo’s raised supply shelter',source:'ai',designer:'Ivo',model:'fixture-model',stockpileId:'fixture-stock'};
const frame={day:94,runtime:{createdAt:1790030005263,revision:19},settlement:{projects:[{...project,code:undefined}],stores:[{id:'fixture-stock',items:{dryWood:1,reeds:1}}]}};
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});await fs.mkdir('structure-workshop/evidence',{recursive:true});
try{
 for(const mobile of [false,true]){
  const name=mobile?'mobile':'desktop',context=await browser.newContext({viewport:mobile?{width:412,height:915}:{width:1440,height:1050},hasTouch:mobile,isMobile:mobile,acceptDownloads:true}),page=await context.newPage(),errors=[],requests=[];let blocked=false;
  page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  await context.route('https://chatgptfarm.kyle8824.workers.dev/**',route=>{requests.push({method:route.request().method,url:route.request().url()});const design=route.request().url().includes('/live/design/');return route.fulfill({status:blocked?503:200,contentType:'application/json',body:JSON.stringify(blocked?{code:'hosting_limit'}:design?{code:project.code}:frame)});});
  await page.goto('http://127.0.0.1:4178/structure-workshop/');await page.waitForFunction(()=>structureWorkshop.projectId==='fixture-ivo-supply');assert.equal(await page.locator('#graphics-error').isVisible(),false);assert.match(await page.locator('#rationale').innerText(),/raised timber/i);assert.match(await page.locator('#functions').innerText(),/storage/);const signature=await page.evaluate(()=>structureWorkshop.signature);
  await page.screenshot({path:`structure-workshop/evidence/${name}-design.png`,fullPage:true});
  await page.click('#tab-materials');assert.match(await page.locator('#materials').innerText(),/timber/i);await page.screenshot({path:`structure-workshop/evidence/${name}-materials.png`,fullPage:true});
  await page.click('#tab-appearance');await page.locator('[data-color="timber"]').evaluate(input=>{input.value='#315347';input.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal(await page.evaluate(()=>structureWorkshop.appearance.timber),'#315347');assert.equal(await page.evaluate(()=>structureWorkshop.signature),signature);await page.screenshot({path:`structure-workshop/evidence/${name}-appearance.png`,fullPage:true});
  const downloaded=page.waitForEvent('download');await page.click('#export');const download=await downloaded,file=await download.path(),look=JSON.parse(await fs.readFile(file));assert.equal(look.schema,'chatgptfarm-structure-look/1');assert.equal(look.appearance.timber,'#315347');assert(!('parts' in look));
  await page.click('#reset');assert.notEqual(await page.evaluate(()=>structureWorkshop.appearance.timber),'#315347');await page.setInputFiles('#look-file',{name:'appearance.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(look))});await page.waitForFunction(()=>structureWorkshop.appearance.timber==='#315347');assert.equal(await page.evaluate(()=>structureWorkshop.appearance.timber),'#315347');
  await page.setInputFiles('#look-file',{name:'wrong-design.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...look,projectId:'wrong'}))});await page.waitForFunction(()=>document.querySelector('#draft-status').textContent.includes('different physical design'));assert.equal(await page.evaluate(()=>structureWorkshop.signature),signature);
  await page.reload();await page.waitForFunction(()=>structureWorkshop.projectId==='fixture-ivo-supply');assert.equal(await page.evaluate(()=>structureWorkshop.appearance.timber),'#315347');
  await page.click('[data-stage="construction"]');assert.equal(await page.evaluate(()=>structureWorkshop.stage),'construction');await page.screenshot({path:`structure-workshop/evidence/${name}-progress.png`,fullPage:true});
  if(mobile){await page.locator('#stage').scrollIntoViewIfNeeded();const box=await page.locator('#stage').boundingBox(),cdp=await context.newCDPSession(page),cx=box.x+box.width*.43,cy=box.y+box.height*.45;const touch=(type,points)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(([x,y],id)=>({id,x,y,force:1}))}),before=await page.evaluate(()=>structureWorkshop);
   await touch('touchStart',[[cx-35,cy],[cx+35,cy]]);for(let i=1;i<=8;i++){const t=i/8,r=35+20*t,a=.45*t;await touch('touchMove',[[cx+10*t-Math.cos(a)*r,cy-Math.sin(a)*r],[cx+10*t+Math.cos(a)*r,cy+Math.sin(a)*r]]);}await touch('touchEnd',[]);const after=await page.evaluate(()=>structureWorkshop);assert.notDeepEqual(before.camera,after.camera);assert.equal(after.signature,signature);
  }
  await page.click('#tab-design');await page.locator('#program summary').click();await page.waitForFunction(()=>document.querySelector('#code').textContent.includes('function upright'));
  blocked=true;await page.click('#refresh');await page.waitForFunction(()=>document.querySelector('#connection').textContent.includes('Showing designs saved'));assert.match(await page.locator('#origin').innerText(),/SAVED WORLD DESIGN/);assert.equal(await page.evaluate(()=>structureWorkshop.projectId),'fixture-ivo-supply');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert(requests.every(r=>r.method==='GET'));assert.equal(requests.filter(r=>r.url.includes('/live/state')).length,3,'only open, reload and explicit refresh fetch world snapshots');assert.deepEqual(errors.filter(e=>!e.includes('503')),[]);await context.close();
 }
 const context=await browser.newContext({viewport:{width:412,height:915}}),page=await context.newPage();await context.route('https://chatgptfarm.kyle8824.workers.dev/**',r=>r.fulfill({status:503,contentType:'application/json',body:'{"code":"hosting_limit"}'}));await page.goto('http://127.0.0.1:4178/structure-workshop/');await page.waitForFunction(()=>document.querySelector('#connection').textContent.includes('Showing an example'));assert.match(await page.locator('#origin').innerText(),/NOT FROM THE LIVE WORLD/);await page.screenshot({path:'structure-workshop/evidence/mobile-quota-example.png',fullPage:true});await page.goto('http://127.0.0.1:4178/character-preview/');await page.waitForFunction(()=>window.previewMetrics);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'character workshop navigation stays within the mobile viewport');assert.equal(await page.locator('header a[href="/structure-workshop/"]').count(),1);await context.close();
}finally{await browser.close();}
console.log('PASS desktop/mobile real WebGL; catalog/rationale/resources; surface draft/export/import; geometry invariance; persisted look; combined touch; cached outage and explicit example; GET-only manual snapshots');
