// CI end-to-end regression test. This starts a real browser against a real
// workerd server: no route stubbing, invented snapshots or clock acceleration.
import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const base=process.env.VALLEY_URL||'http://127.0.0.1:4173';await fs.mkdir('realtime-qa',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const reports=[];
try{for(const [name,size]of [['desktop',{width:1440,height:960}],['mobile',{width:412,height:915}]]){
 const context=await browser.newContext({viewport:size,deviceScaleFactor:1,isMobile:name==='mobile',hasTouch:name==='mobile'}),page=await context.newPage(),errors=[],frames=[];page.on('pageerror',e=>{errors.push(e.message);console.error('BROWSER ERROR',e.message);});page.on('websocket',ws=>ws.on('framereceived',e=>{try{const m=JSON.parse(e.payload.toString());if(m.type==='state')frames.push(m);}catch{}}));
 await page.goto(base+'/live/',{waitUntil:'networkidle'});await page.screenshot({path:`realtime-qa/${name}-opening.png`});await page.getByText('Live world',{exact:true}).waitFor({timeout:30000});await page.waitForTimeout(3000);assert(frames.length>3,'multiple live WebSocket frames');assert(!(await page.locator('.hint').innerText()).includes('3D unavailable'),'3D renderer initialized');const first=frames[0];await page.screenshot({path:`realtime-qa/${name}.png`,fullPage:true});
 await page.locator('#agent-mara').click();await page.getByRole('dialog').filter({has:page.getByRole('heading',{name:'Mara'})}).waitFor();await page.getByRole('button',{name:'Carrying',exact:true}).click();await page.getByRole('button',{name:'Close inspector'}).click();await page.locator('#home').click();await page.getByRole('button',{name:'Open world journal'}).click();assert(await page.locator('#events .event').count()>0);await page.getByRole('button',{name:'Close journal'}).click();
 await page.waitForTimeout(12000);const last=frames.at(-1);assert(last.runtime.revision>first.runtime.revision+50,'server revisions advance');assert(frames.every(f=>f.runtime.computedThrough<=f.runtime.serverTime),'no future frames');assert(frames.every(f=>f.runtime.futureFrames===0));const clearance=Math.min(...frames.slice(15).map(f=>Math.hypot(f.agents[0].coordinates.x-f.agents[1].coordinates.x,f.agents[0].coordinates.y-f.agents[1].coordinates.y)));assert(clearance>=1.02,`server body clearance ${clearance}`);assert(last.agents.every(a=>Number.isFinite(a.motion?.facing)));assert(frames.some(f=>f.groundRecent?.length),'server records actually traversed ground');const moves=last.wildlife.map(a=>({id:a.id,distance:Math.hypot(a.position.x-first.wildlife.find(b=>b.id===a.id).position.x,a.position.y-first.wildlife.find(b=>b.id===a.id).position.y)}));assert(moves.some(m=>m.distance>.5),'actual wildlife positions change');
 const changes=last.agents.map(a=>({id:a.id,distance:Math.hypot(a.coordinates.x-first.agents.find(b=>b.id===a.id).coordinates.x,a.coordinates.y-first.agents.find(b=>b.id===a.id).coordinates.y),action:a.currentAction}));const maxMotion=Math.max(...frames.flatMap(f=>f.agents.map(a=>Math.hypot(a.coordinates.x-first.agents.find(b=>b.id===a.id).coordinates.x,a.coordinates.y-first.agents.find(b=>b.id===a.id).coordinates.y))));if(name==='desktop')assert(maxMotion>.1,'actual villager travel occurs');else assert(last.agents.some(a=>a.task?.phase==='work'||a.task?.phase==='travel'),'mobile shows actual ongoing tasks');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'no mobile overflow');assert.deepEqual(errors,[]);await page.screenshot({path:`realtime-qa/${name}-final.png`});reports.push({minimumSeparation:clearance,viewport:name,frames:frames.length,revision:[first.runtime.revision,last.runtime.revision],agents:changes,wildlife:moves,errors});await context.close();
 }
 const fallback=await chromium.launch({headless:true,args:['--no-sandbox','--disable-webgl']});try{const page=await fallback.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/live/');await page.getByText('Live world',{exact:true}).waitFor({timeout:30000});assert((await page.locator('.hint').innerText()).includes('3D unavailable'));await page.locator('#agent-mara').click();await page.getByRole('heading',{name:'Mara',exact:true}).waitFor();assert.deepEqual(errors,[]);reports.push({fallback:'WebGL disabled: live map, connection and inspector pass'});}finally{await fallback.close();}
 const a=await(await fetch(base+'/live/health')).json();assert.equal(a.viewers,0,'all browsers are closed');await new Promise(r=>setTimeout(r,6000));const b=await(await fetch(base+'/live/health')).json();assert(b.unattendedSteps>a.unattendedSteps+20,'world advances with zero viewers');assert(b.alarmCount>a.alarmCount,'independent alarms fire');reports.push({unattended:{before:a,after:b}});await fs.writeFile('realtime-qa/report.json',JSON.stringify(reports,null,2));console.log('PASS browser: desktop/mobile graphics, WebSocket frames, real villager and wildlife motion, inspector, journal, no console errors, zero-viewer progression.');
}finally{await fs.writeFile('realtime-qa/report.json',JSON.stringify(reports,null,2));await browser.close();}
