import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {RealtimeController,CHECKPOINT_MS} from './world.mjs';
import {WorldController} from '../cloudflare/world.mjs';
const seed=JSON.parse(await fs.readFile(new URL('../world/state.json',import.meta.url),'utf8'));
const map=new Map();let transactions=0,writes=0,fail=false;
const storage={get:async k=>structuredClone(map.get(k)),put:async(k,v)=>{if(fail)throw Error('Exceeded allowed rows written in Durable Objects free tier.');writes++;map.set(k,structuredClone(v));},delete:async k=>{writes++;map.delete(k);},setAlarm:async n=>{writes++;map.set('alarm',n);},getAlarm:async()=>map.get('alarm')??null,deleteAlarm:async()=>map.delete('alarm'),transaction:async fn=>{transactions++;const before=structuredClone(map);try{return await fn(storage);}catch(e){map.clear();for(const [k,v]of before)map.set(k,v);throw e;}}};
let now=Date.UTC(2026,8,22,12);const c=new RealtimeController(storage,{now:()=>now});await c.initialize(seed);const created=c.record.createdAt,baseWrites=writes;
for(let i=0;i<600;i++){now+=100;await c.pulse(1);if(now>=map.get('alarm'))await c.alarm(1);}
assert(c.record.revision>=600,'100 ms simulation remains active between saves');assert(transactions<=6,'a minute of frames does not save every second or double-save on alarms');assert(writes-baseWrites<30,'routine write rate leaves substantial allowance for the original world');
const normalWrites=writes-baseWrites;const saved=new RealtimeController(storage,{now:()=>now});await saved.load();assert.equal(saved.record.createdAt,created);assert(now-saved.record.lastWallTime<=c.checkpointIntervalMs);assert.deepEqual(saved.frame().agents,c.frame().agents,'latest checkpoint retains people, inventory and tasks');
const checkpointCount=transactions;now+=1;await c.alarm();assert.equal(transactions,checkpointCount,'an alarm queued just after a timer save does not write twice');
const before=structuredClone(map);fail=true;now+=c.checkpointIntervalMs;await assert.rejects(c.pulse(),/Exceeded allowed/);const revision=c.record.revision,attempts=transactions;assert.deepEqual(map,before,'failed transaction preserves the previous checkpoint');
for(let i=0;i<100;i++){now+=100;await c.pulse();}assert.equal(c.record.revision,revision,'persistence failure pauses advancement');assert.equal(transactions,attempts,'failed storage is not hammered by the frame loop');assert.equal(c.frame().runtime.status,'persistence-blocked');assert(c.persistenceRetryAt>=Date.UTC(2026,8,23)&&c.persistenceRetryAt<Date.UTC(2026,8,23)+1000);
fail=false;now=c.persistenceRetryAt;await c.pulse();assert.equal(c.persistenceRetryAt,0);assert(c.record.revision>revision);assert.equal(c.record.createdAt,created);assert.equal(c.frame().runtime.futureFrames,0);assert.equal(c.frame().runtime.status,'catching-up','outage catch-up is disclosed');
// Recovery restores alarms without advancing, seeding, or unpausing history.
const original=new WorldController(storage,{},()=>now);original.record={paused:false};map.delete('alarm');await original.recover();assert.equal(map.get('alarm'),now+1000);original.record.paused=true;map.delete('alarm');await original.recover();assert.equal(map.has('alarm'),false,'explicit original-world pause is respected');
console.log(JSON.stringify({result:'PASS bounded writes; uninterrupted frame steps; durable inventory/task restart; atomic failure; pause/backoff; quota-reset recovery without reseed; original pause respected',transactionsBeforeFailure:attempts-1,normalWritesPerMinute:normalWrites,minimumCheckpointMs:CHECKPOINT_MS}));
