import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {runtimeOrigin,runtimeUrl,LIVE_RUNTIME} from '../web/live/runtime.js';
import {WorldController} from '../cloudflare/world.mjs';
import {readCheckpoint,writeCheckpoint} from '../cloudflare/checkpoint.mjs';
for(const page of ['https://chatgptfarm.com/','https://www.chatgptfarm.com/','https://chatgptfarm-git-release-kyle8824.vercel.app/']){assert.equal(runtimeOrigin(page),LIVE_RUNTIME);assert.equal(runtimeUrl('/live/ws',page).href,LIVE_RUNTIME+'/live/ws');}
assert.equal(runtimeOrigin('http://127.0.0.1:4173/live/'),'http://127.0.0.1:4173','local tests cannot attach to production');assert.equal(runtimeOrigin(LIVE_RUNTIME+'/live/'),LIVE_RUNTIME);
const config=JSON.parse(await fs.readFile(new URL('../vercel.json',import.meta.url),'utf8'));assert.equal(config.rewrites.find(r=>r.source==='/').destination,LIVE_RUNTIME+'/live/');assert.equal(config.rewrites.find(r=>r.source==='/live/:path*').destination,LIVE_RUNTIME+'/live/:path*');
const map=new Map();let writes=0,fail=false;const storage={get:async k=>structuredClone(map.get(k)),put:async(k,v)=>{if(fail)throw Error('Exceeded allowed rows written in Durable Objects free tier.');writes++;map.set(k,structuredClone(v));},delete:async k=>map.delete(k),setAlarm:async n=>map.set('alarm',n),getAlarm:async()=>map.get('alarm')??null,deleteAlarm:async()=>map.delete('alarm'),transaction:async fn=>{const before=structuredClone(map);try{return await fn(storage);}catch(e){map.clear();for(const[k,v]of before)map.set(k,v);throw e;}}};
const record={version:1,paused:false,importedAt:123,sourceTick:2015,current:{start:10,end:20,before:{agents:[{id:'agent-mara',inventory:{wood:4}}]},after:{agents:[{id:'agent-mara',inventory:{wood:5}}]}},next:{kept:'existing buffered state'},aiBudget:{day:'2026-09-22',used:14}};
await writeCheckpoint(storage,record,999);const originalBytes=structuredClone(map);const controller=new WorldController(storage,{ORIGINAL_WORLD_ARCHIVED:'true'},()=>1000);
fail=true;await assert.rejects(controller.alarm(),/Exceeded allowed/);assert.deepEqual(map,originalBytes,'blocked archive preserves every saved key');assert.deepEqual(controller.record,record,'old simulation never advances before the archive can be saved');
fail=false;await controller.recover();const saved=await readCheckpoint(storage);assert(saved.paused);assert.equal(saved.archivedAt,1000);assert.deepEqual(saved.current,record.current);assert.deepEqual(saved.next,record.next);assert.deepEqual(saved.aiBudget,record.aiBudget);assert.equal(saved.importedAt,123);assert.equal(map.has('alarm'),false);
const savedWrites=writes;await controller.alarm();await controller.recover();assert.equal(writes,savedWrites,'archived world does not continue writing on each recovery check');const restarted=new WorldController(storage,{ORIGINAL_WORLD_ARCHIVED:'true'},()=>2000);await restarted.recover();assert.deepEqual(await readCheckpoint(storage),saved,'restart does not resume the original world');
console.log('PASS main-domain/preview socket routing; local isolation; main-domain asset rewrites; atomic archive through quota failure; saved inventory/history retained; no original-world advancement or repeated writes');
