import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {RealtimeController,parseDecision,MODEL} from './world.mjs';
const seed=JSON.parse(await fs.readFile(process.env.VALLEY_SEED||new URL('../world/state.json',import.meta.url),'utf8'));
const map=new Map();const storage={get:async k=>structuredClone(map.get(k)),put:async(k,v)=>map.set(k,structuredClone(v)),delete:async k=>map.delete(k),setAlarm:async n=>map.set('alarm',n),deleteAlarm:async()=>{},transaction:async fn=>{const before=structuredClone(map);try{return await fn(storage)}catch(e){map.clear();for(const[k,v]of before)map.set(k,v);throw e;}}};
let now=1790000000000;const c=new RealtimeController(storage,{now:()=>now});const origin=JSON.stringify(seed);await c.initialize(seed);assert.equal(JSON.stringify(seed),origin,'source is unchanged');const first=c.frame();const rev=first.runtime.revision;for(let i=0;i<30;i++)c.frame();assert.equal(c.frame().runtime.revision,rev,'reads never advance world');
now+=16000;await c.alarm();while(c.record.lastWallTime<now)await c.pulse();await c.save();let f=c.frame();assert(f.runtime.unattendedSteps>=40);assert.equal(f.runtime.computedThrough,now);assert.equal(f.runtime.futureFrames,0);assert.equal(f.runtime.alarmCount,1);
const same=new RealtimeController(storage,{now:()=>now});await same.load();assert.deepEqual(same.frame().agents,f.agents,'saved task/position/needs survive restart');await same.alarm();assert.equal(same.frame().runtime.revision,f.runtime.revision,'duplicate alarm is idempotent');
const animal=f.wildlife.find(a=>a.species==='fish');now+=60000;await same.alarm();await same.alarm();f=same.frame();assert.notDeepEqual(f.wildlife.find(a=>a.id===animal.id).position,animal.position,'fish school moves on server while land animals may legitimately rest');assert(f.runtime.computedThrough<=now);assert(f.agents.every(a=>Object.values(a.needs).every(Number.isFinite)));
console.log('PASS source preserved; pure reads; elapsed-only advancement; unattended alarms; restart persistence; duplicate alarms; wildlife movement; finite needs');
const choices=[{id:'rest'}],proposal={actionId:'rest',goal:'Recover',intent:'Rest at camp.',decisionSummary:'I need rest.'};
assert.deepEqual(parseDecision({response:proposal},choices),proposal,'Workers AI JSON-mode object accepted');
assert.deepEqual(parseDecision({response:JSON.stringify(proposal)},choices),proposal,'string response accepted');
assert.throws(()=>parseDecision({response:{...proposal,actionId:'invent-resources'}},choices),/invalid_action/);
let runs=0;same.ai={run:async(model,input)=>{runs++;assert.equal(model,MODEL);assert.equal(input.response_format.type,'json_schema');return {response:proposal};}};
const id=same.record.world.agents[0].id;await same.makeDecision(id,'{}',choices);
assert.equal(runs,1);assert.equal(same.record.ai.succeeded,1);
const restored=new RealtimeController(storage,{now:()=>now,ai:same.ai});await restored.load();assert.deepEqual(restored.record.cloudflareUsage,same.record.cloudflareUsage,'neuron reservations survive durable checkpoint reload');assert.equal(restored.proposals.get(id).actionId,'rest','pending decisions survive restart');
same.record.cloudflareUsage.days[new Date(now).toISOString().slice(0,10)].reservedNeurons=9500;await same.makeDecision(id,'{}',choices);assert.equal(runs,1,'neuron budget includes retries');
console.log('PASS structured model responses; action validation; durable pending decisions; durable daily neuron cap');
