import {pointInPolygon} from '../shared/landscape.js';
// Interaction points come from the same authoritative creek polyline used by
// navigation. A location label alone never grants access to drinking water.
export const CREEK_POINTS=[[0,17.5],[12,19.2],[27,17.4],[43,19.6],[58,18.2],[72,19.4],[86,19.1],[100,21.2]];
export const CREEK_HALF_WIDTH=1.25;
export function riverY(x){for(let i=1;i<CREEK_POINTS.length;i++)if(x<=CREEK_POINTS[i][0]){const [ax,ay]=CREEK_POINTS[i-1],[bx,by]=CREEK_POINTS[i];return ay+(by-ay)*(x-ax)/(bx-ax);}return CREEK_POINTS.at(-1)[1];}
const geometryCache=new WeakMap();
function sources(w){const result=[];for(const o of w.worldModel.objects){if(!['creek_segment','lake'].includes(o.type)||o.state?.active===false||o.state?.potable===false)continue;let data=geometryCache.get(o.geometry);if(!data){const points=o.geometry.points||[],closed=o.type==='lake',segments=[];for(let i=1;i<points.length+(closed?1:0);i++){const[x,y]=points[i-1],[bx,by]=points[i%points.length],dx=bx-x,dy=by-y,length=Math.hypot(dx,dy);if(length)segments.push({x,y,dx,dy,length,halfWidth:closed?0:o.geometry.profile?Math.max(o.geometry.profile[i-1][1],o.geometry.profile[i][1]):(o.geometry.widthM||5)/(w.worldModel.bounds.metersPerUnit||2)/2});}data={segments,polygon:closed?points:null,minX:Math.min(...points.map(p=>p[0])),maxX:Math.max(...points.map(p=>p[0])),minY:Math.min(...points.map(p=>p[1])),maxY:Math.max(...points.map(p=>p[1])),width:Math.max(0,...segments.map(s=>s.halfWidth))};geometryCache.set(o.geometry,data);}result.push(data);}return result;}
const segments=w=>sources(w).flatMap(s=>s.segments);
function projection(s,p){return Math.max(0,Math.min(1,((p.x-s.x)*s.dx+(p.y-s.y)*s.dy)/(s.length*s.length)));}
export function nearestWater(w,p){let best=null;for(const source of sources(w)){const lower=Math.hypot(Math.max(source.minX-p.x,p.x-source.maxX,0),Math.max(source.minY-p.y,p.y-source.maxY,0))-source.width;if(best&&lower>best.edge)continue;let nearest=null;for(const s of source.segments){const t=projection(s,p),q={x:s.x+s.dx*t,y:s.y+s.dy*t},d=Math.hypot(p.x-q.x,p.y-q.y)-s.halfWidth;if(!nearest||d<nearest.edge)nearest={edge:d,point:q};}if(nearest&&source.polygon&&pointInPolygon(p.x,p.y,source.polygon))nearest.edge=-nearest.edge;if(nearest&&(!best||nearest.edge<best.edge))best=nearest;}return best;}

export function withinWaterReach(w,p){const water=nearestWater(w,p);return !!w.resources.creekWater&&!!water&&water.edge>=.34&&water.edge<=.66;}
export function waterBankPoints(w,p){const points=[];for(const s of segments(w).sort((a,b)=>Math.hypot(p.x-a.x-a.dx*projection(a,p),p.y-a.y-a.dy*projection(a,p))-Math.hypot(p.x-b.x-b.dx*projection(b,p),p.y-b.y-b.dy*projection(b,p))).slice(0,w.frontier?8:Infinity)){const near=projection(s,p)*s.length;for(const offset of [0,-2,2,-5,5]){const t=Math.max(.02,Math.min(.98,(near+offset)/s.length));for(const side of [-1,1]){const r=(s.halfWidth+.47)*side;points.push({x:s.x+s.dx*t-s.dy/s.length*r,y:s.y+s.dy*t+s.dx/s.length*r});}}}return points;}
