import {SCENARIOS,LAB_VERSION,freshExperiment,settings,siteChoices,measures,requestContext,validateProposal,adoptProposal,advanceExperiment,selectRestTest} from './core.mjs';
import {LabViewer} from './viewer.mjs';
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),round=x=>Number(x||0).toFixed(1),KEY='chatgptfarm-build-lab-v1';
let lab=freshExperiment(),runs=[],busy=false,stop=false,ownerKey='',budget=null,viewer;
function notify(message,error=false){$('notice').textContent=message;$('notice').classList.toggle('error',error);}
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved?.version===LAB_VERSION&&saved.lab?.world?.agents?.length===1&&Array.isArray(saved.runs)){lab=saved.lab;runs=saved.runs.slice(-6);}}catch{notify('Saved experiment could not be restored. A fresh local experiment is ready.',true);}
try{viewer=new LabViewer($('scene'));}catch{$('scene').textContent='3D preview is unavailable on this device. Validation and simulation still work.';}
function persist(){try{localStorage.setItem(KEY,JSON.stringify({version:LAB_VERSION,lab,runs}));}catch{notify('Browser storage is full or unavailable. Export the experiments to keep them.',true);}}
function form(config){$('scenario').value=config.scenario;for(const k of ['temperature','energy','warmth','comfort','practice','reeds','cordage','weather'])$(k).value=config[k];for(const k of ['fire','nearbySites'])$(k).checked=config[k];$('scenario-description').textContent=SCENARIOS[config.scenario].description;}
function readForm(){const out={scenario:$('scenario').value};for(const k of ['temperature','energy','warmth','comfort','practice','reeds','cordage'])out[k]=Number($(k).value);out.weather=$('weather').value;out.fire=$('fire').checked;out.nearbySites=$('nearbySites').checked;return settings(out);}
function recordResult(){let record=runs.find(r=>r.id===lab.activeRunId);if(!record){record={id:crypto.randomUUID(),at:Date.now(),config:structuredClone(lab.config),variant:$('variant').value,instruction:$('instruction').value,baseline:structuredClone(lab),source:'manual'};lab.activeRunId=record.id;runs.push(record);runs=runs.slice(-6);}record.measured=measures(lab);record.observations=structuredClone(lab.observations);return record;}
function disable(value){busy=value;for(const id of ['generate','new-experiment','run10','run30','validate','adopt','save','import','scenario'])$(id).disabled=value;$('stop').hidden=!value;for(const b of document.querySelectorAll('[data-restore],[data-use]'))b.disabled=value;if(!value)$('adopt').disabled=!lab.validation?.ok||lab.validation.deferred;}
function paint(){
 const m=measures(lab),a=lab.world.agents[0],sites=siteChoices(lab);$('elapsed').textContent=round(lab.elapsedMinutes)+' simulated minutes';$('activity').textContent=m.action||'Ready';
 $('meters').innerHTML=Object.entries({...m.needs,comfort:m.comfort}).map(([key,value])=>`<div class="meter"><span>${esc({hunger:'Fed',hydration:'Hydrated',energy:'Energy',warmth:'Warmth',comfort:'Comfort'}[key])}</span><div class="track"><div class="fill" style="width:${Math.max(0,Math.min(100,value))}%"></div></div><b>${Math.round(value)}</b></div>`).join('');
 $('progress').innerHTML=`<div class="stats"><div><strong>${m.builtParts}<small> / ${m.totalParts}</small></strong><span>parts actually built</span></div><div><strong>${round(m.workMinutes)}</strong><span>assembly minutes</span></div></div><p class="subtle">Carried: ${Object.entries(a.inventory).filter(([,v])=>v>0).map(([k,v])=>esc(k)+' '+round(v)).join(' · ')||'nothing'}</p>`;
 $('surfaces').innerHTML=m.rest.map((s,i)=>`<div class="surface"><strong>${esc(s.posture==='lie'?'Lying surface':'Seated surface')}</strong><br>Comfort ${Math.round(s.comfort)}/100 · cover ${Math.round(s.cover*100)}%<br>Warmth rate ${s.heatPerHour>=0?'+':''}${round(s.heatPerHour)}/hour<button class="secondary" data-use="${i}" ${busy?'disabled':''}>Test use + 10 minutes</button></div>`).join('')||'<p class="subtle">No completed, available resting surface yet. A drawing grants no benefit.</p>';
 $('events').innerHTML=lab.world.history.slice(0,12).map(e=>`<li>${esc(e.title)}<small>${esc(e.detail)}</small></li>`).join('');
 const proposal=lab.proposal,v=lab.validation;$('proposal-status').textContent=v?.deferred?'Deferred':v?.ok?'Geometry accepted':v?'Rejected':'No proposal';
 if(proposal){$('reasoning').innerHTML=`<p><strong>${esc(proposal.name||proposal.problem||'Design decision')}</strong></p><p>${esc(proposal.problem||proposal.rationale||'')}</p>${proposal.problem&&proposal.rationale?'<p>'+esc(proposal.rationale)+'</p>':''}${Array.isArray(proposal.alternatives)?'<ul>'+proposal.alternatives.slice(0,4).map(x=>`<li>${esc(x.option)} — ${esc(x.tradeoff)}</li>`).join('')+'</ul>':''}<p>${proposal.expectedBenefit?'<strong>Hypothesis:</strong> '+esc(proposal.expectedBenefit):''}</p><p>${proposal.successCheck?'<strong>Check after use:</strong> '+esc(proposal.successCheck):''}</p>`;}else $('reasoning').innerHTML='<p class="subtle">Request a design, or enter a plan below. Adopted structures appear in the camp.</p>';
 $('validation').className=v?.ok===false?'bad':'';$('validation').textContent=!v?'':v.ok===false?v.error:v.deferred?v.message:`${Object.entries(v.bill).map(([k,n])=>n+' '+k).join(' · ')} · ${round(v.workMinutes)} minutes of assembly · ${v.bindings.coilsNeeded} additional cordage coil(s). ${v.labels.join(' · ')}. ${v.blockers.length?v.blockers.length+' current tool/binding blockers; prerequisites must be prepared. ':''}${v.message}`;
 $('adopt').disabled=busy||!v?.ok||v.deferred;
 $('sites').textContent=sites.map(s=>`${s.id}${s.experimental?' [experimental nearby site]':''}${s.extendsProjectId?' [extends '+s.extendsProjectId+']':''}: (${s.position.x}, ${s.position.y}), ${s.width} × ${s.depth}`).join('\n');
 $('comparisons').innerHTML=runs.length?`<table><thead><tr><th>Experiment</th><th>Source / result</th><th>Built</th><th>Use</th><th></th></tr></thead><tbody>${[...runs].reverse().map(r=>`<tr><td>${esc(SCENARIOS[r.config?.scenario]?.name||'Imported')}<br><small>${esc(r.variant||'manual')}${r.config?.nearbySites?' · nearby sites':''}</small></td><td>${esc(r.model||r.source||'manual')}<br>${esc(r.validation?.deferred?'deferred':r.validation?.ok?'accepted':r.validation?'rejected':r.error?'request failed':'local run')}</td><td>${r.measured?.builtParts||0}/${r.measured?.totalParts||0}</td><td>${r.measured?.rest?.length||0} surfaces<br>${round(r.measured?.elapsedMinutes)} min</td><td><button data-restore="${esc(r.id)}" ${busy?'disabled':''}>Restore start</button></td></tr>`).join('')}</tbody></table>`:'<p class="subtle">No saved comparisons yet. The last six runs are retained in this browser; export to keep a longer record.</p>';
 viewer?.show(lab,sites,$('view-mode').value);
}
function showBudget(data){budget=data;$('budget').textContent=`${data.model||'Unconfigured model'} · ${data.calls}/${data.dailyCalls} requests · $${data.reservedUsd.toFixed(4)} reserved / $${data.dailyUsd.toFixed(2)} daily. Resets ${new Date(data.resetAt).toLocaleString()}. Cloudflare AI usage: zero. ${data.priceMismatch?'Price/usage mismatch: further calls are paused.':''}`;}
async function api(path,body){const response=await fetch('./api/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+ownerKey,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(65000)});let result;try{result=await response.json();}catch{throw Error('The lab endpoint did not return JSON. No automatic retry was made.');}if(result.budget)showBudget(result.budget);if(!response.ok)throw Error(result.error||'Lab request failed');return result;}
async function run(minutes){if(busy)return;if(!lab.activeRunId)recordResult();disable(true);stop=false;notify('Advancing this local experiment with the farm’s elapsed simulation rules…');try{await advanceExperiment(lab,minutes,{onFrame:paint,shouldStop:()=>stop});recordResult();notify('Measured progress saved. The next AI request will include these observations.');}catch(e){notify(e.message,true);}finally{disable(false);paint();persist();}}
$('scenario').innerHTML=Object.entries(SCENARIOS).map(([id,s])=>`<option value="${id}">${s.name}</option>`).join('');form(lab.config);
$('scenario').addEventListener('change',()=>form(settings({scenario:$('scenario').value})));
$('new-experiment').addEventListener('click',()=>{if(lab.activeRunId)recordResult();lab=freshExperiment(readForm());$('editor').value='';paint();persist();notify('Fresh controlled camp created. Your saved comparisons remain available.');});
$('unlock').addEventListener('click',async()=>{ownerKey=$('owner-key').value;$('owner-key').value='';try{showBudget(await api('status'));notify('Owner access verified. AI calls will use the separate lab budget.');}catch(e){ownerKey='';notify(e.message,true);}});
$('lock').addEventListener('click',()=>{ownerKey='';$('owner-key').value='';notify('AI access locked. The experiment stays available locally.');});
$('generate').addEventListener('click',async()=>{
 if(busy)return;if(!ownerKey){$('access').open=true;$('owner-key').focus();notify('Enter your existing farm owner key under Owner access to enable AI requests. Local editing needs no key.');return;}
 disable(true);const context=requestContext(lab),id=crypto.randomUUID(),record={id,at:Date.now(),config:structuredClone(lab.config),baseline:structuredClone(lab),variant:$('variant').value,instruction:$('instruction').value,context,source:'AI'};runs.push(record);runs=runs.slice(-6);lab.activeRunId=id;persist();notify('Requesting one AI design. Geometry and actual usefulness will be checked separately.');
 try{const result=await api('design',{requestId:id,variant:record.variant,instruction:record.instruction,context});Object.assign(record,{model:result.model,responseId:result.responseId,usage:result.usage,response:result.proposal});const proposal={...result.proposal,labModel:result.model};$('editor').value=JSON.stringify(proposal,null,2);record.validation=validateProposal(lab,proposal);record.measured=measures(lab);notify(record.validation.ok?'AI response received. Inspect the proposal, then adopt it to test actual construction.':'The AI proposal failed the farm’s validator. The rejection is saved for the next attempt.',!record.validation.ok);$('view-mode').value='design';}catch(e){record.error=e.message;notify(e.message,true);}finally{disable(false);paint();persist();}
});
$('validate').addEventListener('click',()=>{try{const raw=JSON.parse($('editor').value);const v=validateProposal(lab,raw),r=recordResult();r.response=raw;r.validation=structuredClone(v);notify(v.ok?'Plan checked against the farm’s rules.':v.error,!v.ok);$('view-mode').value='design';}catch(e){notify(e.message,true);}paint();persist();});
$('adopt').addEventListener('click',()=>{try{adoptProposal(lab);$('view-mode').value='construction';recordResult();notify('Plan adopted. Run the experiment to gather, carry, prepare tools and assemble its parts.');}catch(e){notify(e.message,true);}paint();persist();});
$('run10').addEventListener('click',()=>run(10));$('run30').addEventListener('click',()=>run(30));$('stop').addEventListener('click',()=>{stop=true;});
$('surfaces').addEventListener('click',e=>{const b=e.target.closest('[data-use]');if(!b||busy)return;const s=measures(lab).rest[Number(b.dataset.use)];try{selectRestTest(lab,s.projectId,s.surfaceId);run(10);}catch(e){notify(e.message,true);}});
$('view-mode').addEventListener('change',paint);$('camera-home').addEventListener('click',()=>viewer?.home());
$('comparisons').addEventListener('click',e=>{const b=e.target.closest('[data-restore]');if(!b||busy)return;const r=runs.find(x=>x.id===b.dataset.restore);if(!r)return;lab=r.baseline?structuredClone(r.baseline):freshExperiment(r.config);lab.activeRunId=null;$('variant').value=r.variant||'context';$('instruction').value=r.instruction||'';$('editor').value=lab.proposal?JSON.stringify(lab.proposal,null,2):'';form(lab.config);paint();persist();notify('Restored this run’s starting conditions and world state. AI output may vary between calls.');});
$('save').addEventListener('click',()=>{recordResult();persist();paint();notify('Saved this run in the browser. Export to keep an independent copy.');});
$('export').addEventListener('click',()=>{recordResult();const content=JSON.stringify({format:'chatgptfarm-build-lab',version:LAB_VERSION,engine:typeof __LAB_COMMIT__==='string'?__LAB_COMMIT__:'local',runs},null,2),url=URL.createObjectURL(new Blob([content],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='chatgptfarm-build-experiments.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
$('import').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>4000000)throw Error('Import is limited to 4 MB.');const data=JSON.parse(await file.text());if(data.format!=='chatgptfarm-build-lab'||data.version!==LAB_VERSION||!Array.isArray(data.runs)||data.runs.length>100)throw Error('Unsupported experiment archive.');for(const r of data.runs){if(typeof r.id!=='string'||!r.config||r.baseline&&(!r.baseline.world||r.baseline.world.agents?.length!==1||!Array.isArray(r.baseline.world.settlement?.projects)))throw Error('Invalid saved experiment.');r.config=settings(r.config);}runs=[...runs,...data.runs].slice(-6);persist();paint();notify('Imported comparisons. Restore a starting point to continue.');}catch(error){notify(error.message,true);}e.target.value='';});
$('revision').textContent='Construction rules: '+(typeof __LAB_COMMIT__==='string'?__LAB_COMMIT__.slice(0,12):'local development');
if(lab.proposal)$('editor').value=JSON.stringify(lab.proposal,null,2);paint();
