import {placeMarkup,inventoryMarkup,settlementJournal} from './settlement-inspector.js';
import {WorldConnection} from './connection.js';
import {ValleyScene} from './scene.js';
import {ValleyMap} from './map.js';
import {progressRatio,progressText,taskExplanation} from './task-view.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null,lastFrame=0,lastUI=0,latency=null,selected=null,loaded=false,tab='thought',audio=null,inspectorTaskKey='';
let scene;try{scene=new ValleyScene($('#world'),openPerson);}catch{const old=$('#world'),canvas=old.cloneNode();old.replaceWith(canvas);scene=new ValleyMap(canvas,openPerson);}
function openPerson(id){selected=id;tab='thought';renderInspector();if(!$('#inspector').open)$('#inspector').showModal();scene.follow(id);}
function actionMode(a){return a.task?.source==='ai'?'AI':a.mind?.fallbackReason==='urgent_need'?'Instinct':'NPC';}
function updateUI(){if(!state)return;const s=state;$('#day').textContent=`Day ${s.day}`;$('#clock').textContent=`${String(s.hour).padStart(2,'0')}:${String(Math.floor(s.minute||0)).padStart(2,'0')}`;$('#weather').textContent=`${s.weather==='rain'?'Rain':s.weather==='clear'?'Clear':s.weather} · ${Math.round(s.temperature)}°F`;
 for(const a of s.agents){let card=document.getElementById(a.id);if(!card){card=document.createElement('button');card.id=a.id;card.className='person';card.innerHTML=`<span class="avatar">${esc(a.name[0])}</span><strong>${esc(a.name)}<small></small></strong><span class="activity"></span><span class="progress"><i></i></span>`;card.addEventListener('click',()=>openPerson(a.id));$('#people').append(card);}card.querySelector('small').textContent=actionMode(a);card.querySelector('.activity').textContent=a.task?.phase==='travel'?a.currentAction:a.task?.label||'Observing the valley';card.querySelector('.progress i').style.width=`${progressRatio(a)*100}%`;card.setAttribute('aria-label',`${a.name}: ${a.currentAction}`);}
 $('#latest-event').textContent=s.history[0]?.title||'The world continues';if($('#inspector').open)refreshInspector();if($('#journal').open)renderJournal();if($('#diagnostics').open)renderProof();
}
function renderInspector(){const place=placeMarkup(state,selected);if(place){$('#inspect-content').innerHTML=place;bindPlaces();return;}const a=state?.agents.find(a=>a.id===selected);if(!a)return;const mode=actionMode(a),explanation=taskExplanation(a);inspectorTaskKey=`${a.task?.id}:${a.task?.phase}:${a.task?.source}:${a.task?.interactionReady}`;$('#inspect-content').innerHTML=`<div class="person-intro"><div class="avatar">${esc(a.name[0])}</div><div><h2>${esc(a.name)}</h2><p>${mode==='AI'?'AI-directed action':mode==='Instinct'?'Urgent survival response':'Autonomous survival rules'} · ${a.memoryCount} memories</p></div></div><div class="action-box"><strong>${esc(a.currentAction)}</strong><p>${esc(progressText(a))}</p></div><div class="stats">${[['hunger','Fed'],['hydration','Hydrated'],['energy','Rested'],['warmth','Warm']].map(([k,label])=>`<div class="stat"><label>${label}<span>${Math.round(a.needs[k])}%</span></label><div class="bar"><i style="width:${a.needs[k]}%;background:${a.needs[k]<20?'#d69c73':'#b5c992'}"></i></div></div>`).join('')}</div><div class="detail-tabs">${['thought','carrying','memories'].map(t=>`<button data-tab="${t}" class="${t===tab?'active':''}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div><div class="detail-body">${tab==='carrying'?`<p>${a.carrying?`${a.carrying.mass.toFixed(1)} / ${a.carrying.capacity.mass} kg · ${a.carrying.volume.toFixed(1)} / ${a.carrying.capacity.volume} carrying-space units`:''}</p><div class="inventory">${Object.entries(a.inventory).filter(([,n])=>n>0).map(([k,n])=>`<span>${esc(k.replace(/([A-Z])/g,' $1'))} × ${Math.round(n*10)/10}</span>`).join('')||'Empty hands'}</div>`:tab==='memories'?`<ul>${a.memories.map(m=>`<li>${esc(m.text)}</li>`).join('')}</ul>`:`<p>${esc(explanation.text)}</p><p>${esc(explanation.note)}</p>`}</div>`;for(const b of $('#inspect-content').querySelectorAll('[data-tab]'))b.onclick=()=>{tab=b.dataset.tab;renderInspector();};}
function refreshInspector(){if(placeMarkup(state,selected)||tab==='carrying'){renderInspector();return;}const a=state?.agents.find(a=>a.id===selected);if(!a)return;if(inspectorTaskKey!==`${a.task?.id}:${a.task?.phase}:${a.task?.source}:${a.task?.interactionReady}`){renderInspector();return;}const box=$('#inspect-content .action-box');if(box){box.querySelector('strong').textContent=a.currentAction;box.querySelector('p').textContent=progressText(a);}const keys=['hunger','hydration','energy','warmth'];for(const [i,node]of [...document.querySelectorAll('#inspect-content .stat')].entries()){node.querySelector('label span').textContent=`${Math.round(a.needs[keys[i]])}%`;node.querySelector('.bar i').style.width=`${a.needs[keys[i]]}%`;}}
function bindPlaces(){for(const b of document.querySelectorAll('[data-place]'))b.onclick=()=>{$('#journal').close();openPerson(b.dataset.place);};}
function renderJournal(){$('#events').innerHTML=settlementJournal(state)+state.history.map(e=>`<article class="event"><small>DAY ${e.day} · ${String(e.hour).padStart(2,'0')}:00</small><h3>${esc(e.title)}</h3><p>${esc(e.detail)}</p></article>`).join('');bindPlaces();}
function renderProof(){const r=state.runtime;$('#proof').innerHTML=[['Connection',connection.socket?.readyState===1?'WebSocket connected':'Reconnecting'],['Latest frame',`${Math.max(0,Date.now()-lastFrame)} ms ago`],['Measured round trip',latency===null?'Measuring':`${latency} ms`],['World revision',r.revision.toLocaleString()],['Steps without viewers',r.unattendedSteps.toLocaleString()],['Server alarms',r.alarmCount.toLocaleString()],['Simulation behind wall clock',`${r.lagMs} ms`],['Future frames computed',r.futureFrames],['AI calls today',`${r.ai.calls} / 96 maximum`],['Model responses',r.ai.succeeded],['Action proposals used',r.ai.applied],['Construction designs adopted',state.settlement?.projects.length||0],['World clock','6 simulated seconds / real second']].map(([a,b])=>`<div class="proof-row"><span>${a}</span><strong>${esc(b)}</strong></div>`).join('')+`<p class="proof-note">The server executes the world as time passes. This browser receives current state over a WebSocket and smooths movement between received positions by up to 100 ms. It does not play a prerecorded future. Server alarms continue when nobody is watching. Outages are caught up from elapsed time and are reported as lag.</p><p class="proof-note">This is an independent continuation of the original world from day ${r.origin.sourceDay}. The original world is preserved. ${r.ai.configured?'A language model proposes occasional actions; survival rules handle actions between those decisions.':'Language model planning is not configured; villagers use NPC survival rules.'} ${r.ai.lastError?`Last model error: ${esc(r.ai.lastError)}`:''}</p>`;}
function showConnectionProblem(message){if(loaded)return;$('#loading').classList.add('failed');$('#loading h2').textContent='The valley couldn’t open';$('#loading-message').textContent=message;$('#connection-retry').hidden=false;}
const socketUrl=new URL('/live/ws',location.href);socketUrl.protocol=socketUrl.protocol==='https:'?'wss:':'ws:';
const connection=new WorldConnection({url:socketUrl,onPong:ms=>latency=ms,onProblem:showConnectionProblem,onFrame:m=>{scene.accept(m);state=m;lastFrame=Date.now();if(!loaded){updateUI();loaded=true;$('#loading').style.opacity=0;$('#loading').style.pointerEvents='none';setTimeout(()=>$('#loading').remove(),700);}if(Date.now()-lastUI>500){updateUI();lastUI=Date.now();}}});
$('#connection-retry').onclick=()=>{$('#loading').classList.remove('failed');$('#loading h2').textContent='Opening the valley';$('#loading-message').textContent='Trying the world server again…';$('#connection-retry').hidden=true;connection.retryNow();};
setInterval(()=>{const fresh=state&&Date.now()-lastFrame<2000&&state.runtime.status==='running';$('#connection').classList.toggle('live',!!fresh);$('#connection-text').textContent=fresh?'Live world':state?'Reconnecting':'Connecting';$('#latency').textContent=latency===null?'':`${latency} ms`;$('#offline').hidden=!state||!!fresh;if($('#diagnostics').open&&state)renderProof();connection.ping();},1500);
$('#home').onclick=()=>scene.home();$('#zoom-in').onclick=()=>scene.zoom(.8);$('#zoom-out').onclick=()=>scene.zoom(1.25);$('#connection').onclick=()=>{if(state){renderProof();$('#diagnostics').showModal();}};$('#journal-open').onclick=()=>{if(state){renderJournal();$('#journal').showModal();}};for(const d of document.querySelectorAll('dialog')){d.querySelector('.close').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});}
$('#sound').onclick=()=>{if(audio){audio.close();audio=null;$('#sound').classList.remove('on');return;}audio=new AudioContext();const buf=audio.createBuffer(1,audio.sampleRate*3,audio.sampleRate),data=buf.getChannelData(0);let brown=0;for(let i=0;i<data.length;i++){brown=(brown+(Math.random()*2-1)*.018)/1.025;data[i]=brown;}const source=audio.createBufferSource();source.buffer=buf;source.loop=true;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=1100;const gain=audio.createGain();gain.gain.value=.45;source.connect(filter).connect(gain).connect(audio.destination);source.start();$('#sound').classList.add('on');};
fetch('/live/geometry').then(r=>{if(!r.ok)throw Error('Geometry unavailable');return r.json();}).then(g=>scene.addHistory(g)).catch(()=>{});
connection.start();
