// Accessible live map for browsers where WebGL is disabled. No local simulation.
export class ValleyMap{
 constructor(canvas,onSelect){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.scale=1;this.focus=null;this.onSelect=onSelect;canvas.setAttribute('aria-label','Live valley map. 3D graphics are unavailable in this browser.');document.querySelector('.hint').textContent='3D unavailable in this browser · Live map · Select a villager';canvas.onclick=e=>{if(!this.frame)return;for(const a of this.frame.agents){const p=this.point(a.coordinates);if(Math.hypot(p.x-e.clientX,p.y-e.clientY)<24)this.onSelect(a.id);}};addEventListener('resize',()=>this.draw());}
 point(p){const focus=this.frame?.agents.find(a=>a.id===this.focus)?.coordinates||{x:50,y:37};const size=Math.min(innerWidth/108,innerHeight/83)*this.scale;return{x:innerWidth/2+(p.x-focus.x)*size,y:innerHeight/2+(p.y-focus.y)*size};}
 accept(f){this.frame=f;this.draw();} addHistory(g){this.geometry=g;this.draw();} home(){this.focus=null;this.scale=1;this.draw();} follow(id){this.focus=id;this.scale=1.5;this.draw();} zoom(n){this.scale=Math.max(.6,Math.min(5,this.scale/n));this.draw();}
 draw(){const c=this.ctx;if(!c)return;this.canvas.width=innerWidth;this.canvas.height=innerHeight;c.fillStyle='#243e36';c.fillRect(0,0,innerWidth,innerHeight);c.strokeStyle='#49756c';c.lineWidth=12*this.scale;c.lineJoin='round';c.beginPath();for(const[i,p]of [[0,17.5],[12,19.2],[27,17.4],[43,19.6],[58,18.2],[72,19.4],[86,19.1],[100,21.2]].entries()){const q=this.point({x:p[0],y:p[1]});i?c.lineTo(q.x,q.y):c.moveTo(q.x,q.y);}c.stroke();
  for(const o of this.geometry?.objects||[]){const p=this.point(o.position);c.fillStyle=o.type?.includes('tree')?'#476c46':'#71816d';c.beginPath();c.arc(p.x,p.y,3*this.scale,0,Math.PI*2);c.fill();}
  const labels=[];for(const a of [...(this.frame?.wildlife||[]),...(this.frame?.agents||[])]){const p=this.point(a.coordinates||a.position);c.fillStyle=a.name?'#ead69e':'#abac88';c.beginPath();c.arc(p.x,p.y,a.name?7:3,0,Math.PI*2);c.fill();if(a.name){let y=p.y-15;for(const prev of labels)if(Math.abs(prev.x-p.x)<70&&Math.abs(prev.y-y)<20)y=prev.y-22;labels.push({x:p.x,y});c.font='600 14px system-ui';c.fillText(a.name,p.x+11,y);}}
 }
}
