import {HOME_REGIONS,GREAT_RIVER,FRONTIER_OBSTACLES} from '../../shared/frontier.js';
import {CREEK_POINTS} from '../../realtime/water.mjs';
// Accessible live map for browsers where WebGL is disabled. No local simulation.
export class ValleyMap{
 constructor(canvas,onSelect){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.scale=1;this.focus=null;this.onSelect=onSelect;canvas.setAttribute('aria-label','Live valley map. 3D graphics are unavailable in this browser.');document.querySelector('.hint').textContent='3D unavailable in this browser · Live map · Select a person or supplies';canvas.onclick=e=>{if(!this.frame)return;for(const a of [...this.frame.agents,...(this.frame.wildlife||[]),...(this.frame.objects||[]),...(this.frame.settlement?.trees||[]),...(this.frame.settlement?.stores||[]),...(this.frame.settlement?.projects||[])]){const p=this.point(a.coordinates||a.position);if(Math.hypot(p.x-e.clientX,p.y-e.clientY)<24)this.onSelect(a.id);}};addEventListener('resize',()=>this.draw());}
 point(p){const focus=this.frame?.agents.find(a=>a.id===this.focus)?.coordinates||this.frame?.settlement?.stores.find(s=>s.id===this.focus)?.position||this.frame?.settlement?.projects.find(p=>p.id===this.focus)?.position||this.frame?.wildlife.find(a=>a.id===this.focus)?.position||this.frame?.objects?.find(o=>o.id===this.focus)?.position||this.frame?.settlement?.trees.find(o=>o.id===this.focus)?.position||this.homeCenter||{x:50,y:37};const size=Math.min(innerWidth/108,innerHeight/83)*this.scale;return{x:innerWidth/2+(p.x-focus.x)*size,y:innerHeight/2+(p.y-focus.y)*size};}
 visitHome(id){this.focus=null;const h=[...(this.frame?.frontier?.homes||HOME_REGIONS),...(this.frame?.frontier?.landmarks||[])].find(h=>h.id===id);if(!h)return;this.homeCenter={x:h.x,y:h.y};this.scale=1;this.draw();} overview(){this.focus=null;const b=this.frame?.frontier?.bounds||{minX:0,maxX:500,minY:0,maxY:500};this.homeCenter={x:(b.minX+b.maxX)/2,y:(b.minY+b.maxY)/2};this.scale=.18;this.draw();}
 accept(f){this.frame=f;this.draw();} addHistory(g){this.geometry=g;this.draw();} home(){this.focus=null;this.homeCenter=null;this.scale=1;this.draw();} follow(id){this.focus=id;this.scale=1.5;this.draw();} zoom(n){this.scale=Math.max(this.frame?.frontier ? .1 : .6,Math.min(5,this.scale/n));this.draw();}
 draw(){const c=this.ctx;if(!c)return;this.canvas.width=innerWidth;this.canvas.height=innerHeight;c.fillStyle='#243e36';c.fillRect(0,0,innerWidth,innerHeight);const expanded=!!this.frame?.frontier;
  if(expanded&&this.frame.frontier.landscapeVersion!==2)for(const r of FRONTIER_OBSTACLES){const a=this.point({x:r.minX,y:r.minY}),b=this.point({x:r.maxX,y:r.maxY});c.fillStyle=r.kind==='ravine'?'#172b29':r.kind==='ridge'?'#999887':'#aaa184';c.fillRect(a.x,a.y,b.x-a.x,b.y-a.y);}
  for(const l of this.frame?.frontier?.water?.lakes||[]){c.beginPath();for(const [i,[x,y]]of l.points.entries()){const p=this.point({x,y});i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y);}c.closePath();c.fillStyle="#5b9b9e";c.fill();}
  const rivers=this.frame?.frontier?.water?this.frame.frontier.water.streams.map(s=>s.points):expanded?[GREAT_RIVER,...HOME_REGIONS.map(h=>CREEK_POINTS.map(([x,y])=>[x+h.x-64,y+h.y-34]))]:[CREEK_POINTS];c.strokeStyle='#5b9b9e';c.lineWidth=Math.max(2,12*this.scale);c.lineJoin='round';for(const river of rivers){c.beginPath();for(const [i,p]of river.entries()){const q=this.point({x:p[0],y:p[1]});i?c.lineTo(q.x,q.y):c.moveTo(q.x,q.y);}c.stroke();}
  if(expanded)for(const h of this.frame.frontier.homes){const p=this.point(h);c.fillStyle='#e1d9b2';c.font='600 12px system-ui';c.fillText(h.name,p.x-30,p.y-28);}

  for(const o of [...(this.frame?.objects||this.geometry?.objects||[]),...(this.frame?.settlement?.trees||[])]){const p=this.point(o.position);c.fillStyle=o.type?.includes('tree')?'#476c46':'#71816d';c.beginPath();c.arc(p.x,p.y,3*this.scale,0,Math.PI*2);c.fill();}
  for(const p of this.frame?.settlement?.projects||[]){for(const part of p.parts){const q=this.point({x:p.position.x+part.center[0]-part.size[0]/2,y:p.position.y+part.center[2]-part.size[2]/2}),r=this.point({x:p.position.x+part.center[0]+part.size[0]/2,y:p.position.y+part.center[2]+part.size[2]/2});c.fillStyle=part.built?'#b19c73':'#b19c7333';c.strokeStyle='#dbc996';c.fillRect(q.x,q.y,r.x-q.x,r.y-q.y);c.strokeRect(q.x,q.y,r.x-q.x,r.y-q.y);}}for(const s of this.frame?.settlement?.stores||[]){const p=this.point(s.position);c.fillStyle=s.ownerId?.endsWith('mara')?'#c99a68':'#80b1b1';c.fillRect(p.x-4,p.y-4,8,8);}
  const labels=[];for(const a of [...(this.frame?.wildlife||[]),...(this.frame?.agents||[])]){const p=this.point(a.coordinates||a.position);c.fillStyle=a.name?'#ead69e':'#abac88';c.beginPath();c.arc(p.x,p.y,a.name?7:3,0,Math.PI*2);c.fill();if(a.name){let y=p.y-15;for(const prev of labels)if(Math.abs(prev.x-p.x)<70&&Math.abs(prev.y-y)<20)y=prev.y-22;labels.push({x:p.x,y});c.font='600 14px system-ui';c.fillText(a.name,p.x+11,y);}}
 }
}
