import {NaturalObjects} from './natural-objects.js';
import {forestLayout} from '../../realtime/forest.mjs';
import {SettlementView,updateCargo} from './settlement.js';
import {CAMP} from '../../realtime/layout.mjs';
import {riverY,CREEK_HALF_WIDTH} from '../../realtime/water.mjs';
import {createPerson,animatePerson,personAction} from './people.js';
import {crownGeometry,pineGeometry,foliageMaterial} from './foliage.js';
export {riverY} from '../../realtime/water.mjs';
import * as T from 'three';
import {MapGestureControls} from '../../shared/visuals/map-controls.js';
import {createAnimal,animateAnimal} from '../../shared/visuals/models.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function elevation(x,z){
 const center=riverY(x),d=Math.abs(z-center),side=Math.sign(z-center)||1;
 const raw=sample=>{const gap=Math.abs(sample-center),hills=Math.max(0,sample-53)*.095+Math.max(0,9-sample)*.13;return -.48+Math.min(1.12,gap*.36)+Math.sin(x*.16)*Math.sin(sample*.15)*Math.min(.5,gap*.055)+hills*(1.2+Math.sin(x*.15)*.6);};
 // Match the bank's mesh segments exactly where people stand and reach.
 if(d<=CREEK_HALF_WIDTH)return -.48+.34*d/CREEK_HALF_WIDTH;
 if(d<=2.5)return -.14+(d-CREEK_HALF_WIDTH)*.56;
 if(d<3.75)return T.MathUtils.lerp(.56,raw(center+side*3.75),(d-2.5)/1.25);
 return raw(z);
}

const mat=(color,extra={})=>new T.MeshStandardMaterial({color,roughness:1,flatShading:true,...extra});
function mesh(geo,m,pos,parent){const o=new T.Mesh(geo,m);o.position.set(...pos);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
function seeded(seed=816){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}
function branch(parent,a,b,r,m){const av=new T.Vector3(...a),bv=new T.Vector3(...b),v=bv.clone().sub(av);const o=mesh(new T.CylinderGeometry(r*.72,r,v.length(),6),m,av.add(bv).multiplyScalar(.5).toArray(),parent);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),v.normalize());return o;}
// Existing rows follow the creek's center and edges; no extra triangles.
export function createTerrainGeometry(){const g=new T.PlaneGeometry(148,116,148,116);g.rotateX(-Math.PI/2);const p=g.attributes.position,colors=[];const green=new T.Color();for(let i=0;i<p.count;i++){const x=p.getX(i)+50,gridZ=p.getZ(i)+38,offset=gridZ-20;let z=gridZ;if(Math.abs(offset)<=4)z=riverY(x)+offset*1.25;else if(Math.abs(offset)<12)z+=(riverY(x)-20+Math.sign(offset))*(12-Math.abs(offset))/8;const h=elevation(x,z);p.setXYZ(i,x,h,z);const d=Math.abs(z-riverY(x)),variation=(Math.sin(x*4.1+z*2.7)+Math.cos(z*3.3-x))/2;green.set(d<1.9?'#a4a382':d<3?'#85936b':z>60?'#52794b':'#789855');green.offsetHSL(variation*.008,variation*.025,variation*.033);colors.push(green.r,green.g,green.b);}g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.computeVertexNormals();return g;}
export class ValleyScene{
 constructor(canvas,onSelect){
  this.canvas=canvas;this.onSelect=onSelect;this.entities=new Map();this.labels=new Map();this.frame=null;this.focus=null;this.elapsed=0;this.receivedAt=0;
  this.renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.16;
  this.scene=new T.Scene();this.scene.background=new T.Color('#98bbb7');this.scene.fog=new T.FogExp2('#9fbcb2',.0055);
  this.camera=new T.PerspectiveCamera(43,innerWidth/innerHeight,.2,450);this.controls=new MapGestureControls(this.camera,canvas,{heightAt:elevation});this.controls.enableDamping=true;this.controls.dampingFactor=.065;this.controls.maxPolarAngle=Math.PI*.46;this.controls.minPolarAngle=.2;this.controls.minDistance=4;this.controls.maxDistance=135;this.controls.maxTargetRadius=100;this.controls.enablePan=true;this.controls.screenSpacePanning=false;
  this.controls.mouseButtons.LEFT=T.MOUSE.PAN;this.controls.mouseButtons.RIGHT=T.MOUSE.ROTATE;
  this.controls.cursor.set(50,0,38);this.controls.target.set(51,0,32);this.home();
  this.ambient=new T.HemisphereLight('#d1e6eb','#4b6842',2.1);this.scene.add(this.ambient);this.sun=new T.DirectionalLight('#fff0cc',3.2);this.sun.position.set(-25,65,18);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);Object.assign(this.sun.shadow.camera,{left:-85,right:85,top:85,bottom:-85,near:1,far:180});this.sun.shadow.bias=-.0005;this.sun.shadow.normalBias=.1;this.sun.target.position.set(50,0,30);this.scene.add(this.sun,this.sun.target);this.faceLight=new T.DirectionalLight('#e9f2ed',.5);this.scene.add(this.faceLight,this.faceLight.target);
  this.naturalView=new NaturalObjects(this.scene,elevation);this.settlementView=new SettlementView(this.scene,elevation);this.terrain();this.water();this.forest();this.camp();this.animals();this.environment();
  this.ray=new T.Raycaster();this.pointer=new T.Vector2();let down=null;const pointers=new Set();
  canvas.addEventListener('pointerdown',e=>{pointers.add(e.pointerId);down=pointers.size===1&&e.button===0?{id:e.pointerId,x:e.clientX,y:e.clientY}:null;});
  canvas.addEventListener('pointermove',e=>{if(down?.id===e.pointerId&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)down=null;});
  for(const event of ['pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{pointers.delete(e.pointerId);down=null;});
  canvas.addEventListener('pointerup',e=>{const tap=down?.id===e.pointerId&&pointers.size===1&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<=5;pointers.delete(e.pointerId);down=null;if(!tap)return;this.pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);this.ray.setFromCamera(this.pointer,this.camera);for(const hit of this.ray.intersectObjects([...this.entities.values(),...this.settlementView.objects.values(),...this.naturalView.objects.values()].filter(e=>e.group.visible).map(e=>e.group),true).sort((a,b)=>{const water=h=>{let p=h.object;while(p&&!p.userData.objectId)p=p.parent;return p?.userData.objectId==='OBJ-CREEK-001'?1:0;};return water(a)-water(b)||a.distance-b.distance;})){let o=hit.object;while(o&&!o.userData.agentId&&!o.userData.objectId)o=o.parent;if(o){this.onSelect(o.userData.agentId||o.userData.objectId);break;}}});
  this.controls.addEventListener('start',()=>{this.focus=null;});addEventListener('resize',()=>this.resize());this.resize();this.last=performance.now();this.animate=this.animate.bind(this);requestAnimationFrame(this.animate);
 }
 home(){this.focus=null;const mobile=innerWidth<650;this.camera.position.set(mobile?80:76,mobile?68:49,mobile?97:79);this.controls.target.set(mobile?54:51,0,31);this.controls.update();}
 zoom(amount){const d=this.camera.position.clone().sub(this.controls.target);d.multiplyScalar(amount);this.camera.position.copy(this.controls.target).add(d);}
 follow(id){this.focus=id;const a=this.entities.get(id)||this.settlementView.objects.get(id)||this.naturalView.objects.get(id);if(a){const v=a.group.position;const d=this.camera.position.clone().sub(this.controls.target).normalize().multiplyScalar(26);this.controls.target.copy(v);this.camera.position.copy(v).add(d);}}
 resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight,false);}
 terrain(){const g=createTerrainGeometry();mesh(g,mat('#ffffff',{vertexColors:true}),[0,0,0],this.scene);
  const rnd=seeded(922);const grassGeo=new T.ConeGeometry(.055,.48,3),grassMat=mat('#acc277');const grass=new T.InstancedMesh(grassGeo,grassMat,1800),dummy=new T.Object3D();let index=0;for(let i=0;i<2300&&index<1800;i++){const x=rnd()*116-8,z=rnd()*82-3;if(Math.abs(z-riverY(x))<2.2||Math.hypot(x-64,z-34)<5)continue;dummy.position.set(x,elevation(x,z)+.15,z);dummy.rotation.set((rnd()-.5)*.4,rnd()*6.28,(rnd()-.5)*.4);dummy.scale.setScalar(.5+rnd()*.9);dummy.updateMatrix();grass.setMatrixAt(index++,dummy.matrix);}grass.count=index;this.scene.add(grass);
  // Small stones follow the actual bank, leaving the channel clear.
  const stones=mat('#9b9d84');for(let i=0;i<115;i++){const x=rnd()*110-5,z=riverY(x)+(rnd()<.5?-1:1)*(1.55+rnd()*1.3);const o=mesh(new T.IcosahedronGeometry(.2+rnd()*.6,0),stones,[x,elevation(x,z)+.04,z],this.scene);o.scale.set(1.5,.65,1);o.rotation.y=rnd()*6;}
 }
 water(){const positions=[],indices=[],count=200;for(let i=0;i<=count;i++){const x=-24+i*.74,z=riverY(x);positions.push(x,-.12,z-CREEK_HALF_WIDTH,x,-.12,z+CREEK_HALF_WIDTH);if(i<count){const a=i*2;indices.push(a,a+1,a+2,a+1,a+3,a+2);}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setIndex(indices);g.computeVertexNormals();
  this.waterMat=new T.ShaderMaterial({uniforms:{time:{value:0},deep:{value:new T.Color('#277e86')},shallow:{value:new T.Color('#7ec4bf')}},vertexShader:'varying vec3 pos; void main(){pos=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'varying vec3 pos; uniform float time;uniform vec3 deep;uniform vec3 shallow;void main(){float w=sin(pos.x*2.7-time*1.5+sin(pos.z*9.0))*sin(pos.x*.8+pos.z*19.0-time*2.);float stripe=pow(max(0.,sin(pos.x*1.2-pos.z*6.-time*1.8)),22.)*.18;vec3 col=mix(deep,shallow,w*.13+.46);gl_FragColor=vec4(col,.62);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}',side:T.DoubleSide,transparent:true,depthWrite:false});mesh(g,this.waterMat,[0,0,0],this.scene);
 }
 forest(){for(const m of this.forestMeshes||[]){this.scene.remove(m);m.geometry.dispose();m.material.dispose();}this.forestMeshes=[];const forestGroup=new T.Group();this.scene.add(forestGroup);const rnd=seeded(313);const trunkM=mat('#68563c',{flatShading:false});const leafM=['#315d43','#446d46','#597e48','#709056','#879b58'].map(c=>foliageMaterial(c,this.controls.target));const geo=pineGeometry(),crown=crownGeometry(),trunk=new T.CylinderGeometry(.12,.21,1,14);
  for(const treeData of forestLayout()){const {position:{x,y:z},height:h,color,rotation,pine,id}=treeData;const y=elevation(x,z),m=leafM[color],depleted=this.depletedTrees?.has(id);const tree=new T.Group();tree.position.set(x,y,z);tree.rotation.y=rotation;forestGroup.add(tree);const t=mesh(trunk,trunkM,[0,depleted?.13:h*.4,0],tree);t.scale.y=depleted?.26:h*.8;
   if(depleted)continue;
   if(pine){for(let j=0;j<3;j++){const c=mesh(geo,m,[0,h*(.20+j*.19),0],tree);c.scale.set(h*(.24-j*.05),h*.47,h*(.24-j*.05));}}else{const c=mesh(crown,m,[0,h*.75,0],tree);c.scale.set(h*.36,h*.42,h*.33);for(let j=0;j<2;j++){const o=mesh(crown,m,[Math.sin(j*3)*h*.2,h*.65,Math.cos(j*3)*h*.15],tree);o.scale.setScalar(h*.29);}}
  }
  forestGroup.updateMatrixWorld(true);const batches=new Map();forestGroup.traverse(o=>{if(!o.isMesh)return;const g=(o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone()).applyMatrix4(o.matrixWorld);if(!batches.has(o.material))batches.set(o.material,[]);batches.get(o.material).push(g);});for(const[m,geometries]of batches){const combined=mergeGeometries(geometries);this.forestMeshes.push(mesh(combined,m,[0,0,0],this.scene));geometries.forEach(g=>g.dispose());}this.scene.remove(forestGroup);
 }
 camp(){const rnd=seeded(23),ground=elevation(CAMP.shelter.x,CAMP.shelter.y);this.shelter=new T.Group();this.shelter.position.set(CAMP.shelter.x,ground,CAMP.shelter.y);this.shelter.rotation.y=CAMP.shelter.rotation;this.scene.add(this.shelter);const wood=mat('#7e6242'),roof=mat('#72684a');
  for(const z of [-1.45,1.45]){branch(this.shelter,[-1.8,0,z],[0,3,z],.105,wood);branch(this.shelter,[0,3,z],[1.8,0,z],.105,wood);}branch(this.shelter,[0,3,-1.8],[0,3,1.8],.13,wood);
  for(const side of [-1,1]){const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute([0,3,-1.7,side*1.95,.13,-1.7,0,3,1.7,side*1.95,.13,-1.7,side*1.95,.13,1.7,0,3,1.7],3));g.computeVertexNormals();mesh(g,mat('#7d7551',{side:T.DoubleSide}),[0,0,0],this.shelter);for(let j=0;j<18;j++)branch(this.shelter,[side*.07,2.95,-1.7+j*.2],[side*1.96,.16,-1.7+j*.2],.055,roof);}
  this.fire=new T.Group();this.fire.position.set(CAMP.fire.x,elevation(CAMP.fire.x,CAMP.fire.y),CAMP.fire.y);this.scene.add(this.fire);for(let i=0;i<10;i++){const ang=i/10*Math.PI*2;const s=mesh(new T.DodecahedronGeometry(.23,0),mat('#787969'),[Math.sin(ang)*.8,.12,Math.cos(ang)*.8],this.fire);s.scale.set(1,.6,1);}for(let i=0;i<3;i++){const l=mesh(new T.CylinderGeometry(.12,.14,1.25,6),mat('#4f3e2d'),[0,.17,0],this.fire);l.rotation.z=Math.PI/2;l.rotation.y=i*Math.PI/3;}
  this.flames=new T.Group();this.fire.add(this.flames);for(let i=0;i<5;i++){const f=mesh(new T.ConeGeometry(.15+i*.055,.7+i*.13,5),new T.MeshBasicMaterial({color:i%2?'#ffe399':'#ee993e',transparent:true,opacity:.8}),[(rnd()-.5)*.55,.45,(rnd()-.5)*.55],this.flames);f.userData.phase=rnd()*6;}
  this.fireLight=new T.PointLight('#ffb35e',2,12);this.fireLight.position.set(0,1.2,0);this.fire.add(this.fireLight);
  // The existing fallen oak, stones and clay correspond to server locations.
  const log=new T.Group();log.position.set(59,elevation(59,29)+.3,29);log.rotation.y=.3;this.scene.add(log);branch(log,[-1.3,0,0],[1.3,0,0],.36,mat('#6e5338'));branch(log,[.3,0,0],[.8,.35,.8],.11,wood);
  for(let i=0;i<14;i++){const x=73+(rnd()-.5)*4,z=28+(rnd()-.5)*3,o=mesh(new T.IcosahedronGeometry(.25+rnd()*.55,0),mat(i%2?'#8b9589':'#a6aa91'),[x,elevation(x,z)+.1,z],this.scene);o.scale.y=.7;}
  // Clay is an exposed sloping bank meeting the waterline, not a pile in camp.
  const clayPos=[],clayIdx=[];for(let i=0;i<16;i++){const x=81+i*.62,z=riverY(x);clayPos.push(x,-.15,z+1.25,x,elevation(x,z+3.0)+.02,z+3.0);if(i<15){const k=i*2;clayIdx.push(k,k+2,k+1,k+1,k+2,k+3);}}const cg=new T.BufferGeometry();cg.setAttribute('position',new T.Float32BufferAttribute(clayPos,3));cg.setIndex(clayIdx);cg.computeVertexNormals();mesh(cg,mat('#a77d5b'),[0,0,0],this.scene);
  this.berries=new T.Group();this.scene.add(this.berries);for(let i=0;i<14;i++){const x=29+(rnd()-.5)*4,z=31+(rnd()-.5)*4;const bush=mesh(new T.SphereGeometry(.55+rnd()*.4,16,12),mat('#416442',{flatShading:false}),[x,elevation(x,z)+.4,z],this.berries);for(let j=0;j<3;j++)mesh(new T.SphereGeometry(.075,5,4),mat('#b75749'),[x+(rnd()-.5)*.7,elevation(x,z)+.85,z+(rnd()-.5)*.7],this.berries);}
  const reedsM=mat('#a4a168');for(let i=0;i<50;i++){const x=7+rnd()*6,z=riverY(x)+1.3+rnd()*2;branch(this.scene,[x,elevation(x,z),z],[x+.1,elevation(x,z)+.8+rnd(),z],.025,reedsM);}
 }
 human(id,name){const person=createPerson(id,name);this.scene.add(person.group);const label=document.createElement('div');label.className='label';label.textContent=name;const em=document.createElement('em');label.append(em);document.querySelector('#labels').append(label);this.labels.set(id,label);return person;}
 animal(a){const model=createAnimal(a.species),g=model.root;g.userData.objectId=a.id;this.scene.add(g);
  const school=[];if(a.species==='fish'){const hit=new T.Mesh(new T.SphereGeometry(1,10,8),new T.MeshBasicMaterial({visible:false}));hit.position.set(0,.04,-.2);hit.scale.set(.42,.28,.72);g.add(hit);}if(a.species==='fish')for(let i=0;i<3;i++){const fish=createAnimal('fish');fish.root.position.set((i%2?-.25:.25),-.015,-.25-Math.floor(i/2)*.3);fish.root.scale.setScalar(.72+(i%2)*.1);g.add(fish.root);school.push(fish);}
  return {group:g,model,school,limbs:model.legs,kind:a.species,pos:null,target:null,walk:0};
 }
 animals(){}
 environment(){const rnd=seeded(73);this.clouds=new T.Group();this.scene.add(this.clouds);for(let i=0;i<12;i++){const g=new T.Group();g.position.set(rnd()*180-40,27+rnd()*12,-10+rnd()*50);for(let j=0;j<4;j++){const m=mesh(new T.IcosahedronGeometry(2+rnd()*3,1),new T.MeshLambertMaterial({color:'#e4e9d7',transparent:true,opacity:.28,depthWrite:false}),[j*3,rnd(),rnd()*2],g);m.scale.set(1,.36,.68);m.castShadow=false;}this.clouds.add(g);}
  const rnd2=seeded(818),g=new T.BufferGeometry(),pos=[];for(let i=0;i<300;i++)pos.push(rnd2()*105,5+rnd2()*24,rnd2()*80);g.setAttribute('position',new T.Float32BufferAttribute(pos,3));this.rain=new T.Points(g,new T.PointsMaterial({color:'#d6eeee',size:.11,transparent:true,opacity:.6}));this.scene.add(this.rain);this.rain.visible=false;
 }
 accept(frame){this.naturalView.update(frame);this.settlementView.update(frame.settlement,frame.agents);const depleted=(frame.settlement?.trees||[]).filter(t=>t.remaining===0).map(t=>t.id),treeKey=depleted.join(',');if(treeKey!==this.treeKey){this.treeKey=treeKey;this.depletedTrees=new Set(depleted);if(depleted.length)this.forest();}if(this.berries){let fruit=0;for(const m of this.berries.children)if(m.geometry.parameters?.radius===.075)m.visible=fruit++<(frame.resources?.berries||0)*3;}this.updateGround(frame.groundRecent||[]);this.frame=frame;this.receivedAt=performance.now();for(const a of frame.agents){let e=this.entities.get(a.id);if(!e){e=this.human(a.id,a.name);this.entities.set(a.id,e);}this.setTarget(e,a.coordinates);updateCargo(e,a.inventory);e.action=personAction(a.task);e.phase=a.motion?(a.motion.speed>.02?'travel':a.task?.phase==='travel'?'waiting':'work'):a.task?.phase;if(a.task?.actionId==='drink'&&a.task.interactionReady===false)e.phase='waiting';e.facing=a.motion?.facing;this.labels.get(a.id).querySelector('em').textContent=a.task?.actionId==='explore'?'Exploring':a.task?.phase==='travel'?'Walking':a.task?.interactionReady===false&&a.task?.phase==='work'?'Waiting for water access':a.task?.label||'Observing';}
  const wildlifeIds=new Set(frame.wildlife.map(a=>a.id));for(const [id,e] of this.entities)if(e.kind!=='human')e.group.visible=wildlifeIds.has(id);
  for(const a of frame.wildlife){let e=this.entities.get(a.id);if(!e){e=this.animal(a);this.entities.set(a.id,e);}e.group.visible=true;this.setTarget(e,a.position);e.behavior=a.behavior;e.mode=a.mode||(/graz|feed/.test(a.behavior)?'graze':'idle');e.facing=a.motion?.facing;e.phase=(a.motion?.speed??0)>.02?'travel':'work';}
  this.shelter.visible=!!frame.structures.shelter;this.flames.visible=!!frame.structures.fire;this.fireLight.visible=!!frame.structures.fire;this.rain.visible=frame.weather==='rain';const daylight=Math.max(0,Math.sin((frame.hour+(frame.minute||0)/60-6)/14*Math.PI));this.sun.intensity=.24+daylight*2.9;this.ambient.intensity=.9+daylight*1.2;this.sun.color.set(daylight<.05?'#a8cbe7':frame.hour>17?'#ffd6a0':'#fff0cc');const sky=new T.Color('#263e56').lerp(new T.Color('#98bbb7'),daylight);this.scene.background.copy(sky);this.scene.fog.color.copy(sky);this.renderer.toneMappingExposure=.95+daylight*.21;
 }
 addHistory(geometry){this.updateGround(geometry.groundWear||[]);}
 updateGround(cells){if(!this.groundWear){const geometry=new T.CircleGeometry(.18,7);geometry.rotateX(-Math.PI/2);this.groundWear=new T.InstancedMesh(geometry,mat('#9c9979',{transparent:true,opacity:.23,depthWrite:false}),1600);this.groundWear.count=0;this.groundWear.receiveShadow=true;this.groundWear.frustumCulled=false;this.scene.add(this.groundWear);this.groundCells=new Map();this.groundKeys=[];this.groundCursor=0;}
  const dummy=new T.Object3D();for(const c of cells){const key=`${c.x},${c.y}`;let index=this.groundCells.get(key);if(index===undefined){index=this.groundCursor++%1600;const old=this.groundKeys[index];if(old)this.groundCells.delete(old);this.groundKeys[index]=key;this.groundCells.set(key,index);}dummy.position.set(c.x,elevation(c.x,c.y)+.025,c.y);dummy.rotation.set(0,(c.x*7+c.y*11)%6.28,0);const spread=.65+Math.min(1.7,Math.log2(c.uses+1)*.32);dummy.scale.set(spread,1,spread*.7);dummy.updateMatrix();this.groundWear.setMatrixAt(index,dummy.matrix);}this.groundWear.count=Math.min(1600,this.groundCursor);this.groundWear.instanceMatrix.needsUpdate=true;
 }
 setTarget(e,p){const next=new T.Vector3(p.x,e.kind==='fish'?-.29:this.settlementView.elevationAt(p.x,p.y),p.y);if(!e.target){e.group.position.copy(next);e.pos=next.clone();}else e.pos=e.group.position.clone();e.target=next;e.targetTime=performance.now();}
 animate(now){requestAnimationFrame(this.animate);const dt=Math.min(.05,(now-this.last)/1000);this.last=now;this.elapsed+=dt;const t=this.elapsed,fresh=now-this.receivedAt<2000&&!['persistence-blocked','error'].includes(this.frame?.runtime?.status);
  this.waterMat.uniforms.time.value=t;this.clouds.position.x=Math.sin(t*.005)*5;this.flames.children.forEach(f=>{f.scale.y=1+Math.sin(t*9+f.userData.phase)*.18;f.rotation.y=t*.8;});
  if(this.rain.visible){const p=this.rain.geometry.attributes.position;for(let i=0;i<p.count;i++){let y=p.getY(i)-dt*16;if(y<0)y=26;p.setY(i,y);}p.needsUpdate=true;}
  const labelPositions=[];for(const[id,e]of this.entities){if(!e.target)continue;const before=e.group.position.clone();e.group.position.lerpVectors(e.pos,e.target,clamp((now-e.targetTime)/100,0,1));const delta=e.group.position.clone().sub(before);const walking=fresh&&e.phase==='travel';if(delta.length()>.001){const yaw=Math.atan2(delta.x,delta.z);let diff=yaw-e.group.rotation.y;while(diff>Math.PI)diff-=Math.PI*2;while(diff< -Math.PI)diff+=Math.PI*2;e.group.rotation.y+=diff*Math.min(1,dt*10);}if(delta.length()<=.001&&Number.isFinite(e.facing)){const diff=Math.atan2(Math.sin(e.facing-e.group.rotation.y),Math.cos(e.facing-e.group.rotation.y));e.group.rotation.y+=diff*Math.min(1,dt*8);}e.walk+=walking?dt*9:0;if(e.kind==='human'){if(e.action==='drink'){e.waterPoint??=new T.Vector3();const x=e.group.position.x,z=riverY(x),bank=Math.sign(e.group.position.z-z)||1;e.waterPoint.set(x,-.105,z+bank*(CREEK_HALF_WIDTH-.07));}animatePerson(e,t,dt,walking,fresh);}else if(fresh){const mode=!walking&&['flee','withdraw','roam','associate','water','cover'].includes(e.mode)?'alert':e.mode;animateAnimal(e.model,t,mode,dt);e.school?.forEach((fish,i)=>animateAnimal(fish,t+i*.4,mode,dt));}
   if(e.kind==='human'){const p=e.group.position.clone().add(new T.Vector3(0,2.65,0)).project(this.camera),label=this.labels.get(id);const x=(p.x*.5+.5)*innerWidth;let y=(-p.y*.5+.5)*innerHeight;const visible=p.z<1&&Math.abs(p.x)<1&&Math.abs(p.y)<1;if(visible){for(const prev of labelPositions)if(Math.abs(prev.x-x)<185&&Math.abs(prev.y-y)<48)y=prev.y-50;labelPositions.push({x,y});}label.style.transform=`translate(-50%,-100%) translate(${x}px,${y}px)`;label.style.display=visible?'block':'none';}
  }
  if(this.focus){const e=this.entities.get(this.focus)||this.settlementView.objects.get(this.focus)||this.naturalView.objects.get(this.focus);if(e){const shift=e.group.position.clone().sub(this.controls.target).multiplyScalar(Math.min(1,dt*3));this.controls.target.add(shift);this.camera.position.add(shift);}}
  this.controls.update();const cameraFloor=elevation(this.camera.position.x,this.camera.position.z)+.75;if(this.camera.position.y<cameraFloor){this.camera.position.y=cameraFloor;this.controls.update();}this.faceLight.position.copy(this.camera.position);this.faceLight.target.position.copy(this.controls.target);this.renderer.render(this.scene,this.camera);
 }
}
