export function progressRatio(a){const t=a.task;if(!t||t.actionId==='reconsider')return 0;if(['exploration','return_warmth'].includes(t.progress?.kind))return Math.min(1,t.progress.distance/t.progress.targetDistance);return t.phase==='travel'?0:Math.min(1,(t.workMinutes||0)/(t.requiredMinutes||1));}
export function progressText(a){const t=a.task;if(!t)return 'Choosing the next action.';if(t.actionId==='reconsider')return 'Looking for useful work; available for conversation or a game.';if(t.actionId==='drink'&&t.phase==='work'&&t.interactionReady===false)return 'Waiting for a reachable place at the water’s edge.';if(t.phase==='planning')return 'Finding a safe walking route to a known camp.';if(t.progress?.kind==='return_warmth')return `${Math.floor(t.progress.distance)} m walked toward ${t.progress.camp} · returning to recover warmth`;if(a.restSupport&&t.phase==='work')return `${a.restSupport.description} · ${Math.round(a.restSupport.score)}/100 resting comfort · ${Math.round(progressRatio(a)*100)}% complete.`;if(t.progress?.kind==='hand_game')return `${t.progress.rounds} / ${t.progress.totalRounds} rounds · ${t.progress.players[0]} ${t.progress.scores[0]} – ${t.progress.scores[1]} ${t.progress.players[1]}${t.progress.lastRound?' · '+t.progress.lastRound.signs.join(' vs '):''}`;if(t.progress?.kind==='exploration')return `${Math.floor(t.progress.distance)} m walked while exploring · ${t.progress.cells} ground areas visited · ${t.progress.newCells??0} unfamiliar · ${t.progress.discoveries??0} resource discoveries`;return t.phase==='travel'?'Walking to where this task can be performed.':`${Math.round(progressRatio(a)*100)}% of this task complete.`;}
export function taskExplanation(a){const t=a.task;if(!t)return {text:'Considering current needs and available actions.',note:''};
 if(t.source==='ai'&&t.decisionSummary)return {text:t.decisionSummary,note:`Decision for this task · ${t.model?.split('/').at(-1)||'language model'}`};
 if(t.reason)return {text:t.reason,note:'Current task · autonomous rules using needs and remembered experience'};
 if(t.job?.projectId)return {text:`${t.label}. ${t.phase==='travel'?'Carrying out the trip required by the design.':'Working at the physical site with carried materials.'}`,note:'AI-designed construction · movement, materials and labor follow simulation rules.'};
 if(t.actionId==='explore')return {text:'Walking through less-visited parts of the valley. Exploration progress comes from actual movement; places are discovered only when reached nearby.',note:'Current task · autonomous rules'};
 if(t.actionId==='drink')return {text:t.interactionReady===false&&t.phase==='work'?'Waiting for safe access to the creek. No drinking progress is being credited.':t.phase==='travel'?'Moving to a reachable spot at the creek’s edge. Drinking can begin only when water is within reach.':'Drinking at the creek’s edge. Hydration increases only while water is within reach.',note:'Current task · autonomous rules'};
 return {text:`${t.label}. ${t.phase==='travel'?'Travelling to the task location.':'Carrying out the current task.'}`,note:t.source==='ai'?'AI-directed task':'Selected by autonomous rules using needs, resources and remembered experience.'};
}
