from pathlib import Path
import re

# Real traces and real animals enter the ordinary physical affordance view.
p=Path('engine/affordances.js'); src=p.read_text()
src=src.replace("import{ensureWorldModel,worldObjectForZone,findWorldObject,activeWorldObjects,objectSnapshot}from'./world-model.js';", "import{ensureWorldModel,worldObjectForZone,findWorldObject,activeWorldObjects,objectSnapshot}from'./world-model.js';\nimport{visibleWildlifeForAgent,visibleWildlifeTracesForAgent}from'./ecology.js';",1)
old=re.search(r" const tracks=findWorldObject\(w,'OBJ-TRACKS-001'\);.*?if\(w\.ecology\.tuberPatch",src,re.S)
if not old: raise SystemExit('legacy ecology affordance block missing')
new=""" const traces=visibleWildlifeTracesForAgent(w,a,13);for(const t of traces){const freshness=(t.clarity||0)>.7?'fresh':'fading';o.push(O(`wildlife_trace:${t.id}`,`${t.species} tracks`,'feature',a.position,1,['tracks','animal-sign','directionalSign',t.species,freshness],{traceId:t.id,wildlifeId:t.sourceId,trace:t,supports:['inspect','follow','search','test']}))}
 const living=visibleWildlifeForAgent(w,a,18);for(const x of living){const supports=['inspect','follow','search','test'];const strikeRange=x.species==='fish'?4:x.species==='bear'?1.8:3;if(x.distance<=strikeRange)supports.push('strike');o.push(O(`wildlife:${x.id}`,x.label,'creature',a.position,1,['animal','mobile',x.species,'alert',x.behavior],{wildlifeId:x.id,wildlife:x,supports}))}
 const ac=a.coordinates;for(const animal of w.ecologySystem?.wildlife||[]){if(!animal.carcass?.fresh||!ac)continue;const dd=Math.hypot(ac.x-animal.position.x,ac.y-animal.position.y);if(dd>7)continue;o.push(O(`carcass:${animal.id}`,`${animal.label} carcass`,'creature_remains',a.position,animal.carcass.portions||1,['animal-remains','meat','raw','cuttable',animal.species],{carcassId:animal.id,wildlifeId:animal.id,supports:['inspect','cut','test']}))}
 if(w.ecology.tuberPatch"""
src=src[:old.start()]+new+src[old.end():]
p.write_text(src)

# Replace the legacy generic animal_tracks/game_trail/small_game resolver with
# source-linked traces and persistent animal entities. Keep tuber foraging intact.
p=Path('engine/physical-ecology.js')
p.write_text("""import{remember,learnSkill,recordDiscovery,noise,invConsume,clamp}from'./core.js';

const d=(a,b)=>Math.hypot((a?.x||0)-(b?.x||0),(a?.y||0)-(b?.y||0));
const sharp=y=>['sharp_stone','bound_sharp_tool'].includes(y?.id)||y?.properties?.includes('sharp');
const traceId=x=>x?.traceId||String(x?.id||'').replace(/^wildlife_trace:/,'');
const wildlifeId=x=>x?.wildlifeId||String(x?.id||'').replace(/^(wildlife|carcass):/,'');
const findTrace=(w,x)=>(w.ecologySystem?.traces||[]).find(t=>t.id===traceId(x));
const findAnimal=(w,x)=>(w.ecologySystem?.wildlife||[]).find(t=>t.id===wildlifeId(x));
function nearestZone(w,p){const choices=(w.worldModel?.objects||[]).filter(o=>!o.parentId&&o.state?.active!==false&&o.physical?.navigable&&o.zone!=='edge'&&o.position);if(!choices.length)return null;return choices.reduce((best,o)=>d(p,o.position)<d(p,best.position)?o:best,choices[0])}
function moveNear(w,a,p){const z=nearestZone(w,p);if(!z)return null;a.position=z.zone;a.coordinates={...z.position};return z}
function skill(a){return Number(a.skills?.['track-reading']||0)}
function toolBonus(y,species){const id=y?.id||'';if(species==='rabbit')return id==='bound_sharp_tool'?.38:id==='pointed_pole'?.27:id==='sharp_stone'?.10:0;if(species==='deer')return id==='bound_sharp_tool'?.30:id==='pointed_pole'?.22:id==='sharp_stone'?.04:0;if(species==='fish')return id==='bound_sharp_tool'?.31:id==='pointed_pole'?.26:id==='sharp_stone'?.04:0;if(species==='bear')return id==='bound_sharp_tool'?.08:id==='pointed_pole'?.04:0;return 0}
function strikeBase(species){return species==='rabbit'?.11:species==='fish'?.09:species==='deer'?.04:species==='bear'?.01:.05}
function carcassPortions(species){return species==='rabbit'?2:species==='deer'?8:species==='bear'?12:1}

export function resolveEcology(w,a,p,x,y,n){let success=false,detail='';
 const trace=findTrace(w,x),animal=findAnimal(w,x);
 if(trace&&['inspect','test'].includes(p.verb)){const freshness=Math.round((trace.clarity||0)*100),age=trace.ageHours||0;success=true;detail=`${a.name} studies the ${trace.species} tracks. They are about ${freshness}% clear and roughly ${age} world-hour${age===1?'':'s'} old.`;remember(w,a,`These ${trace.species} tracks were left by a real animal moving through the basin; their clarity is about ${freshness}%.`,{importance:6,tags:['tracks','animals',trace.species,'observation'],source:`wildlife-trace:${trace.id}`,confidence:Math.max(.55,trace.clarity||.6)});if(n>=2)learnSkill(w,a,'track-reading',Math.min(1,.45+n*.1),'Repeated inspection makes direction, species, and freshness easier to distinguish in animal sign.');return{handled:true,success,detail}}
 if(trace&&p.verb==='search'){const q=.26+(trace.clarity||0)*.38+skill(a)*.22-(w.weather==='rain'?.12:0);if(noise(w.day,w.hour,410+n+a.id.length)<q){success=true;detail=`${a.name} searches around the ${trace.species} sign and separates the freshest impressions from older noise.`;a.skills['track-reading']=Math.max(skill(a),Math.min(1,.28+n*.08));remember(w,a,`Searching around ${trace.species} sign can reveal which impressions are freshest before following them.`,{importance:6,tags:['tracks','search',trace.species],confidence:.82})}else detail=`${a.name} searches around the ${trace.species} tracks, but overlapping ground sign remains ambiguous.`;return{handled:true,success,detail}}
 if(trace&&p.verb==='follow'){const source=(w.ecologySystem?.wildlife||[]).find(q=>q.id===trace.sourceId&&q.active),q=.24+(trace.clarity||0)*.36+skill(a)*.28-(w.weather==='rain'?.14:0);if(noise(w.day,w.hour,520+n+a.id.length)<q){success=true;const target=source?.position||trace.position,z=moveNear(w,a,target);detail=source?`${a.name} follows the freshest ${trace.species} sign toward ${z?.label||'nearby cover'}. The actual animal that made these tracks is still somewhere ahead.`:`${a.name} follows the ${trace.species} sign toward ${z?.label||'the next patch of cover'}, though the animal itself is no longer nearby.`;a.skills['track-reading']=Math.max(skill(a),Math.min(1,.36+n*.09));remember(w,a,`Following fresh ${trace.species} tracks moved me toward the animal that actually made them.`,{importance:8,tags:['tracks','animals','following',trace.species],source:`wildlife:${trace.sourceId}`,confidence:.88});recordDiscovery(w,a,'source-linked-tracking','Source-linked tracking','A real animal left persistent sign, and following that sign narrowed the distance to its current path.','Animal movement can now create information that changes later agent movement.')}else{detail=w.weather==='rain'?`${a.name} follows the ${trace.species} tracks until rain breaks the readable sequence.`:`${a.name} follows the ${trace.species} sign until overlapping impressions become ambiguous.`;remember(w,a,`Track-follow attempt ${n}: freshness and continuity matter more than simply knowing tracks exist.`,{importance:5,tags:['tracks','experiment',trace.species],confidence:.72})}return{handled:true,success,detail}}
 if(animal&&x.id?.startsWith('wildlife:')&&p.verb==='inspect'){success=true;detail=`${a.name} watches the ${animal.label}. It is ${animal.behavior||animal.activity}, with fear around ${Math.round(animal.fear||0)}%.`;remember(w,a,`I watched a ${animal.label} while it was ${animal.behavior||animal.activity}.`,{importance:5,tags:['animal','wildlife',animal.species,'observation'],source:`wildlife:${animal.id}`,confidence:.9});return{handled:true,success,detail}}
 if(animal&&x.id?.startsWith('wildlife:')&&p.verb==='follow'){if(!animal.active)return{handled:true,success:false,detail:`${animal.label} is no longer moving.`};const z=moveNear(w,a,animal.position);success=true;detail=`${a.name} moves carefully toward the ${animal.label}'s current area near ${z?.label||'cover'}, without controlling where the animal goes next.`;remember(w,a,`Moving after a visible ${animal.species} can close distance, but the animal keeps its own behavior and may flee.`,{importance:6,tags:['animal','following',animal.species],confidence:.84});return{handled:true,success,detail}}
 if(animal&&x.id?.startsWith('wildlife:')&&p.verb==='strike'){if(!animal.active)return{handled:true,success:false,detail:`${animal.label} is no longer an active target.`};const range=d(a.coordinates,animal.position),max=animal.species==='fish'?4:animal.species==='bear'?1.8:3;if(range>max)return{handled:true,success:false,detail:`${a.name} cannot make a controlled strike; the ${animal.label} is still ${range.toFixed(1)} world units away.`};const chance=clamp(strikeBase(animal.species)+toolBonus(y,animal.species)+skill(a)*.07,0,.72);if(noise(w.day,w.hour,905+n+a.id.length)<chance){success=true;if(animal.species==='fish'){a.inventory.rawMeat=(a.inventory.rawMeat||0)+1;animal.fear=100;animal.behavior='scattered';animal.activity='flee';detail=`${a.name} times a physical strike into the fish school and takes one fish; the rest of the school scatters.`;remember(w,a,'A pointed or bound tool can sometimes take an individual fish when the school comes within reach.',{importance:9,tags:['fish','food','tool','fishing'],confidence:.9});recordDiscovery(w,a,'spear-fishing','Fish taken from the creek','A physical strike took one fish from a real moving school without removing the school itself.','The creek can become a food source through timing, proximity, and suitable tools.')}else{animal.active=false;animal.activity='still';animal.behavior='down';animal.carcass={fresh:true,portions:carcassPortions(animal.species),created:{day:w.day,hour:w.hour},processed:false};detail=`${a.name}'s strike succeeds. The ${animal.label} remains at this location as a physical carcass; usable meat has not been recovered yet.`;remember(w,a,`A successful strike on ${animal.species} does not turn directly into food; the carcass still has to be processed with a cutting edge.`,{importance:10,tags:['animals','tool','hunting','carcass',animal.species],confidence:.94});recordDiscovery(w,a,`animal-carcass-${animal.species}`,`${animal.species} carcass`,`A real ${animal.species} was physically brought down and persisted as remains rather than becoming instant inventory.`,`Animal food now requires a second processing step.`)}}else{animal.fear=100;animal.activity='flee';animal.behavior='startled';if(animal.species==='bear'){a.needs.energy=clamp(a.needs.energy-12);a.needs.warmth=clamp(a.needs.warmth-3);detail=`${a.name} fails the close strike. The black bear reacts violently enough to force an exhausting retreat before moving away.`;remember(w,a,'A close failed attempt against a bear is dangerously different from pursuing small game.',{importance:10,tags:['bear','danger','animals','warning'],confidence:.98})}else{detail=`${a.name} strikes too late; the ${animal.label} bolts away under its own fear response.`;remember(w,a,`Animal-strike attempt ${n}: distance, timing, and tool control matter against a moving ${animal.species}.`,{importance:7,tags:['animals','failure','tool',animal.species],confidence:.8})}}return{handled:true,success,detail}}
 if(animal&&x.id?.startsWith('carcass:')&&['inspect','test'].includes(p.verb)){success=true;detail=`${a.name} examines the ${animal.label} remains. Processing the carcass will require a controlled cutting edge.`;remember(w,a,`The ${animal.species} carcass contains usable tissue, but it must be cut and processed before it becomes food inventory.`,{importance:7,tags:['carcass','meat','processing',animal.species],confidence:.92});return{handled:true,success,detail}}
 if(animal&&x.id?.startsWith('carcass:')&&p.verb==='cut'){if(!animal.carcass?.fresh)return{handled:true,success:false,detail:`The ${animal.label} carcass no longer has recoverable fresh portions.`};if(!sharp(y))return{handled:true,success:false,detail:`${a.name} cannot process the carcass cleanly without a sharp cutting edge.`};const portions=animal.carcass.portions||1;a.inventory.rawMeat=(a.inventory.rawMeat||0)+portions;animal.carcass.fresh=false;animal.carcass.processed=true;animal.carcass.processedBy=a.id;success=true;detail=`${a.name} uses ${y.label} to process the ${animal.label} carcass and recovers ${portions} raw meat portion${portions===1?'':'s'}.`;remember(w,a,`A sharp edge can turn an animal carcass into recoverable raw meat; the meat still needs safe cooking.`,{importance:9,tags:['carcass','meat','processing','cutting'],confidence:.95});return{handled:true,success,detail}}
 if(p.verb==='search'&&x.id==='place:reeds'){const chance=.18+a.traits.curiosity*.15+Math.min(.22,n*.06);if(!w.ecology.tuberPatch&&noise(w.day,w.hour,401+n)<chance){w.ecology.tuberPatch=true;success=true;detail=`${a.name} searches the damp margin and notices disturbed soil around thick underground roots.`;remember(w,a,'The reed-marsh margin contains thick underground tubers; whether they are useful or edible is not yet known.',{importance:7,tags:['tuber','roots','foraging','unknown-food'],confidence:.83});recordDiscovery(w,a,'tuber-patch','Underground tuber patch','Careful searching revealed a recurring patch of thick underground roots.','A new material/food candidate exists, but its usefulness is unproven.')}else detail=`${a.name} searches the marsh margin, but finds no new usable resource this hour.`;return{handled:true,success,detail}}
 if(p.verb==='dig'&&x.id==='tuber_patch'){if(w.ecology.tubers>0){w.ecology.tubers--;a.inventory.tubers++;success=true;detail=`${a.name} digs beneath disturbed soil and lifts one thick tuber.`;remember(w,a,'Marsh-edge tubers can be dug up, but their safety as food remains uncertain.',{importance:6,tags:['tuber','foraging','unknown-food'],confidence:.82})}else detail=`${a.name} finds the tuber patch depleted for now.`;return{handled:true,success,detail}}
 if(p.verb==='test'&&x.id==='carried_tuber'){if(!invConsume(a,'tubers'))detail=`${a.name} no longer has the tuber to test.`;else if(w.ecology.tubersEdible){success=true;a.needs.hunger=clamp(a.needs.hunger+10);detail=`${a.name} cautiously tastes a small piece and waits; it proves starchy without immediate distress.`;learnSkill(w,a,'tuber-edible',1,'A cautious food test showed the marsh tuber is starchy and edible in small amounts.',{title:'Edible marsh tuber',detail:`${a.name} established through cautious testing that the underground tuber can serve as food.`,effect:'The marsh contains a second renewable food source beyond berries.'})}else{detail=`${a.name} tastes the tuber and rejects its bitter, irritating flesh.`;remember(w,a,'The marsh tuber tastes bitter and irritating; it should not be treated as food.',{importance:9,tags:['tuber','food','warning'],confidence:.95})}return{handled:true,success,detail}}
 return{handled:false,success:false,detail:''};
}
""")

# Live Threads should describe real sign rather than obsolete global booleans.
p=Path('engine/spectator.js'); src=p.read_text()
old="if(w.ecology.animalTracks&&!w.ecology.gameTrail&&w.agents.some(knowsTracks))t.push(thread('tracks','Animal tracks remain unresolved',66,'At least one agent knows about the marsh tracks, but nobody has yet converted that sign into a reliable trail.','mystery',w.agents.filter(knowsTracks).map(a=>a.id),['reeds']));if(w.ecology.gameTrail&&w.ecology.smallGame===0)t.push(thread('game-trail','A game trail is known',61,'The trail is real, but no animal is currently in sight. Waiting, following or preparing may change that.','opportunity',w.agents.filter(knowsGameTrail).map(a=>a.id),['reeds']));"
new="const freshTrace=(w.ecologySystem?.traces||[]).filter(x=>x.active&&(x.clarity||0)>.55).sort((a,b)=>(b.clarity||0)-(a.clarity||0))[0];if(freshTrace){const aware=w.agents.filter(a=>a.wildlifeTracksSeen?.[freshTrace.species]||knowsTracks(a));if(aware.length)t.push(thread(`tracks-${freshTrace.species}`,`Fresh ${freshTrace.species} sign persists`,58,`${freshTrace.species} tracks are still ${Math.round((freshTrace.clarity||0)*100)}% clear. They came from ${freshTrace.sourceId}, a real persistent animal in the basin.`,'mystery',aware.map(a=>a.id),[]))}"
if old not in src: raise SystemExit('legacy spectator track threads missing')
src=src.replace(old,new,1)
p.write_text(src)

# Legacy small-game counters no longer repopulate a second invisible animal system.
p=Path('engine/core.js'); src=p.read_text()
src=src.replace("if(w.ecology.gameTrail&&w.ecology.smallGame<2&&noise(w.day,w.hour,117)>.82)w.ecology.smallGame++", "// Persistent wildlife in ecologySystem replaces the legacy generic small-game counter.",1)
p.write_text(src)

# Renderer: a downed animal persists visibly until its carcass is processed.
p=Path('world-pixi-v11.js'); src=p.read_text()
old="function renderWildlife(){for(const a of current.ecologySystem?.wildlife||[]){if(!a.active)continue;const made=animalGraphics(a),p=wp(a.position);made.c.position.set(p.x,p.y);made.c._data=a;addWorld(made.c,p.y,7,{kind:`wildlife-${a.species}`,tier:'wildlife',sourceId:a.id,height:made.h});wildlifeSprites.set(a.id,made.c)}}"
new="function renderWildlife(){for(const a of current.ecologySystem?.wildlife||[]){if(!a.active&&!a.carcass?.fresh)continue;const made=animalGraphics(a),p=wp(a.position);made.c.position.set(p.x,p.y);made.c._data=a;if(!a.active&&a.carcass?.fresh){made.c._animal.g.rotation=-1.25;made.c._animal.g.alpha=.72;made.c._animal.name.alpha=.72;made.c._animal.name.text=`${a.label} remains`}addWorld(made.c,p.y,7,{kind:a.active?`wildlife-${a.species}`:`carcass-${a.species}`,tier:a.active?'wildlife':'ground-object',sourceId:a.id,height:made.h});wildlifeSprites.set(a.id,made.c)}}"
if old not in src: raise SystemExit('renderWildlife anchor missing')
src=src.replace(old,new,1)
src=src.replace("for(const a of current.ecologySystem?.wildlife||[]){const c=wildlifeSprites.get(a.id);if(!c)continue;", "for(const a of current.ecologySystem?.wildlife||[]){const c=wildlifeSprites.get(a.id);if(!c)continue;if(!a.active){c._animal?.name?.scale.set(1/camera.scale);continue;}",1)
p.write_text(src)

# Regression coverage: fake wildlife affordances must be gone and real tracks must be actionable.
p=Path('scripts/smoke-test.mjs'); src=p.read_text()
insert="""
const wildlifeWorld=migrateWorld(createWorld());tick(wildlifeWorld);const tracker=wildlifeWorld.agents[0];const trace=wildlifeWorld.ecologySystem.traces.find(x=>x.active);if(!trace)fail('Living wildlife did not leave a real trace during smoke test');tracker.coordinates={...trace.position};tracker.position='meadow';const wildlifeAff=buildAffordanceView(wildlifeWorld,tracker);const realTrace=wildlifeAff.objects.find(o=>o.id===`wildlife_trace:${trace.id}`);if(!realTrace||!realTrace.supports.includes('follow'))fail('Source-linked wildlife trace did not expose primitive follow affordance');if(wildlifeAff.objects.some(o=>['animal_tracks','game_trail','small_game'].includes(o.id)))fail('Legacy fake wildlife affordances are still exposed');
"""
marker="const toggleWorld=migrateWorld(createWorld());"
if marker not in src: raise SystemExit('smoke insertion marker missing')
src=src.replace(marker,insert+"\n"+marker,1)
p.write_text(src)
