// Phaser Living World QA · v1.3 diagnostic gate
import { chromium } from 'playwright';
import fs from 'node:fs';
import { migrateWorld, advanceEcology } from '../engine.js';

const base=process.env.BASE_URL||'http://127.0.0.1:4173/phaser.html';
fs.mkdirSync('phaser-qa',{recursive:true});
let state=migrateWorld(JSON.parse(fs.readFileSync('world/state.json','utf8')));
advanceEcology(state);
state.surfaceHistory={version:'surface-history-1',routes:[{id:'ROUTE-QA-VISUAL',key:'43,31|64,34',from:{x:43,y:31},to:{x:64,y:34},traversals:5,agents:{'agent-mara':3,'agent-ivo':2},firstUsed:{day:state.day,hour:Math.max(0,state.hour-5)},lastUsed:{day:state.day,hour:state.hour},lastActionId:'qa_walk'}],campWear:{uses:12,agents:{'agent-mara':7,'agent-ivo':5},lastUsed:{day:state.day,hour:state.hour}}};
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:412,height:915},deviceScaleFactor:1,isMobile:true,hasTouch:true});
const page=await context.newPage();
const errors=[],failures=[];
page.on('pageerror',e=>{const v=`pageerror: ${e.message}`;errors.push(v);console.error(v)});
page.on('console',m=>{if(m.type()==='error'){const v=`console: ${m.text()}`;errors.push(v);console.error(v)}});
await page.route(/raw\.githubusercontent\.com\/kyle8824\/chatgptfarm\/main\/world\/state\.json.*/,route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(state)}));
await page.goto(base,{waitUntil:'domcontentloaded',timeout:60000});
await page.waitForFunction(()=>window.ChatGPTFarmPhaserDebug?.snapshot()?.ready===true,{timeout:60000});
try{await page.waitForSelector('#phLoading.hidden',{state:'attached',timeout:10000})}catch(e){await page.screenshot({path:'phaser-qa/build-failure.png'});const snap=await page.evaluate(()=>window.ChatGPTFarmPhaserDebug?.snapshot?.()||null);fs.writeFileSync('phaser-qa/build-failure.json',JSON.stringify({snap,errors},null,2));await browser.close();throw new Error(`Phaser canonical state loaded but scene build never completed. ${errors.join(' | ')||'No browser error surfaced.'}`)}
await page.waitForTimeout(1200);
const snap=()=>page.evaluate(()=>window.ChatGPTFarmPhaserDebug.snapshot());
let s=await snap();
if(s.version!=='phaser-v1.6.1-living-space')failures.push(`wrong renderer: ${s.version}`);
if(!String(s.phaser||'').startsWith('3.'))failures.push(`Phaser failed to initialize: ${s.phaser}`);
if(s.agents!==2)failures.push(`expected 2 agents, got ${s.agents}`);
const expectedPresentWildlife=(state.ecologySystem?.wildlife||[]).filter(x=>x.active&&x.localPresence!==false).length;if(s.wildlife!==expectedPresentWildlife)failures.push(`renderer wildlife count drift: ${s.wildlife} != canonical ${expectedPresentWildlife}`);
if(s.trees<55)failures.push(`expected a forest, got ${s.trees} trees`);
if(s.treeWaterCollisions!==0)failures.push(`trees spawned in canonical water: ${s.treeWaterCollisions}`);
if((s.terrain?.water||0)<20||(s.terrain?.bank||0)<20||(s.terrain?.forest||0)<100)failures.push(`terrain occupancy is incomplete: ${JSON.stringify(s.terrain)}`);
if(s.movingEntities<1)failures.push('no entity has visible interpolated movement');if(!Number.isFinite(s.concealedWildlife))failures.push(`wildlife concealment state missing: ${s.concealedWildlife}`);const expectedRoutes=(state.surfaceHistory?.routes||[]).filter(r=>(r.traversals||0)>=2).length;if(s.livingWorld?.routeVisuals!==expectedRoutes||s.livingWorld?.canonicalRoutes!==expectedRoutes)failures.push(`travel-wear projection drift: rendered=${s.livingWorld?.routeVisuals} canonical=${expectedRoutes}`);if(s.livingWorld?.campWear!==12)failures.push(`camp-wear projection drift: ${s.livingWorld?.campWear}`);if((s.livingWorld?.campWearVisuals||0)<5||s.livingWorld?.campWearState?.uses!==12)failures.push(`camp wear visual projection missing: ${JSON.stringify(s.livingWorld?.campWearState)}`);const expectedResourceVisuals={stonesLoose:Math.round(13*Math.max(0,Math.min(1,(state.resources?.stones||0)/24))),reedsStanding:Math.round(28*Math.max(0,Math.min(1,(state.resources?.reeds||0)/18))),berryFruitingBushes:Math.round(9*Math.max(0,Math.min(1,(state.resources?.berries||0)/20))),clayRichness:+Math.max(0,Math.min(1,(state.resources?.clay||0)/10)).toFixed(2)};if(JSON.stringify(s.resourceVisualState)!==JSON.stringify(expectedResourceVisuals))failures.push(`resource landscape drift: ${JSON.stringify(s.resourceVisualState)} != ${JSON.stringify(expectedResourceVisuals)}`);if(!s.rangePresenceCounts||s.rangePresenceCounts.present!==expectedPresentWildlife)failures.push(`range presence projection missing or stale: ${JSON.stringify(s.rangePresenceCounts)}`);
const expectedDNA=state.dna?.[0]?.decision_id||null;if(!String(s.decisionDNA?.protocol||'').startsWith('Decision DNA'))failures.push(`Decision DNA projection missing: ${JSON.stringify(s.decisionDNA)}`);if(expectedDNA&&s.decisionDNA?.decisionId!==expectedDNA)failures.push(`renderer DNA drifted from canonical state: ${s.decisionDNA?.decisionId} != ${expectedDNA}`);if((s.agentArtModes||[]).length!==2||(s.agentArtModes||[]).some(x=>x!=='natural-procedural'))failures.push(`natural agent embodiment failed: ${JSON.stringify(s.agentArtModes)}`);if(s.campVisualMode!=='canonical-branch-camp-v1')failures.push(`canonical camp visual mode missing: ${s.campVisualMode}`);if(!s.lightCycle||s.lightCycle.hour!==state.hour)failures.push(`light cycle state missing or stale: ${JSON.stringify(s.lightCycle)}`);const wetExpected=+(state.environmentState?.surfaceWetness??.32).toFixed(3),levelExpected=+(state.environmentState?.creekLevel??.42).toFixed(3);if(s.weatherMemory?.surfaceWetness!==wetExpected||s.weatherMemory?.creekLevel!==levelExpected)failures.push(`weather memory projection drift: ${JSON.stringify(s.weatherMemory)} expected wet=${wetExpected} level=${levelExpected}`);if(!s.habitatDetail||s.habitatDetail.meadow<100||s.habitatDetail.forest<20)failures.push(`habitat detail missing: ${JSON.stringify(s.habitatDetail)}`);const expectedSigns=(state.ecologySystem?.signs||[]).filter(x=>x.active&&(x.clarity??0)>.34&&(x.ageHours??0)<=30).length;if(s.livingWorld?.signVisuals!==expectedSigns||s.livingWorld?.canonicalSigns!==expectedSigns)failures.push(`ecological sign projection drift: rendered=${s.livingWorld?.signVisuals} canonical=${expectedSigns}`);const expectedTracks=(state.ecologySystem?.traces||[]).filter(t=>t.active&&(t.clarity??0)>.38&&(t.ageHours??0)<=14&&(t.species!=='rabbit'||(t.clarity??0)>.55)).length;if(s.livingWorld?.trackVisuals!==expectedTracks||s.livingWorld?.canonicalTracks!==expectedTracks)failures.push(`wildlife trace projection drift: rendered=${s.livingWorld?.trackVisuals} canonical=${expectedTracks}`);const expectedCue=state.dna?.[0]?.decision_id||null;if(expectedCue&&s.livingWorld?.decisionCueId!==expectedCue)failures.push(`Decision DNA world cue drift: ${s.livingWorld?.decisionCueId} != ${expectedCue}`);
await page.screenshot({path:'phaser-qa/mobile-auto.png'});const savedResources={...state.resources};state.meta.tickNumber=Number(state.meta.tickNumber||0)+31;Object.assign(state.resources,{berries:0,reeds:0,stones:0,clay:0});await page.evaluate(()=>window.ChatGPTFarmPhaserDebug.reload());await page.waitForTimeout(650);let depleted=await snap();if(depleted.resourceVisualState?.stonesLoose!==0||depleted.resourceVisualState?.reedsStanding!==0||depleted.resourceVisualState?.berryFruitingBushes!==0||depleted.resourceVisualState?.clayRichness!==0)failures.push(`depleted resources remained visually full: ${JSON.stringify(depleted.resourceVisualState)}`);await page.screenshot({path:'phaser-qa/mobile-resource-depletion-proof.png'});Object.assign(state.resources,savedResources);state.meta.tickNumber++;await page.evaluate(()=>window.ChatGPTFarmPhaserDebug.reload());await page.waitForTimeout(650);s=await snap();if(JSON.stringify(s.resourceVisualState)!==JSON.stringify(expectedResourceVisuals))failures.push(`resource landscape failed to recover after canonical quantities restored: ${JSON.stringify(s.resourceVisualState)}`);

for(const [name,id] of [['MARA','agent-mara'],['IVO','agent-ivo']]){
 await page.getByRole('button',{name,exact:true}).click();await page.waitForTimeout(600);s=await snap();if(s.camera.mode!==id)failures.push(`${name} camera did not enter follow mode`);await page.screenshot({path:`phaser-qa/mobile-${name.toLowerCase()}.png`});
}
await page.getByRole('button',{name:'AUTO',exact:true}).click();await page.waitForTimeout(350);
const habitatDeer=state.ecologySystem?.wildlife?.find(x=>x.active&&x.localPresence!==false&&x.species==='deer');if(habitatDeer){await page.evaluate(({x,y})=>window.ChatGPTFarmPhaserDebug.focusWorldUnit(x,y,.95),habitatDeer.position);await page.waitForTimeout(250);await page.screenshot({path:'phaser-qa/mobile-wildlife-habitat.png'});}

let before=(await snap()).positions['W-DEER-001'];
if(!before)failures.push('missing deer for movement QA');
else{
 const targetWorld={x:45,y:36},targetPx={x:targetWorld.x*24,y:(100-targetWorld.y)*24};
 await page.evaluate(({to})=>window.ChatGPTFarmPhaserDebug.simulateMove('W-DEER-001',to,2400),{to:targetWorld});
 await page.waitForTimeout(950);const mid=(await snap()).positions['W-DEER-001'];
 await page.waitForTimeout(1900);const end=(await snap()).positions['W-DEER-001'];
 const d0=Math.hypot(mid.x-before.x,mid.y-before.y),d1=Math.hypot(mid.x-targetPx.x,mid.y-targetPx.y),de=Math.hypot(end.x-targetPx.x,end.y-targetPx.y);
 if(!(d0>5&&d1>5))failures.push(`deer did not visibly interpolate through a midpoint (${d0.toFixed(1)}, ${d1.toFixed(1)})`);
 if(de>4)failures.push(`deer did not reach visible movement target (${de.toFixed(1)}px)`);
 await page.evaluate(()=>window.ChatGPTFarmPhaserDebug.focusWorldUnit(45,36,.95));await page.waitForTimeout(250);await page.screenshot({path:'phaser-qa/mobile-movement-proof.png'});
}

await page.evaluate(()=>window.ChatGPTFarmPhaserDebug.focusWorldUnit(50,19,.92));await page.waitForTimeout(300);await page.screenshot({path:'phaser-qa/mobile-creek.png'});state.environmentState={surfaceWetness:.86,creekLevel:.73,lastRainAt:{day:state.day,hour:Math.max(0,state.hour-2)},hoursSinceRain:2};state.weather='clear';state.meta.tickNumber++;await page.evaluate(()=>window.ChatGPTFarmPhaserDebug.reload());await page.waitForTimeout(650);const wetAfter=await snap();if(wetAfter.weatherMemory?.surfaceWetness<.8||wetAfter.weatherMemory?.visuals<3)failures.push(`wet aftermath did not render from canonical weather memory: ${JSON.stringify(wetAfter.weatherMemory)}`);await page.evaluate(()=>window.ChatGPTFarmPhaserDebug.focusWorldUnit(50,19,.92));await page.waitForTimeout(200);await page.screenshot({path:'phaser-qa/mobile-after-rain.png'});state.environmentState={surfaceWetness:.24,creekLevel:.43,lastRainAt:{day:Math.max(1,state.day-1),hour:state.hour},hoursSinceRain:24};state.meta.tickNumber++;await page.evaluate(()=>window.ChatGPTFarmPhaserDebug.reload());await page.waitForTimeout(650);const dryAfter=await snap();if(!(dryAfter.weatherMemory?.surfaceWetness<wetAfter.weatherMemory?.surfaceWetness&&dryAfter.weatherMemory?.visuals<wetAfter.weatherMemory?.visuals))failures.push(`weather-memory visuals did not recede as canonical ground dried: wet=${JSON.stringify(wetAfter.weatherMemory)} dry=${JSON.stringify(dryAfter.weatherMemory)}`);
await page.evaluate(()=>window.ChatGPTFarmPhaserDebug.focusWorldUnit(64,34,1.05));await page.waitForTimeout(300);await page.screenshot({path:'phaser-qa/mobile-camp.png'});
await page.evaluate(()=>window.ChatGPTFarmPhaserDebug.focusWorldUnit(14,29,1.0));await page.waitForTimeout(300);await page.screenshot({path:'phaser-qa/mobile-forest.png'});

state=JSON.parse(JSON.stringify(state));state.meta=state.meta||{};state.meta.tickNumber=Number(state.meta.tickNumber||0)+50;state.hour=20;state.weather='clear';await page.evaluate(()=>window.ChatGPTFarmPhaserDebug.reload());await page.waitForTimeout(650);let light=await snap();if(light.lightCycle?.hour!==20||light.lightCycle?.alpha<.2)failures.push(`dusk lighting failed: ${JSON.stringify(light.lightCycle)}`);await page.evaluate(()=>window.ChatGPTFarmPhaserDebug.focusWorldUnit(64,34,1.0));await page.waitForTimeout(200);await page.screenshot({path:'phaser-qa/mobile-dusk.png'});state.hour=2;state.meta.tickNumber++;await page.evaluate(()=>window.ChatGPTFarmPhaserDebug.reload());await page.waitForTimeout(650);light=await snap();if(light.lightCycle?.hour!==2||light.lightCycle?.alpha<.4)failures.push(`night lighting failed: ${JSON.stringify(light.lightCycle)}`);await page.screenshot({path:'phaser-qa/mobile-night.png'});state.hour=12;state.weather='rain';state.meta.tickNumber++;await page.evaluate(()=>window.ChatGPTFarmPhaserDebug.reload());await page.waitForTimeout(650);

state=JSON.parse(JSON.stringify(state));state.meta=state.meta||{};state.meta.tickNumber=Number(state.meta.tickNumber||0)+100;const rabbit=state.ecologySystem?.wildlife?.find(x=>x.id==='W-RABBIT-001');if(rabbit){rabbit.previousPosition={...rabbit.position};rabbit.movement={from:{...rabbit.position},to:{x:Math.min(95,rabbit.position.x+5),y:rabbit.position.y+2},goal:{x:Math.min(95,rabbit.position.x+7),y:rabbit.position.y+2},worldDay:state.day,worldHour:state.hour,speed:3};rabbit.position={...rabbit.movement.to}}
await page.evaluate(()=>window.ChatGPTFarmPhaserDebug.reload());await page.waitForTimeout(800);s=await snap();if(!s.positions['W-RABBIT-001'])failures.push('same-page heartbeat lost rabbit');if(s.movingEntities<1)failures.push('heartbeat did not create visible movement');await page.screenshot({path:'phaser-qa/mobile-heartbeat.png'});

fs.writeFileSync('phaser-qa/report.json',JSON.stringify({base,snapshot:s,errors,failures},null,2));
await browser.close();
if(errors.length)console.error(errors.join('\n'));
if(failures.length){console.error(failures.join('\n'));process.exit(1)}
console.log(`Phaser QA passed: ${s.trees} trees, ${s.wildlife} wildlife, ${s.movingEntities} moving entities, zero trees in water.`);
