import { chromium } from 'playwright';
import fs from 'node:fs';
import { migrateWorld, advanceEcology } from '../engine.js';

const base=process.env.BASE_URL||'http://127.0.0.1:4173/';
const qaMode=process.env.QA_MODE||'unknown';
fs.mkdirSync('visual-qa',{recursive:true});
let qaState=migrateWorld(JSON.parse(fs.readFileSync('world/state.json','utf8')));advanceEcology(qaState);const originalState=JSON.parse(JSON.stringify(qaState));fs.writeFileSync('visual-qa/state.json',JSON.stringify(qaState));
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:412,height:915},deviceScaleFactor:1,isMobile:true,hasTouch:true});
const page=await context.newPage();
await page.route(/raw\.githubusercontent\.com\/kyle8824\/chatgptfarm\/main\/world\/state\.json.*/,route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(qaState)}));
const errors=[],failures=[];page.on('pageerror',e=>errors.push(`pageerror: ${e.message}`));page.on('console',m=>{if(m.type()==='error')errors.push(`console: ${m.text()}`)});
await page.goto(base,{waitUntil:'domcontentloaded',timeout:60000});
await page.waitForFunction(()=>document.querySelector('#loading')?.classList.contains('hidden')&&window.ChatGPTFarmRendererDebug?.snapshot().items?.length>0,{timeout:60000});await page.waitForTimeout(1400);
const snap=()=>page.evaluate(()=>window.ChatGPTFarmRendererDebug.snapshot());let snapshot=await snap();
if(snapshot.version!=='v13-world-quality')failures.push(`expected v13-world-quality renderer, got ${snapshot.version}`);if((snapshot.riverCollisions||[]).length)failures.push(`river/object collisions: ${snapshot.riverCollisions.map(x=>`${x.label}:${x.clearance}px`).join(', ')}`);if((snapshot.treeCollisions||[]).length)failures.push(`aggregate tree/object collisions: ${snapshot.treeCollisions.map(x=>x.label).join(', ')}`);if(!snapshot.layers||snapshot.layers.bank<1||snapshot.layers.water<1||snapshot.layers.shore<1||snapshot.layers.world<1)failures.push('depth layer stack is incomplete');if(snapshot.river?.mode!=='variable-ribbon'||snapshot.river.samples<100||snapshot.river.variation<1.12)failures.push(`river is not a sufficiently variable ribbon: ${JSON.stringify(snapshot.river)}`);
const status=(await page.locator('#worldStatus strong').textContent())||'';if(!status.includes('0.9')||status.includes('0.7'))failures.push(`status is exposing stale schema version: ${status}`);
const items=snapshot.items||[],trees=items.filter(x=>x.kind==='tree'),reeds=items.filter(x=>x.kind==='reed-cluster'||x.kind==='reed_stand'),agents=items.filter(x=>x.kind==='agent'),wildlife=items.filter(x=>String(x.kind||'').startsWith('wildlife-')),raisedClay=items.filter(x=>x.kind==='clay_bank');if(trees.length<10)failures.push(`expected visible forest population, got ${trees.length} trees`);if(agents.length!==2)failures.push(`expected 2 agents, got ${agents.length}`);if(wildlife.length<8)failures.push(`expected living wildlife population, got ${wildlife.length}`);if((snapshot.ecology?.traceCount||0)<1)failures.push('expected at least one source-linked wildlife trace after QA ecology advance');if((snapshot.ecology?.ambient?.birds||0)<1)failures.push('ambient bird population is missing');if(raisedClay.length)failures.push('clay bank is incorrectly present in raised/depth-sorted layer');if(trees.length&&reeds.length){const minTree=Math.min(...trees.map(x=>Number(x.height)||0)),maxTree=Math.max(...trees.map(x=>Number(x.height)||0)),maxReed=Math.max(...reeds.map(x=>Number(x.height)||0));if(maxReed>=minTree*.72)failures.push(`reed/tree scale regression: max reed ${maxReed}px vs min tree ${minTree}px`);if(maxTree>84)failures.push(`forest dominance regression: max tree visual height ${maxTree}px`)}
const giant=items.filter(x=>['low-vegetation','ground-object','shrub'].includes(x.tier)&&Number(x.height)>72);if(giant.length)failures.push(`oversized low-tier visuals: ${giant.map(x=>`${x.kind}:${x.height}`).join(', ')}`);if(agents.length===2&&agents.every(x=>Number.isFinite(x.screenX)&&Number.isFinite(x.screenBaseY))){const d=Math.hypot(agents[0].screenX-agents[1].screenX,agents[0].screenBaseY-agents[1].screenBaseY);if(d<22)failures.push(`collocated agents are visually merged: ${d.toFixed(1)}px apart`)}
function screenPoint(s,item){const a=s.viewport.anchor;return{x:a.x+((item.screenX??item.worldX)-s.camera.x)*s.camera.scale,y:a.y+((item.screenBaseY??item.worldY)-s.camera.y)*s.camera.scale}}
function assertFocusVisible(s,label){const id=s.focus?.wildlifeId||s.focus?.agentId,item=(s.items||[]).find(x=>x.sourceId===id);if(!item){failures.push(`${label}: focus subject ${id} is missing`);return}const p=screenPoint(s,item),w=s.viewport.width,h=s.viewport.height;if(p.x<40||p.x>w-40||p.y<115||p.y>h-190)failures.push(`${label}: focus subject is outside useful viewport at ${p.x.toFixed(0)},${p.y.toFixed(0)}`);const a=s.viewport.anchor;if(Math.hypot(p.x-a.x,p.y-a.y)>190)failures.push(`${label}: focus subject is too far from camera anchor`)}
async function shot(name){await page.screenshot({path:`visual-qa/${name}.png`,fullPage:false})}
try{
 await shot('mobile-auto');assertFocusVisible(snapshot,'initial AUTO');
 for(const [button,name,id] of [['MARA','mobile-mara','agent-mara'],['IVO','mobile-ivo','agent-ivo']]){await page.getByRole('button',{name:button,exact:true}).click();await page.waitForTimeout(700);const follow=await page.evaluate(agentId=>{const s=window.ChatGPTFarmRendererDebug.snapshot(),a=(s.items||[]).find(x=>x.kind==='agent'&&x.sourceId===agentId);return{camera:s.camera,agent:a||null}},id);if(!follow.agent||!Number.isFinite(follow.agent.screenX)||!Number.isFinite(follow.agent.screenBaseY))failures.push(`${button} follow target is missing from renderer debug state`);else{const d=Math.hypot(follow.camera.x-follow.agent.screenX,follow.camera.y-follow.agent.screenBaseY);if(d>14)failures.push(`${button} camera is not following the rendered agent: ${d.toFixed(1)}px off target`)}await shot(name)}
 await page.getByRole('button',{name:'AUTO',exact:true}).click();await page.waitForTimeout(350);
 await page.evaluate(()=>window.ChatGPTFarmRendererDebug.focusWorldUnit(48,19,1.45));await page.waitForTimeout(250);await shot('mobile-creek');
 await page.evaluate(()=>window.ChatGPTFarmRendererDebug.focusWorldUnit(86,23,1.55));await page.waitForTimeout(250);await shot('mobile-east-bank');
 await page.evaluate(()=>window.ChatGPTFarmRendererDebug.focusWorldUnit(73,28,1.5));await page.waitForTimeout(250);await shot('mobile-stone-bank');
 if(!await page.evaluate(()=>window.ChatGPTFarmRendererDebug.focusWildlife('W-DEER-001',1.9)))failures.push('could not focus deer for visual QA');await page.waitForTimeout(250);await shot('mobile-deer');if(!await page.evaluate(()=>window.ChatGPTFarmRendererDebug.focusWildlife('W-BEAR-001',1.75)))failures.push('could not focus bear for visual QA');await page.waitForTimeout(250);await shot('mobile-bear');
 await page.locator('#pulseButton').click();await page.waitForTimeout(350);await shot('mobile-world-pulse');if(!await page.locator('#pulseDrawer').evaluate(el=>el.classList.contains('open')))failures.push('World Pulse drawer did not open');for(const [tab,name] of [['relationship','mobile-relationship'],['dna','mobile-decision-dna'],['controls','mobile-ai-usage']]){await page.locator(`[data-pulse-tab="${tab}"]`).click();await page.waitForTimeout(160);await shot(name)}const toggles=await page.locator('#pulseControls input[data-ai]').count();if(toggles!==3)failures.push(`expected 3 AI controls, got ${toggles}`);await page.locator('#pulseClose').click();
 // Reproduce the failure users actually see: state changes while the same AUTO page stays open.
 qaState=JSON.parse(JSON.stringify(originalState));qaState.meta=qaState.meta||{};qaState.meta.tickNumber=Number(qaState.meta.tickNumber||0)+100;qaState.meta.lastAdvancedAt=new Date(Date.now()-10*60*1000).toISOString();qaState.ecologySystem.events=[];const mara=qaState.agents.find(x=>x.id==='agent-mara');mara.position='clay';mara.coordinates={x:86,y:23};mara.currentAction='Inspect clay bank';mara.mind=mara.mind||{};mara.mind.currentGoal='Inspect the clay bank after a new heartbeat.';mara.mind.intent='Examine the clay exposure.';mara.activeAction={id:'QA-HEARTBEAT',decisionId:'QA-HEARTBEAT',label:'Inspect clay bank',actionId:'__qa__',worldDay:qaState.day,worldHour:qaState.hour,from:{x:86,y:23},to:{x:86,y:23},target:{x:86,y:23},moving:false,phases:[{id:'decide',label:'Deciding',start:0,end:.1},{id:'interact',label:'Acting',start:.1,end:.8},{id:'resolve',label:'Resolving',start:.8,end:1}],outcome:{success:true,detail:'QA heartbeat'}};qaState.liveThreads=[{id:'QA-THREAD',kind:'qa',title:'Heartbeat focus',summary:'Mara changed state after page load.',urgency:95,agentIds:['agent-mara']}];
 await page.getByRole('button',{name:'AUTO',exact:true}).click();await page.evaluate(()=>window.ChatGPTFarmRendererDebug.reload());await page.waitForTimeout(900);const heartbeat=await snap();assertFocusVisible(heartbeat,'heartbeat AUTO');if(heartbeat.focus?.agentId!=='agent-mara')failures.push(`heartbeat AUTO focus did not follow Mara: ${heartbeat.focus?.agentId}`);const hbStatus=(await page.locator('#focusCard').textContent())||'';if(!/Mara/i.test(hbStatus)||!/CLAY/i.test(hbStatus))failures.push(`heartbeat focus card/camera context diverged: ${hbStatus}`);await shot('mobile-heartbeat-auto');
}catch(e){failures.push(`interaction QA failed: ${String(e.message||e).slice(0,300)}`);try{await shot('mobile-interaction-error')}catch{}}
fs.writeFileSync('visual-qa/report.json',JSON.stringify({qaMode,base,snapshot,errors,failures,wildlifeCount:wildlife.length,traceCount:snapshot.ecology?.traceCount||0,ecologyEvents:snapshot.ecology?.eventCount||0},null,2));await browser.close();if(errors.length)console.error(errors.join('\n'));if(failures.length){console.error(failures.join('\n'));process.exit(1)}console.log(`Visual QA passed (${qaMode}): ${trees.length} trees, ${agents.length} agents, ${wildlife.length} wildlife, variable-ribbon creek.`);
