const OWNER='kyle8824',REPO='chatgptfarm',PATH='world/control.json',API=`https://api.github.com/repos/${OWNER}/${REPO}/contents/${PATH}`;
const allowed=new Set(['agent-mara','agent-ivo']);
function clean(body,current){const next=structuredClone(current);next.ai||={};next.ai.people||={};next.ai.wildlife||={enabled:false,individuals:{}};if(body?.people)for(const [id,v]of Object.entries(body.people))if(allowed.has(id)&&typeof v==='boolean')next.ai.people[id]=v;if(typeof body?.wildlifeEnabled==='boolean')next.ai.wildlife.enabled=body.wildlifeEnabled;if(body?.wildlifeIndividuals&&typeof body.wildlifeIndividuals==='object')for(const [id,v]of Object.entries(body.wildlifeIndividuals))if(/^W-[A-Z]+-\d+$/.test(id)&&typeof v==='boolean')next.ai.wildlife.individuals[id]=v;return next}
export default async function handler(req,res){
 res.setHeader('Cache-Control','no-store');
 if(req.method==='GET'){try{const r=await fetch(`https://raw.githubusercontent.com/${OWNER}/${REPO}/main/${PATH}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(String(r.status));return res.status(200).json(await r.json())}catch(e){return res.status(502).json({error:'control_read_failed'})}}
 if(req.method!=='POST')return res.status(405).json({error:'method_not_allowed'});
 const secret=process.env.CONTROL_KEY,token=process.env.GITHUB_CONTROL_TOKEN;if(!secret||!token)return res.status(503).json({error:'owner_controls_not_configured'});if(req.headers['x-control-key']!==secret)return res.status(401).json({error:'unauthorized'});
 try{const r=await fetch(API,{headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'chatgptfarm-control'}});if(!r.ok)throw Error(`read ${r.status}`);const file=await r.json(),current=JSON.parse(Buffer.from(file.content,'base64').toString('utf8')),next=clean(req.body||{},current);const content=Buffer.from(JSON.stringify(next,null,2)+'\n').toString('base64');const w=await fetch(API,{method:'PUT',headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json','User-Agent':'chatgptfarm-control'},body:JSON.stringify({message:'control: update AI runtime settings',content,sha:file.sha,branch:'main'})});if(!w.ok)throw Error(`write ${w.status}: ${(await w.text()).slice(0,160)}`);return res.status(200).json({ok:true,control:next})}catch(e){return res.status(500).json({error:'control_write_failed',detail:String(e.message||e).slice(0,180)})}
}
